window.DK_TRANSLATIONS = window.DK_TRANSLATIONS || {};
window.DK_TRANSLATIONS.vi = {
  _lang: "vi",
  _title: "Điều khoản và Điều kiện — Heqiyou · Deployku",
  "eyebrow": "Pháp lý · Heqiyou",
  "h1": "Điều khoản và Điều kiện",
  "meta": "<span>Ngày hiệu lực: 28 June 2026</span><span>Phiên bản 1.3</span><span>Deployku Pte Ltd · Singapore</span>",
  "intro": `Các Điều khoản và Điều kiện này (gọi là "<strong>Điều khoản</strong>") là thỏa thuận giữa bạn và <strong>Deployku Pte Ltd</strong>, một công ty được đăng ký tại Singapore ("<strong>Deployku</strong>", "<strong>chúng tôi</strong>" hoặc "<strong>của chúng tôi</strong>"). Các Điều khoản này điều chỉnh việc bạn sử dụng ứng dụng Heqiyou và mọi thứ trong đó — tất cả các tính năng, nội dung, cùng các trang web và dịch vụ liên quan (gọi chung là "<strong>Dịch vụ</strong>" (Service) hoặc "<strong>Ứng dụng</strong>" (App)).`,
  "nav.product": "Heqiyou",
  "nav.privacy": "Quyền riêng tư",
  "nav.terms": "Điều khoản",
  "nav.cta": "Liên hệ",
  "foot.tagline": `Một studio Singapore xây dựng những sản phẩm thúc đẩy Đông Nam Á.`,
  "foot.company": "Công ty",
  "foot.whatwedo": "Chúng tôi làm gì",
  "foot.approach": "Phương pháp",
  "foot.about": "Giới thiệu",
  "foot.careers": "Tuyển dụng",
  "foot.products": "Sản phẩm",
  "foot.heqiyou": "Heqiyou",
  "foot.legal": "Pháp lý",
  "foot.privacyLink": "Chính sách Quyền riêng tư",
  "foot.termsLink": "Điều khoản &amp; Điều kiện",
  "foot.contact": "Liên hệ",
  "foot.email": "Email",
  "foot.getintouch": "Liên hệ",
  "foot.copyright": "© 2026 Deployku Pte Ltd. Bảo lưu mọi quyền.",
  "foot.built": "Xây dựng tại Singapore · cho Đông Nam Á",
  "body": `
      <p><strong>Vui lòng đọc các Điều khoản này. Bằng việc tạo tài khoản hoặc sử dụng Service, bạn đồng ý với các Điều khoản này và với <a href="privacy.html">Chính sách Quyền riêng tư</a> của chúng tôi. Nếu bạn không đồng ý, đừng sử dụng Service.</strong></p>

      <div class="notice-card">
        <p><strong>Những điều quan trọng cần biết ngay từ đầu:</strong></p>
        <ul>
          <li><strong>Bạn phải từ 18 tuổi trở lên mới được sử dụng Service.</strong></li>
          <li><strong>Các cuộc gọi thoại được ghi âm và chuyển thành văn bản nhằm mục đích an toàn</strong> (xem Mục 8 và <a href="privacy.html">Chính sách Quyền riêng tư</a>). Việc thực hiện hoặc tham gia một cuộc gọi đồng nghĩa với việc bạn đồng ý với điều này. Nếu bạn không đồng ý, đừng sử dụng các tính năng gọi.</li>
          <li><strong>"Glimpse" cho phép bạn đăng một video ngắn về chính mình.</strong> Trong chế độ khám phá ẩn danh, tên và hồ sơ của bạn vẫn được ẩn, nhưng <strong>video vẫn hiển thị khuôn mặt và ngoại hình của bạn</strong>. Bằng việc đăng một video như vậy, bạn đồng ý rằng video có thể được kiểm duyệt và hiển thị cho đối tượng mà bạn chọn.</li>
          <li><strong>Credits không phải là tiền. Credits không được hoàn lại, và bạn có thể mất Credits nếu vi phạm các Điều khoản này</strong> (xem Mục 7).</li>
          <li><strong>"Premium" là một gói đăng ký tự động gia hạn và tự động tính phí bạn cho đến khi bạn hủy</strong> (xem Mục 6.9).</li>
          <li><strong>Các Điều khoản này giới hạn trách nhiệm pháp lý của chúng tôi đối với bạn và bao gồm một điều khoản bồi thường có lợi cho chúng tôi</strong> (xem Mục 15–17).</li>
        </ul>
      </div>

      <h2 id="s1">1. Về Service</h2>
      <p>1.1 Heqiyou là một ứng dụng hẹn hò và mạng xã hội ưu tiên giọng nói. Thay vì lướt qua các bức ảnh, bạn gặp gỡ mọi người qua những cuộc gọi thoại ngắn, ẩn danh ("<strong>Mini-Date</strong>" (buổi hẹn nhỏ)). Tên và ảnh vẫn được ẩn trong suốt cuộc gọi. Chỉ khi <strong>cả hai</strong> bạn chọn tiếp tục sau đó thì hồ sơ của bạn mới được tiết lộ cho nhau và một cuộc trò chuyện riêng tư được mở ra.</p>
      <p>1.2 Service có thể bao gồm: đăng ký bằng số điện thoại hoặc bằng bên thứ ba như Apple hoặc Google; cuộc gọi thoại ẩn danh; ghép đôi dựa trên hàng đợi; gợi ý về mức độ tương hợp; trò chuyện sau khi có một Match; cuộc gọi trực tiếp (không ẩn danh) giữa những người dùng đã ghép đôi; một trợ lý lên kế hoạch hẹn hò bằng AI (có thể đề xuất một khu vực khởi điểm từ vị trí thiết bị của bạn và cho phép bạn mở các ứng dụng như gọi xe với điểm đến đã được điền sẵn); một người bạn đồng hành giọng nói bằng AI; các video ngắn với chú thích tùy chọn và một bản xuất tóm lược ngày ("<strong>Glimpse</strong>"); kết nối bạn bè và một tính năng cam kết độc quyền ("<strong>Pledge</strong>"); một "nhật ký đôi" chung về các địa điểm ("<strong>Places</strong>"); tạo hồ sơ và ảnh; mua Credits; một gói đăng ký <strong>Premium</strong>; và các quảng cáo mà bạn có thể xem để nhận thưởng.</p>
      <p>1.3 Service chỉ khả dụng tại các khu vực mà chúng tôi lựa chọn ("<strong>Khu vực Được hỗ trợ</strong>"). Việc ghép đôi và khám phá Glimpse thường giới hạn ở những người trong cùng một Khu vực Được hỗ trợ. Chúng tôi có thể thêm, bớt hoặc thay đổi các Khu vực Được hỗ trợ bất cứ lúc nào, mà không cần báo trước.</p>
      <p>1.4 Chúng tôi liên tục cải thiện Service. Chúng tôi có thể thêm, thay đổi, tạm dừng hoặc gỡ bỏ các tính năng (bao gồm cả những tính năng vẫn đang phát triển, như việc kiểm tra danh tính chặt chẽ hơn hoặc các phương thức thanh toán mới), hoặc đặt ra giới hạn cho các tính năng, vào bất cứ lúc nào và theo quyết định của chúng tôi. Nếu một thay đổi ảnh hưởng nghiêm trọng và tiêu cực đến một tính năng có trả phí, chúng tôi sẽ cố gắng thông báo trước cho bạn.</p>
      <p>1.5 <strong>Glimpse.</strong> Glimpse cho phép bạn quay một video ngắn (vài giây) về chính mình, tùy chọn thêm một chú thích ngắn, và đăng nó vào một "khung" thời gian lặp lại cho đối tượng mà bạn chọn: <strong>Hopeful</strong> (khám phá ẩn danh), <strong>Matched</strong>, <strong>Friends</strong>, hoặc <strong>Pledged</strong>. Các video và chú thích gửi đến đối tượng Hopeful hoặc Matched sẽ được kiểm tra bằng kiểm duyệt tự động trước khi hiển thị, và được hiển thị cùng một biểu tượng trừu tượng và một điểm tương hợp — chứ không phải tên hay hồ sơ của bạn (mặc dù video có hiển thị ngoại hình của bạn). Các video gửi đến Friends hoặc một đối tác Pledged được hiển thị kèm tên và ảnh của bạn cho những người đó. Glimpse cũng có thể ghép các clip trong ngày (của bạn và của bạn bè/đối tác) thành một video tóm lược ngắn mà bạn có thể lưu hoặc chia sẻ. Việc đăng lên Hopeful hoặc Matched, và việc xuất một bản tóm lược, có thể tốn Credits hoặc được bao gồm trong Premium; các bài đăng cho Friends/Pledged là miễn phí (xem Mục 6).</p>
      <p>1.6 <strong>Connections, Friends và Pledge.</strong> Bạn có thể hình thành các kết nối liên tục với những người dùng khác: một <strong>Match</strong> (sau một Mini-Date chung), một <strong>Friend</strong> (được thêm bằng một mã bạn bè cá nhân), và một <strong>Pledge</strong> (một cam kết độc quyền, song phương giữa những người dùng đã ghép đôi, được hình thành bằng một mã ghép đôi). Trong khi bạn đang trong trạng thái Pledged, một số tính năng hẹn hò "mù" và ghép đôi sẽ bị tắt, và một số tính năng chỉ hoạt động với đối tác Pledged của bạn. Bạn có thể chấm dứt bất kỳ kết nối nào vào bất cứ lúc nào.</p>
      <p>1.7 <strong>Places (nhật ký đôi).</strong> Những người dùng đã kết nối (Matched hoặc Pledged) có thể duy trì một nhật ký chung về những địa điểm họ đã cùng nhau đến — bao gồm tên và vị trí địa điểm, ngày tháng, ảnh, chú thích và ghi chú do một trong hai người thêm vào. Cả hai thành viên của kết nối đều có thể xem nhật ký. Việc đăng một địa điểm có thể tốn Credits hoặc được bao gồm trong Premium (xem Mục 6).</p>
      <p>1.8 <strong>Người bạn đồng hành giọng nói bằng AI.</strong> Service có thể cho phép bạn trò chuyện bằng giọng nói trực tiếp với một người bạn đồng hành AI tự động (không phải một người khác). Tính năng này có giới hạn thời gian và có thể tốn Credits.</p>
      <p>1.9 <strong>Chế độ Ambassador.</strong> Chúng tôi có thể mời một số người dùng vào chế độ "ambassador" (đại sứ) tùy chọn nhằm giúp khởi tạo hàng đợi ghép đôi. Nếu bạn bật chế độ này, một số cuộc gọi của bạn có thể được gắn cờ để loại trừ khỏi một số chỉ số nhất định, và một cuộc gọi bạn bắt đầu ở chế độ này có thể không tốn Credits của bạn. Chúng tôi có thể cấp, thay đổi hoặc gỡ bỏ tư cách đủ điều kiện ambassador theo quyết định của chúng tôi.</p>

      <h2 id="s2">2. Định nghĩa</h2>
      <p>Trong các Điều khoản này:</p>
      <ul>
        <li>"<strong>Account</strong>" (Tài khoản) nghĩa là tài khoản mà bạn đăng ký với Service.</li>
        <li>"<strong>Content</strong>" (Nội dung) nghĩa là bất kỳ dữ liệu, văn bản, âm thanh, giọng nói, video, hình ảnh, ảnh, hồ sơ, tin nhắn, bản chép lời, đánh giá, báo cáo, mục địa điểm hoặc tài liệu nào khác trên Service.</li>
        <li>"<strong>User Content</strong>" (Nội dung Người dùng) nghĩa là Content do bạn cung cấp — hồ sơ của bạn, ảnh, <strong>video Glimpse</strong>, <strong>các mục nhật ký đôi (địa điểm, ảnh, chú thích và ghi chú)</strong>, giọng nói của bạn trong các cuộc gọi, và các tin nhắn trò chuyện.</li>
        <li>"<strong>Credits</strong>" nghĩa là các đơn vị trong ứng dụng được dùng để thanh toán cho một số tính năng nhất định (xem Mục 6).</li>
        <li>"<strong>Premium</strong>" nghĩa là một gói đăng ký trả phí tự động gia hạn, mở khóa một số tính năng nhất định và/hoặc loại bỏ một số khoản phí Credit nhất định (xem Mục 6.9).</li>
        <li>"<strong>Mini-Date</strong>" nghĩa là một cuộc gọi thoại ẩn danh, có giới hạn thời gian giữa hai người dùng do hệ thống ghép đôi của chúng tôi thiết lập.</li>
        <li>"<strong>Direct Call</strong>" (Cuộc gọi Trực tiếp) nghĩa là một cuộc gọi thoại không ẩn danh giữa những người dùng đã ghép đôi với nhau.</li>
        <li>"<strong>Match</strong>" nghĩa là trạng thái mà cả hai người dùng đã chọn tiếp tục sau một Mini-Date, để hồ sơ của họ được tiết lộ cho nhau.</li>
        <li>"<strong>Glimpse</strong>" hoặc "<strong>Glimpse Clip</strong>" nghĩa là một video ngắn về chính bạn mà bạn đăng tải.</li>
        <li>"<strong>Connection</strong>" (Kết nối) nghĩa là một liên kết liên tục giữa hai người dùng — một Match, một Friend, hoặc một Pledge.</li>
        <li>"<strong>Friend</strong>" nghĩa là một kết nối phi lãng mạn được thêm bằng mã bạn bè.</li>
        <li>"<strong>Pledge</strong>" nghĩa là một cam kết độc quyền, song phương giữa hai người dùng đã ghép đôi.</li>
        <li>"<strong>Places</strong>" hoặc "<strong>Couple Diary</strong>" (Nhật ký Đôi) nghĩa là nhật ký chung nơi một Connection ghi lại các địa điểm, ảnh, chú thích và ghi chú.</li>
        <li>"<strong>Marks</strong>" nghĩa là tên "Heqiyou", logo, các nhãn hiệu chữ, và tất cả thương hiệu cùng thiết kế liên quan.</li>
        <li>"<strong>Virtual Items</strong>" (Vật phẩm Ảo) nghĩa là Credits, các lợi ích Premium và bất kỳ hàng hóa hay tính năng ảo nào khác trong Service.</li>
      </ul>

      <h2 id="s3">3. Ai Có Thể Sử Dụng Service</h2>
      <p>3.1 <strong>Bạn phải từ 18 tuổi trở lên.</strong> Bạn phải đủ ít nhất 18 tuổi mới được tạo một Account hoặc sử dụng Service, và bạn xác nhận rằng bạn đủ tuổi. Chúng tôi có thể đóng bất kỳ Account nào mà chúng tôi có cơ sở hợp lý để tin rằng thuộc về một người dưới 18 tuổi, mà không hoàn tiền, và chúng tôi có thể yêu cầu bằng chứng về độ tuổi vào bất cứ lúc nào.</p>
      <p>3.2 <strong>Bạn được phép đồng ý, và bạn có lý lịch trong sạch.</strong> Bạn xác nhận rằng: (a) bạn có thể giao kết hợp đồng này một cách hợp pháp; (b) không có điều gì trong luật pháp nơi bạn sinh sống ngăn cản bạn sử dụng Service; (c) bạn chưa bao giờ bị kết án về, và không đang bị truy tố về, một tội nghiêm trọng, một tội về tình dục, hay bất kỳ tội nào liên quan đến bạo lực hoặc đe dọa bạo lực; và (d) bạn không bị yêu cầu phải đăng ký là tội phạm tình dục ở bất cứ đâu.</p>
      <p>3.3 <strong>Nơi bạn có thể sử dụng.</strong> Service chỉ dành để sử dụng tại các Khu vực Được hỗ trợ. Đừng sử dụng — hay cố gắng vượt qua các giới hạn theo khu vực (ví dụ bằng VPN, vị trí giả, hoặc thông tin đăng ký sai sự thật) — từ bên ngoài một Khu vực Được hỗ trợ.</p>
      <p>3.4 <strong>Mỗi người một tài khoản.</strong> Bạn chỉ được có một Account, dành cho mục đích sử dụng cá nhân, phi thương mại của riêng bạn. Đừng tạo hoặc vận hành một Account thay cho người khác, một tổ chức, hay một bot.</p>
      <p>3.5 <strong>Không quay lại sau khi bị cấm.</strong> Nếu trước đây chúng tôi đã đình chỉ, cấm hoặc gỡ bỏ bạn, đừng tạo một Account mới trừ khi chúng tôi cho bạn sự cho phép bằng văn bản.</p>

      <h2 id="s4">4. Account Của Bạn</h2>
      <p>4.1 <strong>Đăng ký.</strong> Để sử dụng Service, bạn đăng ký bằng một số điện thoại di động hợp lệ có thể nhận mã một lần, hoặc bằng cách đăng nhập với một nhà cung cấp được hỗ trợ như Apple hoặc Google. Một số điện thoại đã được xác minh sẽ là danh tính chính của bạn cho một số tính năng. Bạn sẽ trải qua quá trình thiết lập ban đầu — cung cấp tên hoặc tên hiển thị, ngày sinh, giới tính, thành phố, và một số tùy chọn. Bạn cũng có thể thêm một địa chỉ email và một ảnh hồ sơ.</p>
      <p>4.2 <strong>Giữ thông tin chính xác.</strong> Hãy cung cấp cho chúng tôi thông tin đúng sự thật, cập nhật và đầy đủ, bao gồm ngày sinh thật của bạn, và giữ cho thông tin được cập nhật. Nói dối về độ tuổi, danh tính hoặc các chi tiết đăng ký khác của bạn là một vi phạm nghiêm trọng đối với các Điều khoản này.</p>
      <p>4.3 <strong>Giữ thông tin an toàn.</strong> Bạn chịu trách nhiệm về mọi điều xảy ra trên Account của bạn và về việc bảo vệ thiết bị cùng số điện thoại của mình. Hãy báo cho chúng tôi ngay tại <strong><a href="mailto:admin@deployku.com">admin@deployku.com</a></strong> nếu bạn cho rằng có ai đó đã truy cập Account của bạn mà không được phép.</p>
      <p>4.4 <strong>Xác minh.</strong> Chúng tôi có thể yêu cầu bạn xác minh danh tính, độ tuổi, số điện thoại, ảnh hoặc "tính sống động" (bao gồm thông qua các nhà cung cấp xác minh bên ngoài) trước hoặc trong khi bạn sử dụng Service, hoặc để mở khóa một số tính năng nhất định (như nhận cuộc gọi). Nếu bạn không hoàn thành một bước kiểm tra bắt buộc, quyền truy cập của bạn có thể bị giới hạn hoặc đình chỉ.</p>
      <p>4.5 <strong>Kiểm tra ảnh và video.</strong> Ảnh và video Glimpse bạn tải lên có thể được kiểm tra bởi các hệ thống tự động và/hoặc con người trước khi hiển thị. Chúng tôi có thể từ chối, gỡ bỏ hoặc từ chối hiển thị bất kỳ ảnh hoặc video nào theo quyết định của chúng tôi — ví dụ nếu nó hiển thị ảnh khỏa thân, vũ khí, ma túy, hoặc tài liệu phản cảm, hoặc không hiển thị bạn.</p>
      <p>4.6 <strong>Quyền của thiết bị.</strong> Một số tính năng cần quyền của thiết bị — ví dụ micrô (cuộc gọi và người bạn đồng hành AI), camera (Glimpse và ảnh), thư viện ảnh (tải lên), và tùy chọn vị trí (để đề xuất một khu vực lên kế hoạch hẹn hò, giúp bạn gắn thẻ các địa điểm gần đó, hoặc căn giữa một bản đồ). Chúng tôi chỉ đọc vị trí của bạn khi bạn sử dụng một tính năng như vậy; chúng tôi không theo dõi nó trong nền. Bạn có thể quản lý các quyền trong cài đặt thiết bị của bạn; việc tắt một quyền có thể vô hiệu hóa tính năng tương ứng.</p>

      <h2 id="s5">5. Ghép Đôi, Chất Lượng và Sự Công Bằng</h2>
      <p>5.1 <strong>Cách ghép đôi hoạt động.</strong> Các hệ thống của chúng tôi ghép đôi người dùng dựa trên những yếu tố có thể bao gồm các tùy chọn của bạn, mức độ hoàn thiện của hồ sơ của bạn, các gợi ý về độ tương hợp từ các câu trả lời trong quá trình thiết lập ban đầu của bạn, khu vực của bạn, thời gian bạn đã chờ đợi, và các điểm số nội bộ về chất lượng, uy tín và độ tương hợp. Việc ghép đôi dựa trên thuật toán và theo quyết định của chúng tôi, và <strong>chúng tôi không bảo đảm bất kỳ kết quả ghép đôi cụ thể nào, số lượng match nào, tần suất gọi nào, hay kết quả nào — dù là lãng mạn hay khác.</strong></p>
      <p>5.2 <strong>Các điểm số nội bộ.</strong> Để giữ cho mọi thứ an toàn và cân bằng, chúng tôi duy trì các chỉ số nội bộ, riêng tư cho các Account — chẳng hạn như điểm uy tín (bị ảnh hưởng bởi các đánh giá sau cuộc gọi và các báo cáo) và điểm chất lượng ghép đôi (bị ảnh hưởng bởi kết quả của các cuộc gọi). Chúng tôi sử dụng những điểm này cho việc ghép đôi, tính đủ điều kiện, giới hạn tần suất và an toàn. Chúng không phải là một sự đánh giá về bạn với tư cách một con người, không được hiển thị cho những người dùng khác, và không phải là một lời hứa từ chúng tôi.</p>
      <p>5.3 <strong>Tính đủ điều kiện và các giới hạn.</strong> Một số tính năng (như tham gia hàng đợi nhận cuộc gọi) có thể yêu cầu những điều như một số điện thoại đã được xác minh, một hồ sơ hoàn chỉnh, một ảnh hoặc avatar hệ thống đã được phê duyệt, tư cách tốt, hoàn thành xác minh, và duy trì trong các giới hạn sử dụng (ví dụ giới hạn hàng tháng về số cuộc gọi nhận được, hoặc giới hạn hàng ngày về một số hành động nhất định). Chúng tôi có thể thay đổi các yêu cầu và giới hạn này bất cứ lúc nào.</p>
      <p>5.4 <strong>Giữ ẩn danh trước khi tiết lộ.</strong> Trong một Mini-Date, các hồ sơ hiển thị dưới dạng avatar trừu tượng. Đừng cố gắng phá vỡ tính ẩn danh — ví dụ bằng cách cho hoặc hỏi tên thật, ảnh, tài khoản mạng xã hội, số điện thoại, hoặc các chi tiết liên hệ hay nhận dạng khác trong một Mini-Date.</p>
      <p>5.5 <strong>Tiết lộ song phương.</strong> Hồ sơ và trò chuyện chỉ được mở khóa nếu cả hai người chọn tiếp tục sau một Mini-Date. Một quyết định không tiếp tục là quyết định cuối cùng cho cuộc gọi đó, và chúng tôi không tiết lộ nó theo cách nhằm làm bất kỳ ai bối rối.</p>
      <p>5.6 <strong>Khám phá Glimpse.</strong> Khi bạn đăng một Glimpse, bạn hiểu rằng: (a) các video và chú thích gửi đến <strong>Hopeful</strong> hoặc <strong>Matched</strong> được kiểm tra bằng kiểm duyệt tự động trước và có thể bị từ chối; (b) trong <strong>Hopeful</strong>, video của bạn được hiển thị cho một nhóm người dùng đủ điều kiện được xếp hạng theo độ tương hợp trong khu vực của bạn cho khung thời gian đó — tên và hồ sơ của bạn được ẩn, nhưng <strong>video hiển thị ngoại hình của bạn</strong>; (c) trong <strong>Matched</strong>, <strong>Friends</strong> và <strong>Pledged</strong>, video của bạn được hiển thị kèm tên và ảnh của bạn cho những người bạn đã kết nối; (d) một bản tóm lược ngày mà bạn tạo có thể kết hợp các clip của bạn với những clip mà bạn bè/đối tác của bạn đã chia sẻ; và (e) bạn không được đăng một Glimpse hiển thị bất kỳ ai khác ngoài chính bạn mà không có sự đồng ý của họ, hoặc một video vi phạm Mục 9.</p>

      <h2 id="s6">6. Credits, Mua Hàng, Đăng Ký và Thanh Toán</h2>
      <p>6.1 <strong>Credits là gì.</strong> Credits là một giấy phép có giới hạn, cá nhân, không thể chuyển nhượng để sử dụng một số tính năng nhất định — và chúng tôi có thể thu hồi chúng. <strong>Credits không phải là tiền. Chúng không có giá trị tiền mặt, không sinh lãi, và không thể được quy đổi, trao đổi hoặc rút thành bất kỳ thứ gì có giá trị bên ngoài Service.</strong> Bạn không thể bán, trao đổi, tặng, chuyển nhượng hoặc gộp chung Credits.</p>
      <p>6.2 <strong>Cách bạn nhận Credits.</strong> Bạn có thể nhận Credits bằng cách: (a) mua các gói Credit thông qua mua hàng trong ứng dụng với giá hiển thị khi bạn mua; (b) các khoản cấp khuyến mãi hoặc miễn phí (như thưởng đăng ký), theo quyết định của chúng tôi; (c) xem các quảng cáo có thưởng ở những nơi được cung cấp, trong các giới hạn mà chúng tôi đặt ra; và (d) bất kỳ phương thức nào khác mà chúng tôi bổ sung. Chúng tôi có thể thay đổi giá Credit, kích cỡ gói, quy tắc kiếm Credit, chi phí tính năng và các giới hạn bất cứ lúc nào; các thay đổi chỉ áp dụng về sau và không ảnh hưởng đến Credits đã có trong số dư của bạn.</p>
      <p>6.3 <strong>Cách Credits được chi tiêu.</strong> Các tính năng sử dụng Credits — chẳng hạn như bắt đầu các Mini-Date, bắt đầu các Direct Call, tạo các kế hoạch hẹn hò bằng AI, sử dụng người bạn đồng hành giọng nói bằng AI, đăng một Glimpse cho một đối tượng trả phí (Hopeful hoặc Matched), xuất một bản tóm lược Glimpse, và đăng một địa điểm vào nhật ký đôi — tốn số lượng được hiển thị trong App khi bạn sử dụng chúng. Một số trong những điều này có thể miễn phí với một gói đăng ký Premium đang hoạt động, và một số đối tượng Glimpse (Friends và Pledged) luôn miễn phí. Đối với các cuộc gọi tính giờ, Credits có thể được giữ lại khi cuộc gọi bắt đầu và được quyết toán dựa trên thời gian bạn thực sự được kết nối. Nếu một cuộc gọi kết thúc sớm hơn so với đã đặt, bạn có thể bị tính phí theo tỷ lệ, và nếu một cuộc gọi không kết nối được do lỗi từ phía chúng tôi, chúng tôi thường sẽ giải phóng hoặc hoàn lại Credits đã giữ.</p>
      <p>6.4 <strong>Thanh toán và quy tắc của cửa hàng ứng dụng.</strong> Các giao dịch mua trong ứng dụng và các gói đăng ký được xử lý bởi cửa hàng ứng dụng mà bạn đã tải xuống từ đó và/hoặc các nhà cung cấp thanh toán của chúng tôi, và cũng tuân theo các điều khoản của họ. Chúng tôi không lưu trữ đầy đủ chi tiết thẻ của bạn. Chúng tôi có thể bổ sung các phương thức thanh toán khác sau này, với các điều khoản riêng của chúng được hiển thị tại thời điểm mua.</p>
      <p>6.5 <strong>Không hoàn tiền.</strong> <strong>Trừ khi pháp luật hoặc các quy tắc riêng của cửa hàng ứng dụng yêu cầu, tất cả các giao dịch mua Credits và đăng ký là cuối cùng và không được hoàn lại</strong> — bao gồm Credits chưa sử dụng, các phần chưa sử dụng của một gói đăng ký, và các trường hợp tài khoản của bạn bị đóng, đình chỉ hoặc chấm dứt, hoặc Service bị ngừng. Nếu chúng tôi chọn cho bạn một khoản hoàn tiền hoặc tín dụng một lần, điều đó không có nghĩa là chúng tôi sẽ làm vậy lần nữa.</p>
      <p>6.6 <strong>Hết hạn.</strong> Credits hiện tại không hết hạn, nhưng chúng tôi có thể bổ sung các quy tắc hết hạn hoặc không hoạt động hợp lý cho Credits miễn phí/khuyến mãi, và — với thông báo trước hợp lý — cho Credits đã mua, ở những nơi pháp luật cho phép.</p>
      <p>6.7 <strong>Không gian lận hệ thống.</strong> Đừng: (a) nhận Credits, các lợi ích Premium hoặc các Virtual Items khác thông qua gian lận, lỗi, bot, hoặc lạm dụng các cơ chế khuyến mãi/quảng cáo/giới thiệu; (b) khởi tạo các giao dịch hoàn tiền (chargeback) hoặc đảo ngược thanh toán với dụng ý xấu; hoặc (c) mua hoặc bán Credits, gói đăng ký hoặc Account bên ngoài Service. Bất cứ thứ gì có được do vi phạm quy tắc này đều vô hiệu.</p>
      <p>6.8 <strong>Hồ sơ của chúng tôi.</strong> Hồ sơ của chúng tôi (bao gồm sổ cái giao dịch và hồ sơ quyền lợi của chúng tôi), trừ khi có một sai sót rõ ràng, là quyết định cuối cùng về số dư Credit, tình trạng đăng ký và các giao dịch của bạn.</p>
      <p>6.9 <strong>Gói đăng ký Premium (tự động gia hạn).</strong> Premium là một gói đăng ký tự động gia hạn được bán thông qua cửa hàng ứng dụng.</p>
      <ul>
        <li><strong>Tự động gia hạn.</strong> Bạn bị tính phí thông qua tài khoản cửa hàng ứng dụng của bạn khi bạn mua. <strong>Nó tự động gia hạn cho mỗi kỳ mới với giá tại thời điểm đó trừ khi bạn hủy ít nhất 24 giờ trước khi kỳ hiện tại kết thúc</strong> (hoặc theo yêu cầu khác của cửa hàng ứng dụng).</li>
        <li><strong>Quản lý và hủy.</strong> Bạn có thể quản lý hoặc hủy bất cứ lúc nào trong cài đặt đăng ký của cửa hàng ứng dụng của bạn. Việc xóa App <strong>không</strong> hủy nó. Việc hủy có hiệu lực vào cuối kỳ đã trả tiền hiện tại, và bạn vẫn giữ Premium cho đến lúc đó.</li>
        <li><strong>Thay đổi giá.</strong> Chúng tôi có thể thay đổi giá; các thay đổi áp dụng cho các kỳ tương lai và được thông báo theo quy tắc của cửa hàng ứng dụng, mà có thể yêu cầu sự đồng ý của bạn trước.</li>
        <li><strong>Dùng thử miễn phí / khuyến mãi.</strong> Nếu một bản dùng thử miễn phí hoặc khuyến mãi được cung cấp, nó tự động trở thành một gói đăng ký trả phí trừ khi bạn hủy trước khi nó kết thúc; bất kỳ phần chưa sử dụng nào của bản dùng thử đều bị mất khi bạn đăng ký, ở những nơi áp dụng.</li>
        <li><strong>Lợi ích.</strong> Các lợi ích Premium (như đăng các Glimpse hoặc địa điểm mà không tốn Credit, lưu trữ lịch sử nhiều hơn, hoặc các tính năng khác) là một phần của giấy phép sử dụng Service của bạn, không phải là tài sản, có thể thay đổi, và kết thúc khi gói đăng ký của bạn kết thúc hoặc bị hủy.</li>
      </ul>
      <p>6.10 <strong>Điều khoản của Apple / Google.</strong> Ở những nơi cửa hàng ứng dụng yêu cầu, các điều khoản giấy phép và đăng ký tiêu chuẩn của họ cũng được áp dụng, và đơn vị vận hành cửa hàng ứng dụng có thể là một bên thụ hưởng thứ ba có thể thực thi các Điều khoản này (xem Mục 14.3).</p>

      <h2 id="s7">7. Mất Credits; Đình Chỉ và Chấm Dứt bởi Chúng Tôi</h2>
      <p>7.1 <strong>Bạn có thể mất Credits nếu vi phạm quy tắc.</strong> <strong>Nếu bạn vi phạm các Điều khoản này — bao gồm các quy tắc ứng xử ở Mục 9, các quy tắc thanh toán ở Mục 6.7, hoặc các quy tắc đủ điều kiện ở Mục 3 — chúng tôi có thể hủy và tịch thu bất kỳ hoặc toàn bộ Credits của bạn (đã mua, đã kiếm được hoặc miễn phí) và thu hồi các lợi ích Premium, mà không hoàn tiền hoặc bồi thường, ngoài bất kỳ hành động nào khác mà chúng tôi thực hiện.</strong> Chúng tôi có thể làm điều này có hoặc không có một cảnh báo, thời gian chờ, đình chỉ hoặc cấm riêng biệt.</p>
      <p>7.2 <strong>Khi nào chúng tôi có thể hành động.</strong> Chúng tôi có thể cảnh báo bạn, hạn chế các tính năng, áp dụng một thời gian chờ, đình chỉ hoặc cấm vĩnh viễn Account của bạn, và/hoặc tịch thu Credits, nếu chúng tôi có cơ sở hợp lý để tin rằng bạn đã: (a) vi phạm các Điều khoản này hoặc bất kỳ chính sách nào mà chúng dẫn chiếu; (b) thực hiện gian lận, lạm dụng thanh toán hoặc lạm dụng chargeback; (c) quấy rối, đe dọa, làm hại hoặc gây nguy hiểm cho bất kỳ người dùng nào hoặc nhân viên của chúng tôi; (d) nói dối về độ tuổi hoặc danh tính của bạn; (e) sử dụng Service để chào mời thương mại, quảng bá hoặc lừa đảo; (f) tạo nhiều Account hoặc Account trốn tránh lệnh cấm; hoặc (g) có hành vi khác tạo ra rủi ro hoặc khả năng phơi bày pháp lý cho chúng tôi, những người dùng khác, hoặc các bên thứ ba.</p>
      <p>7.3 <strong>Điều gì xảy ra nếu chúng tôi chấm dứt.</strong> Nếu chúng tôi đình chỉ hoặc chấm dứt Account của bạn: (a) quyền sử dụng Service của bạn kết thúc ngay lập tức (hoặc trong thời gian đình chỉ); (b) <strong>tất cả Credits đều bị tịch thu mà không hoàn tiền</strong>, ở mức tối đa mà pháp luật cho phép; (c) các lợi ích Premium ngừng lại (bất kỳ việc hủy hoặc hoàn tiền đăng ký nào đều do cửa hàng ứng dụng xử lý theo quy tắc của họ); và (d) các phần của các Điều khoản này mà cần tồn tại tiếp tục (bao gồm các Mục 6.5, 7, 10, 11, 14–19) tiếp tục được áp dụng.</p>
      <p>7.4 <strong>Khiếu nại.</strong> Nếu bạn cho rằng chúng tôi đã thực hiện sai một hành động cưỡng chế, hãy gửi email đến <strong><a href="mailto:admin@deployku.com">admin@deployku.com</a></strong>. Chúng tôi sẽ xem xét các khiếu nại chính đáng nhưng không bắt buộc phải khôi phục bất kỳ Account, Credits hoặc lợi ích nào.</p>
      <p>7.5 <strong>Đóng tài khoản của chính bạn.</strong> Bạn có thể ngừng sử dụng Service và xóa Account của bạn bất cứ lúc nào trong cài đặt App hoặc bằng cách gửi email đến <strong><a href="mailto:admin@deployku.com">admin@deployku.com</a></strong>. Việc xóa Account của bạn làm mất bất kỳ Credits còn lại nào mà không hoàn tiền (trừ khi pháp luật quy định khác) và <strong>không</strong> tự nó hủy một gói đăng ký tự động gia hạn — hãy hủy gói đó thông qua cửa hàng ứng dụng của bạn. Cách chúng tôi xử lý dữ liệu của bạn khi xóa được nêu trong <a href="privacy.html">Chính sách Quyền riêng tư</a>.</p>

      <h2 id="s8">8. Ghi Âm Cuộc Gọi, Video, Chép Lời và Giám Sát</h2>
      <p>8.1 <strong>Bạn đồng ý với việc ghi âm.</strong> Để bảo vệ tất cả mọi người, <strong>các cuộc gọi thoại trên Service (các Mini-Date và Direct Call) được ghi âm và tự động chép lời thành văn bản.</strong> App thông báo cho bạn điều này trước mỗi cuộc gọi. <strong>Bằng việc bắt đầu hoặc tham gia một cuộc gọi, bạn đồng ý — và xác nhận bạn có quyền đồng ý — rằng cuộc gọi đó được ghi âm, chép lời, phân tích và xem xét vì mục đích an toàn.</strong> Nếu bạn không đồng ý, đừng sử dụng các tính năng gọi.</p>
      <p>8.2 <strong>Chúng tôi làm gì với các bản ghi âm.</strong> Như được giải thích trong <a href="privacy.html">Chính sách Quyền riêng tư</a>: âm thanh thô được dùng để tạo một bản chép lời và được xóa ngay sau đó; bản chép lời (với nhãn người nói tự động và một bản tóm tắt) được lưu giữ và chỉ có sẵn cho những người tham gia cuộc gọi và cho nhân viên được ủy quyền vì các mục đích an toàn, kiểm duyệt, phòng chống gian lận và tuân thủ pháp luật.</p>
      <p>8.3 <strong>An toàn và trải nghiệm.</strong> Chúng tôi có thể xem xét và sử dụng các bản ghi âm, bản chép lời, tin nhắn trò chuyện, video Glimpse và nội dung nhật ký đôi để điều tra các báo cáo, phát hiện và ngăn chặn lạm dụng, thực thi các Điều khoản này, tuân thủ pháp luật, bảo vệ người dùng, và cải thiện trải nghiệm của bạn — tất cả phù hợp với Chính sách Quyền riêng tư.</p>
      <p>8.4 <strong>Nội dung Glimpse và nhật ký.</strong> Các video Glimpse và mục nhật ký được sàng lọc và/hoặc có thể được xem xét vì mục đích an toàn. Các video Glimpse được lưu trữ và phân phối thông qua các liên kết được ký an toàn và chỉ được hiển thị cho các đối tượng được mô tả ở Mục 1.5 và 5.6. Bạn chịu trách nhiệm về những gì bạn ghi và đăng.</p>
      <p>8.5 <strong>Đừng ghi lại những người dùng khác.</strong> Đừng ghi âm, ghi lại, chụp màn hình, phát sóng hoặc sao chép bằng cách khác cuộc gọi, giọng nói, video Glimpse, cuộc trò chuyện, mục nhật ký hoặc hồ sơ của một người dùng khác — bằng bất kỳ phương tiện nào, bao gồm một thiết bị bên ngoài — mà không có sự đồng ý rõ ràng của người dùng đó và của chúng tôi. Làm như vậy là một vi phạm nghiêm trọng đối với các Điều khoản này.</p>

      <h2 id="s9">9. Quy Tắc Cộng Đồng</h2>
      <p>9.1 Liên quan đến Service, bạn đồng ý <strong>không</strong>:</p>
      <ul>
        <li>quấy rối, lăng mạ, theo dõi rình rập, đe dọa, dọa nạt, phỉ báng hoặc làm hại bất kỳ ai, hoặc khuyến khích người khác làm vậy;</li>
        <li>sử dụng ngôn từ thù ghét, hoặc phân biệt đối xử dựa trên chủng tộc, sắc tộc, quốc tịch, tôn giáo, giới tính, bản dạng giới, xu hướng tính dục, khuyết tật, hoặc bất kỳ đặc điểm được bảo vệ nào khác;</li>
        <li>chia sẻ nội dung — trong các cuộc gọi, video Glimpse, ảnh, mục nhật ký hoặc trò chuyện — mang tính khiêu dâm rõ ràng, tục tĩu, đồi trụy, bạo lực hoặc phản cảm theo cách khác, hoặc khiến bất kỳ ai tiếp xúc với nội dung như vậy mà không có sự đồng ý;</li>
        <li>ghi lại hoặc đăng một Glimpse, ảnh hoặc mục nhật ký hiển thị bất kỳ ai khác ngoài chính bạn mà không có sự đồng ý của họ, hoặc thực sự không phải là bạn;</li>
        <li>nói dối về danh tính, độ tuổi, ảnh, video hoặc các mối liên kết của bạn, mạo danh bất kỳ ai, hoặc vận hành một hồ sơ giả, trùng lặp hoặc "câu cá" (catfishing);</li>
        <li>hỏi xin bất kỳ người dùng nào tiền, quà tặng, quyên góp, thông tin tài chính, mật khẩu hoặc mã một lần, hoặc thực hiện bất kỳ trò lừa đảo, lừa tình, mô hình kim tự tháp hoặc chào mời thương mại nào;</li>
        <li>quảng cáo, quảng bá hoặc bán bất cứ thứ gì, hoặc sử dụng Service cho bất kỳ mục đích thương mại nào, mà không có sự đồng ý bằng văn bản của chúng tôi;</li>
        <li>chia sẻ hoặc hỏi xin thông tin nhận dạng hoặc liên hệ trong các cuộc gọi ẩn danh, hoặc vượt qua thiết kế ẩn danh và tiết lộ bằng cách khác;</li>
        <li>lạm dụng các tính năng kết nối — ví dụ bằng cách chia sẻ hoặc thu thập mã bạn bè/ghép đôi để gửi thư rác, hoặc lạm dụng Pledge để quấy rối hoặc lừa dối;</li>
        <li>chia sẻ thông tin riêng tư của ai đó mà không có sự đồng ý của họ ("doxxing"), bao gồm các vị trí trong một nhật ký đôi;</li>
        <li>sử dụng Service nếu bạn dưới 18 tuổi, hoặc tương tác với nó thay mặt cho bất kỳ ai dưới 18 tuổi;</li>
        <li>gửi virus, phần mềm độc hại hoặc bất kỳ mã có hại hoặc gây gián đoạn nào;</li>
        <li>thu thập, dò quét, gặt hái hoặc thu gom dữ liệu về những người dùng khác (bao gồm video Glimpse hoặc hồ sơ), hoặc truy cập Service bằng các phương tiện tự động (bot, kịch bản, trình giả lập) cho bất kỳ mục đích nào;</li>
        <li>thăm dò, quét hoặc kiểm tra tính bảo mật của, hoặc phá vỡ, vượt qua hoặc đánh bại, bất kỳ biện pháp bảo mật, giới hạn tần suất, chống gian lận, kiểm duyệt hoặc đăng nhập nào;</li>
        <li>thiết kế ngược, dịch ngược, tháo rời, sửa đổi hoặc tạo các tác phẩm phái sinh của App hoặc Service, trừ những nơi pháp luật không cho phép hạn chế đó;</li>
        <li>sử dụng Service để xây dựng một sản phẩm cạnh tranh, hoặc sao chép bất kỳ tính năng, chức năng, giao diện hoặc đồ họa nào của nó;</li>
        <li>khai thác lỗi, thao túng các hệ thống ghép đôi, đánh giá, tư cách hoặc phần thưởng, hoặc lạm dụng các chương trình khuyến mãi; hoặc</li>
        <li>sử dụng Service vi phạm bất kỳ luật nào.</li>
      </ul>
      <p>9.2 <strong>Báo cáo.</strong> App cho phép bạn báo cáo và chặn những người dùng khác trước, trong và sau các cuộc gọi, trong cuộc trò chuyện, và trên nội dung Glimpse. Vui lòng báo cáo bất cứ điều gì vi phạm các quy tắc này. Các báo cáo đi qua quy trình kiểm duyệt của chúng tôi, bao gồm sự xem xét của con người. Việc nộp các báo cáo sai sự thật một cách cố ý hoặc với dụng ý xấu tự nó là một vi phạm đối với các Điều khoản này.</p>
      <p>9.3 <strong>Chúng tôi có thể hành động, nhưng không bắt buộc phải theo dõi mọi thứ.</strong> Chúng tôi không hứa sẽ giám sát tất cả Content, nhưng chúng tôi có thể (hoàn toàn theo quyết định của chúng tôi) xem xét, sàng lọc, kiểm duyệt, gỡ bỏ hoặc từ chối bất kỳ Content nào, và thực hiện hành động theo Mục 7, vào bất cứ lúc nào và không cần báo trước.</p>

      <h2 id="s10">10. Content Của Bạn và Giấy Phép Bạn Cấp Cho Chúng Tôi</h2>
      <p>10.1 <strong>Bạn sở hữu Content của bạn.</strong> Bạn giữ bất kỳ quyền sở hữu nào mà bạn có trong User Content của bạn.</p>
      <p>10.2 <strong>Giấy phép bạn cấp cho chúng tôi.</strong> Bằng việc gửi User Content (hồ sơ của bạn, ảnh, video Glimpse, mục nhật ký, giọng nói trong các cuộc gọi, và tin nhắn trò chuyện), bạn cấp cho Deployku một giấy phép toàn cầu, không độc quyền, miễn bản quyền, có thể cấp lại (cho các nhà cung cấp dịch vụ của chúng tôi) và có thể chuyển nhượng để lưu trữ, lưu giữ, sao chép, xử lý, điều chỉnh, chép lời, phân tích, hiển thị và phân phối nó — chỉ để: (a) vận hành, cung cấp, bảo mật và cải thiện Service; (b) hiển thị hồ sơ, video Glimpse, mục nhật ký và tin nhắn của bạn cho người dùng theo đúng thiết kế của Service (ví dụ sau khi tiết lộ, cho đối tượng Glimpse của bạn, hoặc cho một đối tác đã kết nối); (c) xử lý kiểm duyệt, an toàn, phòng chống gian lận và cưỡng chế; và (d) tuân thủ pháp luật. Giấy phép này kéo dài chừng nào chúng tôi còn lưu giữ Content đó theo <a href="privacy.html">Chính sách Quyền riêng tư</a>, và tồn tại sau khi chấm dứt ở mức độ đó.</p>
      <p>10.3 <strong>Dữ liệu ẩn danh và tổng hợp.</strong> Chúng tôi có thể tạo và sử dụng dữ liệu ẩn danh, đã được khử nhận dạng hoặc tổng hợp từ Content và hoạt động của bạn — dữ liệu không còn có thể nhận dạng bạn một cách hợp lý — cho bất kỳ mục đích hợp pháp nào, bao gồm cải thiện việc ghép đôi, an toàn, các tính năng và trải nghiệm tổng thể.</p>
      <p>10.4 <strong>Các cam kết của bạn về Content của bạn.</strong> Bạn xác nhận rằng: (a) bạn có tất cả các quyền cần thiết để gửi User Content của bạn và cấp giấy phép ở trên; (b) User Content của bạn (bao gồm ảnh, video Glimpse và giọng nói của bạn) hiển thị và thuộc về bạn, và không bao gồm bất kỳ người nhận dạng được nào khác mà không có sự đồng ý của họ; và (c) nó không và sẽ không vi phạm hoặc xâm phạm quyền sở hữu trí tuệ, quyền riêng tư, quyền công khai hoặc các quyền khác của bất kỳ ai, hoặc bất kỳ luật nào.</p>
      <p>10.5 <strong>Phản hồi.</strong> Nếu bạn gửi cho chúng tôi các đề xuất hoặc ý tưởng về Service, chúng tôi có thể sử dụng chúng một cách tự do, mãi mãi, không hạn chế hoặc thanh toán cho bạn.</p>

      <h2 id="s11">11. Sở Hữu Trí Tuệ và Nhãn Hiệu</h2>
      <p>11.1 <strong>Chúng tôi sở hữu Service.</strong> Service — App, phần mềm của nó, mã, kiến trúc, cơ sở dữ liệu, thuật toán, các hệ thống ghép đôi và chấm điểm, các avatar và thiết kế biểu tượng được tạo ra, các đầu ra AI do Service cung cấp, giao diện, thiết kế, văn bản, đồ họa, âm thanh và mọi thứ khác (ngoại trừ User Content) — thuộc về hoặc được cấp phép bởi Deployku, và được bảo vệ bởi luật bản quyền, nhãn hiệu, bí mật thương mại và các luật khác. Bất kỳ quyền nào chúng tôi không cấp cho bạn một cách rõ ràng đều được bảo lưu.</p>
      <p>11.2 <strong>Giấy phép sử dụng nó của bạn.</strong> Tuân theo các Điều khoản này, chúng tôi cấp cho bạn một giấy phép cá nhân, có giới hạn, không độc quyền, không thể chuyển nhượng, không thể cấp lại, có thể thu hồi để tải xuống và sử dụng App trên các thiết bị mà bạn sở hữu hoặc kiểm soát, cho mục đích sử dụng cá nhân, phi thương mại của riêng bạn.</p>
      <p>11.3 <strong>Nhãn hiệu, bao gồm cả đơn đăng ký đang chờ xử lý.</strong> "Heqiyou", logo Heqiyou và các Marks khác của chúng tôi là nhãn hiệu của Deployku Pte Ltd. <strong>Một đơn đăng ký nhãn hiệu cho "Heqiyou" hiện đang được Cục Sở hữu Trí tuệ Singapore (IPOS) thẩm định. Việc đơn này vẫn đang chờ xử lý không làm giảm, từ bỏ hay tổn hại bất kỳ quyền nào của Deployku trong các Marks — bao gồm các quyền chưa đăng ký và quyền theo thông luật, các quyền về việc giả mạo nguồn gốc (passing off), bản quyền trong tác phẩm nghệ thuật logo, và các quyền có hiệu lực khi đăng ký (mà nếu được cấp, sẽ áp dụng từ ngày nộp đơn).</strong> Các Điều khoản này không cấp cho bạn quyền nào trong các Marks. Đừng sử dụng, đăng ký, hoặc cố gắng đăng ký bất kỳ Marks nào của chúng tôi, hoặc bất kỳ tên, logo, tên miền, tài khoản mạng xã hội hoặc định danh ứng dụng nào dễ gây nhầm lẫn tương tự, ở bất cứ đâu trên thế giới. Toàn bộ uy tín thương mại từ bất kỳ việc sử dụng các Marks nào đều thuộc về Deployku.</p>
      <p>11.4 <strong>Khiếu nại vi phạm.</strong> Nếu bạn tin rằng Content trên Service vi phạm bản quyền hoặc các quyền khác của bạn, hãy báo cho chúng tôi tại <strong><a href="mailto:admin@deployku.com">admin@deployku.com</a></strong> với đủ chi tiết (tác phẩm, tài liệu vi phạm, chi tiết liên hệ của bạn, và một tuyên bố thiện chí). Chúng tôi sẽ xem xét và hành động đối với các thông báo hợp lệ theo yêu cầu của pháp luật.</p>

      <h2 id="s12">12. Các Tính Năng AI</h2>
      <p>12.1 <strong>Những gì được hỗ trợ bởi AI.</strong> Service bao gồm các tính năng AI: chép lời và tóm tắt tự động các cuộc gọi, một trợ lý lên kế hoạch hẹn hò bằng AI gợi ý các lịch trình từ các thông tin mà bạn và match của bạn cung cấp, một người bạn đồng hành giọng nói bằng AI mà bạn có thể trò chuyện, và kiểm duyệt nội dung tự động. Việc xử lý AI có thể được thực hiện bởi các nhà cung cấp AI bên thứ ba thay mặt cho chúng tôi, như được mô tả trong <a href="privacy.html">Chính sách Quyền riêng tư</a>.</p>
      <p>12.2 <strong>Đừng phụ thuộc vào các đầu ra AI.</strong> Các đầu ra AI (kế hoạch hẹn hò, gợi ý địa điểm, bản chép lời, bản tóm tắt, câu trả lời của người bạn đồng hành, gợi ý độ tương hợp) là <strong>các gợi ý tự động, được cung cấp "nguyên trạng" chỉ để thuận tiện</strong>. Chúng có thể sai, thiếu sót hoặc lỗi thời. Chúng tôi không xác minh các địa điểm, giờ mở cửa, giá cả, chi tiết phương tiện đi lại và những thứ tương tự. Việc kiểm tra các đầu ra AI trước khi phụ thuộc vào chúng, và việc tự lo cho các quyết định và sự an toàn của riêng bạn, là tùy thuộc vào bạn.</p>
      <p>12.3 <strong>Các địa điểm của bên thứ ba.</strong> Chúng tôi không liên kết với, và không chịu trách nhiệm về, bất kỳ địa điểm, doanh nghiệp hoặc nơi chốn nào mà một tính năng AI gợi ý. Bất cứ điều gì giữa bạn và những nơi đó hoàn toàn là giữa bạn và họ.</p>
      <p>12.4 <strong>Người bạn đồng hành giọng nói bằng AI.</strong> Người bạn đồng hành giọng nói bằng AI là một tác nhân tự động, không phải một người thật, và một nhà cung cấp AI xử lý cuộc trò chuyện để tạo ra các câu trả lời. Đừng phụ thuộc vào nó để xin lời khuyên (y tế, pháp lý, tài chính, sức khỏe tâm thần hoặc khác), và đừng coi nó như một sự thay thế cho sự trợ giúp chuyên nghiệp hoặc các mối quan hệ con người.</p>

      <h2 id="s13">13. An Toàn và Việc Giao Tiếp với Những Người Dùng Khác</h2>
      <p>13.1 <strong>Bạn chịu trách nhiệm về các tương tác của mình.</strong> Service giới thiệu mọi người với nhau. <strong>Chúng tôi không thực hiện kiểm tra lý lịch tư pháp hoặc kiểm tra danh tính đầy đủ đối với người dùng</strong>, và bất kỳ kiểm tra nào chúng tôi thực hiện (như số điện thoại, ảnh hoặc tính sống động) là có giới hạn và có thể không phát hiện được thông tin sai sự thật. Chúng tôi không đưa ra lời hứa nào về danh tính, hành vi, ý định, sự tương hợp hoặc sự trung thực của bất kỳ người dùng nào.</p>
      <p>13.2 <strong>Hãy cẩn thận.</strong> Một mình bạn chịu trách nhiệm về cách bạn giao tiếp với những người dùng khác, trực tuyến và đặc biệt là ngoại tuyến. Hãy thực hiện các biện pháp phòng ngừa theo lẽ thường: gặp gỡ nơi công cộng, nói cho ai đó biết bạn sẽ đi đâu, đừng chia sẻ thông tin tài chính hoặc gửi tiền, hãy cẩn thận về việc chia sẻ các vị trí chính xác (bao gồm trong một nhật ký đôi), và đừng chỉ dựa vào các tín hiệu trong ứng dụng. Các mẹo an toàn trong ứng dụng là để thuận tiện và không phải là một sự bảo đảm về an toàn.</p>
      <p>13.3 <strong>Chúng tôi không chịu trách nhiệm về những người dùng khác.</strong> Ở mức tối đa mà pháp luật cho phép, Deployku không chịu trách nhiệm hoặc nghĩa vụ pháp lý về hành vi của bất kỳ người dùng nào, trực tuyến hoặc ngoại tuyến, hoặc về bất kỳ tổn thất, thương tích hoặc thiệt hại nào từ các tương tác giữa những người dùng — bao gồm các cuộc gặp gỡ được thiết lập thông qua Service hoặc trợ lý lên kế hoạch hẹn hò bằng AI của nó.</p>
      <p>13.4 <strong>Trường hợp khẩn cấp.</strong> Service không phải là một dịch vụ khẩn cấp. Nếu bạn nghĩ rằng mình đang gặp nguy hiểm, hãy liên hệ với cảnh sát địa phương hoặc các dịch vụ khẩn cấp ngay lập tức.</p>

      <h2 id="s14">14. Các Dịch Vụ của Bên Thứ Ba, Quảng Cáo và Các Cửa Hàng Ứng Dụng</h2>
      <p>14.1 <strong>Các nhà cung cấp dịch vụ.</strong> Chúng tôi vận hành Service bằng cách sử dụng cơ sở hạ tầng, các dịch vụ liên lạc, lưu trữ, phân phối nội dung, bản đồ, thanh toán, quảng cáo, xác minh, kiểm duyệt và AI từ các bên thứ ba hành động thay mặt cho chúng tôi. Cách họ xử lý dữ liệu cá nhân được nêu trong <a href="privacy.html">Chính sách Quyền riêng tư</a>. Chúng tôi không chịu trách nhiệm về các sự cố ngừng hoạt động, lỗi hoặc hành vi của các nhà cung cấp này nằm ngoài tầm kiểm soát hợp lý của chúng tôi.</p>
      <p>14.2 <strong>Quảng cáo.</strong> Service có thể hiển thị quảng cáo, bao gồm các quảng cáo có thưởng tùy chọn. Quảng cáo đến từ các mạng quảng cáo bên thứ ba; chúng tôi không xác nhận các sản phẩm hoặc dịch vụ được quảng cáo, và bất kỳ giao dịch nào với các nhà quảng cáo hoàn toàn là giữa bạn và họ.</p>
      <p>14.3 <strong>Điều khoản của cửa hàng ứng dụng.</strong> Việc tải xuống và sử dụng App của bạn, và bất kỳ gói đăng ký nào, cũng tuân theo các quy tắc của cửa hàng ứng dụng mà bạn đã nhận nó từ đó. Các Điều khoản này chỉ là giữa bạn và Deployku; đơn vị vận hành cửa hàng ứng dụng không phải là một bên của chúng, không bắt buộc phải cung cấp hỗ trợ cho App, và không chịu trách nhiệm về các khiếu nại liên quan đến nó. Ở những nơi các quy tắc của cửa hàng ứng dụng yêu cầu, đơn vị vận hành đó và các bên liên kết của họ là các bên thụ hưởng thứ ba của các Điều khoản này và có thể thực thi chúng đối với bạn.</p>
      <p>14.4 <strong>Các liên kết và các ứng dụng khác.</strong> Service có thể liên kết đến các trang web hoặc tài nguyên của bên thứ ba (bao gồm bên trong các kế hoạch hẹn hò bằng AI và bản đồ) và có thể cho phép bạn mở các ứng dụng khác — ví dụ một ứng dụng gọi xe được điền sẵn một điểm đến được gợi ý, hoặc một ứng dụng nhắn tin được điền sẵn một lời mời và mã của bạn. Khi bạn rời khỏi Service để sang một ứng dụng hoặc trang web khác, các điều khoản và chính sách quyền riêng tư riêng của bên thứ ba đó được áp dụng. Chúng tôi không chịu trách nhiệm về nội dung, sản phẩm, dịch vụ, giá cả hoặc tính khả dụng của họ.</p>

      <h2 id="s15">15. Tuyên Bố Từ Chối Bảo Đảm</h2>
      <p>15.1 <strong>SERVICE ĐƯỢC CUNG CẤP "NGUYÊN TRẠNG" VÀ "THEO TÌNH TRẠNG SẴN CÓ", VỚI MỌI LỖI VÀ KHÔNG CÓ BẤT KỲ BẢO ĐẢM NÀO.</strong> Ở mức tối đa mà pháp luật cho phép, Deployku từ chối tất cả các bảo đảm và điều kiện, dù là rõ ràng, ngụ ý hay theo luật định — bao gồm bất kỳ bảo đảm ngụ ý nào về khả năng bán được, chất lượng đạt yêu cầu, sự phù hợp cho một mục đích cụ thể, quyền sở hữu, sự hưởng dụng yên ổn, độ chính xác và việc không vi phạm, và bất kỳ bảo đảm nào phát sinh từ cách chúng tôi đã giao dịch hoặc tập quán trong thương mại.</p>
      <p>15.2 Cụ thể, chúng tôi không hứa rằng: (a) Service sẽ không bị gián đoạn, đúng giờ, an toàn, không có lỗi hoặc không có virus hay các thành phần có hại; (b) bất kỳ match, cuộc gọi, tin nhắn, bản chép lời, đầu ra AI, video Glimpse hoặc Content nào khác sẽ chính xác, đáng tin cậy, đầy đủ hoặc có sẵn; (c) các khiếm khuyết sẽ được sửa chữa; hoặc (d) Service sẽ đáp ứng kỳ vọng của bạn hoặc dẫn đến bất kỳ mối quan hệ, buổi hẹn hò hoặc kết quả nào khác.</p>
      <p>15.3 Một số nơi không cho phép loại trừ một số bảo đảm nhất định; tại đó, điều trên áp dụng ở mức tối đa được cho phép, và không có điều gì trong các Điều khoản này loại trừ các quyền không thể bị loại trừ một cách hợp pháp.</p>

      <h2 id="s16">16. Giới Hạn Trách Nhiệm của Chúng Tôi</h2>
      <p>16.1 Ở mức tối đa mà pháp luật cho phép, Deployku cùng các giám đốc, cán bộ, nhân viên, đại lý, bên cấp phép và nhà cung cấp dịch vụ của họ sẽ không chịu trách nhiệm về: (a) bất kỳ thiệt hại gián tiếp, ngẫu nhiên, đặc biệt, hệ quả, mang tính làm gương hoặc trừng phạt nào; (b) lợi nhuận, doanh thu, uy tín thương mại, dữ liệu, cơ hội hoặc khoản tiết kiệm dự kiến bị mất; (c) bất kỳ thiệt hại nào từ việc bạn sử dụng (hoặc không thể sử dụng) Service; (d) hành vi hoặc Content của bất kỳ người dùng hoặc bên thứ ba nào, bao gồm hành vi có hại, phản cảm hoặc bất hợp pháp, và bao gồm các cuộc gặp gỡ phát sinh từ Service; hoặc (e) việc truy cập hoặc thay đổi trái phép dữ liệu của bạn — bất kể khiếu nại dựa trên bảo đảm, hợp đồng, hành vi vi phạm dân sự (bao gồm sơ suất), luật định hay bất cứ điều gì khác, và ngay cả khi chúng tôi đã được cảnh báo rằng những thiệt hại như vậy là có thể.</p>
      <p>16.2 Ở mức tối đa mà pháp luật cho phép, <strong>tổng trách nhiệm của chúng tôi đối với tất cả các khiếu nại liên quan đến Service hoặc các Điều khoản này sẽ không vượt quá giá trị lớn hơn của (a) số tiền bạn đã trả cho chúng tôi trong 12 tháng trước sự kiện làm phát sinh khiếu nại, và (b) một trăm đô la Singapore (SGD 100).</strong></p>
      <p>16.3 Không có điều gì trong các Điều khoản này loại trừ hoặc giới hạn trách nhiệm về tử vong hoặc thương tích cá nhân do sơ suất gây ra, về gian lận hoặc khai man gian lận, hoặc về bất cứ điều gì không thể bị loại trừ hoặc giới hạn theo pháp luật. Các giới hạn trong Mục này chỉ áp dụng ở mức pháp luật cho phép.</p>
      <p>16.4 Bạn đồng ý rằng các Mục 15 và 16 là một cách công bằng để chia sẻ rủi ro giữa chúng ta, và là một phần cơ bản của thỏa thuận của chúng ta — và rằng chúng tôi không thể cung cấp Service theo các điều khoản này mà không có chúng.</p>

      <h2 id="s17">17. Bồi Thường</h2>
      <p>Ở mức tối đa mà pháp luật cho phép, bạn đồng ý bảo vệ, bồi thường và giữ cho Deployku cùng các giám đốc, cán bộ, nhân viên, đại lý và nhà cung cấp dịch vụ của họ không bị tổn hại khỏi bất kỳ khiếu nại, yêu cầu, hành động, tổn thất, trách nhiệm, thiệt hại, chi phí và phí tổn nào (bao gồm phí pháp lý hợp lý) phát sinh từ: (a) User Content của bạn (bao gồm video Glimpse và mục nhật ký); (b) việc bạn sử dụng hoặc sử dụng sai Service; (c) việc bạn vi phạm các Điều khoản này hoặc bất kỳ luật nào; (d) các tương tác của bạn với những người dùng khác, trực tuyến hoặc ngoại tuyến; hoặc (e) việc bạn vi phạm các quyền của bất kỳ ai. Chúng tôi có thể, với chi phí của bạn, tiếp quản việc bào chữa và kiểm soát độc quyền đối với bất kỳ vấn đề nào mà lẽ ra bạn phải bồi thường, và bạn đồng ý hợp tác.</p>

      <h2 id="s18">18. Luật Điều Chỉnh và Tranh Chấp</h2>
      <p>18.1 <strong>Luật điều chỉnh.</strong> Các Điều khoản này, và bất kỳ tranh chấp nào liên quan đến chúng hoặc Service (dù theo hợp đồng hay không), được điều chỉnh bởi luật pháp Singapore, bỏ qua các quy tắc về xung đột luật.</p>
      <p>18.2 <strong>Hãy trao đổi với chúng tôi trước.</strong> Trước khi bắt đầu thủ tục tố tụng chính thức, hãy gửi email đến <strong><a href="mailto:admin@deployku.com">admin@deployku.com</a></strong> mô tả tranh chấp và thiện chí cố gắng giải quyết nó với chúng tôi trong ít nhất 30 ngày.</p>
      <p>18.3 <strong>Tòa án.</strong> Tuân theo Mục 18.2, các tòa án của Singapore có thẩm quyền tài phán độc quyền đối với bất kỳ tranh chấp nào liên quan đến các Điều khoản này hoặc Service, và mỗi bên trong chúng ta tuân theo các tòa án đó. Không có điều gì ở đây ngăn cản bất kỳ ai trong chúng ta tìm kiếm biện pháp ngăn chặn khẩn cấp tại bất kỳ tòa án có thẩm quyền nào, hoặc giới hạn bất kỳ quyền tiêu dùng bắt buộc nào mà bạn có để khởi kiện tại nơi bạn sinh sống.</p>
      <p>18.4 <strong>Không kiện tập thể.</strong> Ở mức pháp luật cho phép, bạn phải đưa các tranh chấp một cách cá nhân, không phải với tư cách nguyên đơn hay thành viên nhóm trong bất kỳ thủ tục tố tụng tập thể, gộp chung hoặc đại diện nào.</p>
      <p>18.5 <strong>Giới hạn một năm.</strong> Ở mức pháp luật cho phép, bất kỳ khiếu nại nào liên quan đến Service phải được khởi xướng trong vòng một (1) năm sau khi nó phát sinh; sau thời gian đó nó bị vĩnh viễn ngăn cấm.</p>

      <h2 id="s19">19. Quy Định Chung</h2>
      <p>19.1 <strong>Các thay đổi đối với các Điều khoản này.</strong> Chúng tôi có thể cập nhật các Điều khoản này. Nếu các thay đổi là trọng yếu, chúng tôi sẽ thông báo cho bạn qua App hoặc một cách hợp lý khác, và các Điều khoản được cập nhật sẽ hiển thị một ngày hiệu lực mới. Việc sử dụng Service sau ngày đó có nghĩa là bạn chấp nhận các Điều khoản mới. Nếu bạn không đồng ý, hãy ngừng sử dụng Service và, nếu muốn, xóa Account của bạn.</p>
      <p>19.2 <strong>Toàn bộ thỏa thuận.</strong> Các Điều khoản này, cùng với <a href="privacy.html">Chính sách Quyền riêng tư</a> và bất kỳ điều khoản bổ sung nào được hiển thị cho các tính năng hoặc giao dịch mua cụ thể, là toàn bộ thỏa thuận giữa bạn và Deployku về Service, và thay thế bất kỳ thỏa thuận trước đó nào về chủ đề này.</p>
      <p>19.3 <strong>Tính tách biệt.</strong> Nếu bất kỳ phần nào của các Điều khoản này bị xác định là vô hiệu hoặc không thể thực thi, phần đó được áp dụng ở mức tối đa có thể và phần còn lại vẫn giữ nguyên hiệu lực.</p>
      <p>19.4 <strong>Không từ bỏ.</strong> Nếu chúng tôi không thực thi một quyền hoặc quy tắc, đó không phải là sự từ bỏ nó. Bất kỳ sự từ bỏ nào cũng phải bằng văn bản và được chúng tôi ký.</p>
      <p>19.5 <strong>Chuyển nhượng.</strong> Bạn không thể chuyển nhượng hoặc chuyển giao các Điều khoản này hoặc Account của bạn. Chúng tôi có thể chuyển nhượng hoặc chuyển giao chúng (toàn bộ hoặc một phần) một cách tự do, bao gồm trong một vụ sáp nhập, mua lại, tái tổ chức hoặc bán tài sản.</p>
      <p>19.6 <strong>Các sự kiện ngoài tầm kiểm soát của chúng tôi.</strong> Chúng tôi không chịu trách nhiệm về bất kỳ sự chậm trễ hoặc thất bại nào do những điều nằm ngoài tầm kiểm soát hợp lý của chúng tôi, bao gồm thiên tai, dịch bệnh, chiến tranh, khủng bố, bất ổn dân sự, tranh chấp lao động, hành động của chính phủ, sự cố tiện ích hoặc viễn thông, hoặc sự cố của các nhà cung cấp bên thứ ba.</p>
      <p>19.7 <strong>Không có quan hệ đối tác.</strong> Các Điều khoản này không tạo ra bất kỳ quan hệ đối tác, liên doanh, lao động, ủy thác hoặc đại lý nào giữa bạn và Deployku.</p>
      <p>19.8 <strong>Tiếp tục hiệu lực.</strong> Các phần của các Điều khoản này mà theo bản chất của chúng cần tiếp tục sau khi chấm dứt sẽ tiếp tục có hiệu lực, bao gồm các Mục 6.5, 7, 10, 11, 14–19.</p>
      <p>19.9 <strong>Ngôn ngữ.</strong> Các Điều khoản này được viết bằng tiếng Anh. Bất kỳ bản dịch nào chỉ để thuận tiện; nếu có mâu thuẫn, bản tiếng Anh sẽ được ưu tiên, trừ những nơi pháp luật quy định khác.</p>
      <p>19.10 <strong>Liên lạc điện tử.</strong> Bạn đồng ý nhận các liên lạc từ chúng tôi bằng phương thức điện tử (thông báo trong ứng dụng, thông báo đẩy, SMS đến số đã đăng ký của bạn, hoặc email ở nơi được cung cấp), và rằng những liên lạc này đáp ứng bất kỳ yêu cầu pháp lý nào về liên lạc bằng văn bản.</p>

      <h2 id="s20">20. Liên Hệ</h2>
      <p><strong>Deployku Pte Ltd</strong><br />
      Email: <strong><a href="mailto:admin@deployku.com">admin@deployku.com</a></strong></p>
      <p>Để được hỗ trợ, khiếu nại, gửi thông báo pháp lý và khiếu nại vi phạm, hãy sử dụng email ở trên và bao gồm đủ chi tiết để chúng tôi tìm thấy Account của bạn và xử lý yêu cầu của bạn.</p>

      <p class="doc-note">Bằng việc sử dụng Heqiyou, bạn xác nhận rằng bạn đã đọc, hiểu và đồng ý với các Điều khoản và Điều kiện này cùng <a href="privacy.html">Chính sách Quyền riêng tư</a> kèm theo.</p>

    `
};
