window.DK_TRANSLATIONS = window.DK_TRANSLATIONS || {};
window.DK_TRANSLATIONS.id = {
  _lang: "id",
  _title: "Syarat dan Ketentuan — Heqiyou · Deployku",
  "eyebrow": "Hukum · Heqiyou",
  "h1": "Syarat dan Ketentuan",
  "meta": "<span>Tanggal Berlaku: 28 June 2026</span><span>Versi 1.3</span><span>Deployku Pte Ltd · Singapura</span>",
  "intro": `Syarat dan Ketentuan ini (selanjutnya disebut "<strong>Ketentuan</strong>") merupakan perjanjian antara Anda dan <strong>Deployku Pte Ltd</strong>, sebuah perusahaan yang terdaftar di Singapura ("<strong>Deployku</strong>", "<strong>kami</strong>", atau "<strong>milik kami</strong>"). Ketentuan ini mengatur penggunaan aplikasi Heqiyou oleh Anda beserta segala isinya — seluruh fitur, konten, serta situs web dan layanan terkait (secara bersama-sama disebut "<strong>Service</strong>" (Layanan) atau "<strong>App</strong>" (Aplikasi)).`,
  "nav.product": "Heqiyou",
  "nav.privacy": "Privasi",
  "nav.terms": "Ketentuan",
  "nav.cta": "Hubungi kami",
  "foot.tagline": `Sebuah studio Singapura yang membangun produk-produk yang menggerakkan Asia Tenggara.`,
  "foot.company": "Perusahaan",
  "foot.whatwedo": "Apa yang kami lakukan",
  "foot.approach": "Pendekatan",
  "foot.about": "Tentang",
  "foot.careers": "Karier",
  "foot.products": "Produk",
  "foot.heqiyou": "Heqiyou",
  "foot.legal": "Hukum",
  "foot.privacyLink": "Kebijakan Privasi",
  "foot.termsLink": "Syarat &amp; Ketentuan",
  "foot.contact": "Kontak",
  "foot.email": "Email",
  "foot.getintouch": "Hubungi kami",
  "foot.copyright": "© 2026 Deployku Pte Ltd. Hak cipta dilindungi undang-undang.",
  "foot.built": "Dibuat di Singapura · untuk Asia Tenggara",
  "body": `

      <p><strong>Mohon baca Ketentuan ini. Dengan membuat akun atau menggunakan Service, Anda menyetujui Ketentuan ini dan <a href="privacy.html">Kebijakan Privasi</a> kami. Jika Anda tidak setuju, jangan gunakan Service.</strong></p>

      <div class="notice-card">
        <p><strong>Hal-hal penting yang perlu diketahui sejak awal:</strong></p>
        <ul>
          <li><strong>Anda harus berusia 18 tahun atau lebih untuk menggunakan Service.</strong></li>
          <li><strong>Panggilan suara direkam dan ditranskripsikan demi keamanan</strong> (lihat Bagian 8 dan <a href="privacy.html">Kebijakan Privasi</a>). Melakukan atau bergabung dalam panggilan berarti Anda menyetujui hal ini. Jika Anda tidak menyetujuinya, jangan gunakan fitur panggilan.</li>
          <li><strong>"Glimpse" memungkinkan Anda memposting video pendek tentang diri Anda.</strong> Dalam tampilan penemuan anonim, nama dan profil Anda tetap tersembunyi, tetapi <strong>video tersebut tetap menampilkan wajah dan penampilan Anda</strong>. Dengan mempostingnya, Anda setuju bahwa video tersebut dapat disaring dan ditampilkan kepada audiens yang Anda pilih.</li>
          <li><strong>Credits bukanlah uang. Credits tidak dapat dikembalikan, dan Anda dapat kehilangannya jika melanggar Ketentuan ini</strong> (lihat Bagian 7).</li>
          <li><strong>"Premium" adalah langganan yang diperpanjang dan menagih Anda secara otomatis hingga Anda membatalkannya</strong> (lihat Bagian 6.9).</li>
          <li><strong>Ketentuan ini membatasi tanggung jawab hukum kami kepada Anda dan mencakup ganti rugi yang berpihak pada kami</strong> (lihat Bagian 15–17).</li>
        </ul>
      </div>

      <h2 id="s1">1. Tentang Service</h2>
      <p>1.1 Heqiyou adalah aplikasi kencan dan sosial yang mengutamakan suara. Alih-alih menggeser-geser foto, Anda bertemu orang melalui panggilan suara anonim yang singkat ("<strong>Mini-Date</strong>" (Kencan Singkat)). Nama dan foto tetap tersembunyi selama panggilan. Hanya jika <strong>kalian berdua</strong> memilih untuk melanjutkan setelahnya, profil kalian akan diungkapkan satu sama lain dan obrolan pribadi pun terbuka.</p>
      <p>1.2 Service dapat mencakup: pendaftaran melalui nomor telepon atau pihak ketiga seperti Apple atau Google; panggilan suara anonim; pencocokan berbasis antrean; petunjuk kecocokan; obrolan setelah terjadi pencocokan; panggilan langsung (non-anonim) antara pengguna yang telah cocok; asisten perencanaan kencan berbasis AI (yang dapat menyarankan area awal dari lokasi perangkat Anda dan memungkinkan Anda membuka aplikasi seperti ride-hailing dengan tujuan yang telah terisi otomatis); pendamping suara AI; video pendek dengan teks opsional dan ekspor rekap harian ("<strong>Glimpse</strong>"); koneksi pertemanan dan fitur komitmen eksklusif ("<strong>Pledge</strong>" (Ikrar)); "buku harian pasangan" bersama tentang tempat-tempat ("<strong>Places</strong>" (Tempat)); pembuatan profil dan foto; pembelian Credits; langganan <strong>Premium</strong>; dan iklan yang dapat Anda tonton untuk mendapatkan imbalan.</p>
      <p>1.3 Service hanya tersedia di wilayah yang kami pilih ("<strong>Supported Regions</strong>" (Wilayah yang Didukung)). Pencocokan dan penemuan Glimpse biasanya terbatas pada orang-orang di Supported Region yang sama. Kami dapat menambah, menghapus, atau mengubah Supported Regions kapan saja, tanpa pemberitahuan.</p>
      <p>1.4 Kami terus meningkatkan Service. Kami dapat menambah, mengubah, menjeda, atau menghapus fitur (termasuk fitur yang masih dalam pengembangan, seperti pemeriksaan identitas yang lebih ketat atau opsi pembayaran baru), atau menetapkan batasan pada fitur, kapan saja dan atas kebijaksanaan kami. Jika suatu perubahan secara serius dan negatif memengaruhi fitur berbayar, kami akan berusaha memberi Anda pemberitahuan terlebih dahulu.</p>
      <p>1.5 <strong>Glimpse.</strong> Glimpse memungkinkan Anda merekam video pendek (beberapa detik) tentang diri Anda, secara opsional menambahkan teks singkat, dan mempostingnya ke "jendela" waktu berulang untuk audiens yang Anda pilih: <strong>Hopeful</strong> (penemuan anonim), <strong>Matched</strong>, <strong>Friends</strong>, atau <strong>Pledged</strong>. Video dan teks yang dikirim ke audiens Hopeful atau Matched diperiksa oleh moderasi otomatis sebelum ditampilkan, dan ditampilkan dengan glif abstrak serta skor kecocokan — bukan nama atau profil Anda (meskipun video memang menampilkan penampilan Anda). Video yang dikirim ke Friends atau pasangan Pledged ditampilkan dengan nama dan foto Anda kepada orang-orang tersebut. Glimpse juga dapat menggabungkan klip-klip dalam sehari (milik Anda dan milik teman/pasangan Anda) menjadi sebuah video rekap pendek yang dapat Anda simpan atau bagikan. Memposting ke Hopeful atau Matched, dan mengekspor rekap, mungkin memerlukan Credits atau termasuk dalam Premium; postingan Friends/Pledged gratis (lihat Bagian 6).</p>
      <p>1.6 <strong>Connections, Friends dan Pledge.</strong> Anda dapat membentuk koneksi berkelanjutan dengan pengguna lain: sebuah <strong>Match</strong> (setelah Mini-Date yang saling cocok), seorang <strong>Friend</strong> (ditambahkan dengan kode teman pribadi), dan sebuah <strong>Pledge</strong> (komitmen eksklusif yang saling menguntungkan antara pengguna yang telah cocok, dibentuk dengan kode pencocokan). Saat Anda berstatus pledged, beberapa fitur kencan buta dan pencocokan dimatikan, dan beberapa fitur hanya berfungsi dengan pasangan pledged Anda. Anda dapat mengakhiri koneksi apa pun kapan saja.</p>
      <p>1.7 <strong>Places (buku harian pasangan).</strong> Pengguna yang terhubung (matched atau pledged) dapat menyimpan buku harian bersama tentang tempat-tempat yang telah mereka kunjungi bersama — termasuk nama dan lokasi tempat, tanggal, foto, teks, dan catatan yang ditambahkan oleh salah satu pihak. Kedua anggota koneksi dapat melihat buku harian tersebut. Memposting suatu tempat mungkin memerlukan Credits atau termasuk dalam Premium (lihat Bagian 6).</p>
      <p>1.8 <strong>Pendamping suara AI.</strong> Service dapat memungkinkan Anda melakukan obrolan suara langsung dengan pendamping AI otomatis (bukan orang lain). Fitur ini dibatasi waktu dan mungkin memerlukan Credits.</p>
      <p>1.9 <strong>Mode Ambassador.</strong> Kami dapat mengundang sebagian pengguna ke mode "ambassador" opsional yang membantu menumbuhkan antrean pencocokan. Jika Anda mengaktifkannya, sebagian panggilan Anda mungkin ditandai sehingga dikecualikan dari metrik tertentu, dan panggilan yang Anda mulai dalam mode ini mungkin tidak dikenakan Credits. Kami dapat memberikan, mengubah, atau menghapus kelayakan ambassador atas kebijaksanaan kami.</p>

      <h2 id="s2">2. Definisi</h2>
      <p>Dalam Ketentuan ini:</p>
      <ul>
        <li>"<strong>Account</strong>" (Akun) berarti akun yang Anda daftarkan dengan Service.</li>
        <li>"<strong>Content</strong>" (Konten) berarti data, teks, audio, suara, video, gambar, foto, profil, pesan, transkrip, peringkat, laporan, entri tempat, atau materi lain apa pun di Service.</li>
        <li>"<strong>User Content</strong>" (Konten Pengguna) berarti Content yang Anda sediakan — profil Anda, foto, <strong>video Glimpse</strong>, <strong>entri buku harian pasangan (tempat, foto, teks, dan catatan)</strong>, suara Anda selama panggilan, dan pesan obrolan.</li>
        <li>"<strong>Credits</strong>" berarti unit dalam aplikasi yang digunakan untuk membayar fitur tertentu (lihat Bagian 6).</li>
        <li>"<strong>Premium</strong>" berarti langganan berbayar yang diperpanjang otomatis yang membuka fitur tertentu dan/atau menghilangkan biaya Credit tertentu (lihat Bagian 6.9).</li>
        <li>"<strong>Mini-Date</strong>" berarti panggilan suara anonim yang dibatasi waktu antara dua pengguna yang diatur oleh sistem pencocokan kami.</li>
        <li>"<strong>Direct Call</strong>" (Panggilan Langsung) berarti panggilan suara non-anonim antara pengguna yang telah cocok.</li>
        <li>"<strong>Match</strong>" berarti keadaan di mana kedua pengguna memilih untuk melanjutkan setelah Mini-Date, sehingga profil mereka diungkapkan satu sama lain.</li>
        <li>"<strong>Glimpse</strong>" atau "<strong>Glimpse Clip</strong>" berarti video pendek tentang diri Anda yang Anda posting.</li>
        <li>"<strong>Connection</strong>" (Koneksi) berarti tautan berkelanjutan antara dua pengguna — sebuah Match, seorang Friend, atau sebuah Pledge.</li>
        <li>"<strong>Friend</strong>" berarti koneksi non-romantis yang ditambahkan melalui kode teman.</li>
        <li>"<strong>Pledge</strong>" berarti komitmen eksklusif yang saling menguntungkan antara dua pengguna yang telah cocok.</li>
        <li>"<strong>Places</strong>" atau "<strong>Couple Diary</strong>" (Buku Harian Pasangan) berarti buku harian bersama tempat sebuah Connection mencatat tempat, foto, teks, dan catatan.</li>
        <li>"<strong>Marks</strong>" berarti nama "Heqiyou", logo, merek kata, serta seluruh merek dan desain terkait.</li>
        <li>"<strong>Virtual Items</strong>" (Barang Virtual) berarti Credits, manfaat Premium, dan barang atau fitur virtual lainnya di Service.</li>
      </ul>

      <h2 id="s3">3. Siapa yang Dapat Menggunakan Service</h2>
      <p>3.1 <strong>Anda harus berusia 18+.</strong> Anda harus berusia minimal 18 tahun untuk membuat Account atau menggunakan Service, dan Anda mengonfirmasi bahwa Anda memenuhi syarat ini. Kami dapat menutup Account mana pun yang secara wajar kami yakini milik seseorang yang berusia di bawah 18 tahun, tanpa pengembalian dana, dan kami dapat meminta bukti usia kapan saja.</p>
      <p>3.2 <strong>Anda diperbolehkan untuk menyetujui, dan Anda memiliki catatan bersih.</strong> Anda mengonfirmasi bahwa: (a) Anda secara hukum dapat mengadakan kontrak ini; (b) tidak ada hukum di tempat tinggal Anda yang melarang Anda menggunakan Service; (c) Anda tidak pernah dihukum atas, dan tidak sedang menghadapi tuntutan atas, kejahatan serius, pelanggaran seksual, atau kejahatan apa pun yang melibatkan kekerasan atau ancaman kekerasan; dan (d) Anda tidak diwajibkan untuk mendaftar sebagai pelaku kejahatan seksual di mana pun.</p>
      <p>3.3 <strong>Di mana Anda dapat menggunakannya.</strong> Service hanya untuk digunakan di Supported Regions. Jangan gunakan — atau mencoba menghindari batasan regional (misalnya dengan VPN, lokasi palsu, atau detail pendaftaran palsu) — dari luar Supported Region.</p>
      <p>3.4 <strong>Satu akun untuk masing-masing.</strong> Anda hanya boleh memiliki satu Account, untuk penggunaan pribadi dan non-komersial Anda sendiri. Jangan membuat atau menjalankan Account untuk orang lain, organisasi, atau bot.</p>
      <p>3.5 <strong>Tidak ada kembali setelah pemblokiran.</strong> Jika kami pernah menangguhkan, memblokir, atau menghapus Anda sebelumnya, jangan membuat Account baru kecuali kami memberi Anda izin tertulis.</p>

      <h2 id="s4">4. Account Anda</h2>
      <p>4.1 <strong>Pendaftaran.</strong> Untuk menggunakan Service, Anda mendaftar dengan nomor ponsel valid yang dapat menerima kode satu kali, atau dengan masuk melalui penyedia yang didukung seperti Apple atau Google. Nomor telepon terverifikasi tetap menjadi identitas utama Anda untuk beberapa fitur. Anda akan melalui proses orientasi — memberikan nama atau nama tampilan, tanggal lahir, jenis kelamin, kota, dan beberapa preferensi. Anda juga dapat menambahkan alamat email dan foto profil.</p>
      <p>4.2 <strong>Jaga keakuratannya.</strong> Berikan kepada kami informasi yang benar, terkini, dan lengkap, termasuk tanggal lahir Anda yang sebenarnya, serta jaga agar tetap diperbarui. Berbohong tentang usia, identitas, atau detail pendaftaran lainnya merupakan pelanggaran serius terhadap Ketentuan ini.</p>
      <p>4.3 <strong>Jaga keamanannya.</strong> Anda bertanggung jawab atas segala hal yang terjadi pada Account Anda dan atas perlindungan perangkat serta nomor telepon Anda. Beri tahu kami segera di <strong><a href="mailto:admin@deployku.com">admin@deployku.com</a></strong> jika Anda merasa seseorang telah mengakses Account Anda tanpa izin.</p>
      <p>4.4 <strong>Verifikasi.</strong> Kami dapat meminta Anda untuk memverifikasi identitas, usia, telepon, foto, atau "liveness" Anda (termasuk melalui penyedia verifikasi luar) sebelum atau selama Anda menggunakan Service, atau untuk membuka fitur tertentu (seperti menerima panggilan). Jika Anda tidak menyelesaikan pemeriksaan yang diperlukan, akses Anda mungkin dibatasi atau ditangguhkan.</p>
      <p>4.5 <strong>Pemeriksaan foto dan video.</strong> Foto dan video Glimpse yang Anda unggah dapat diperiksa oleh sistem otomatis dan/atau orang sebelum ditampilkan. Kami dapat menolak, menghapus, atau menolak menampilkan foto atau video apa pun atas kebijaksanaan kami — misalnya jika menampilkan ketelanjangan, senjata, narkoba, atau materi yang menyinggung, atau tidak menampilkan diri Anda.</p>
      <p>4.6 <strong>Izin perangkat.</strong> Beberapa fitur memerlukan izin perangkat — misalnya mikrofon (panggilan dan pendamping AI), kamera (Glimpse dan foto), pustaka foto (unggahan), dan secara opsional lokasi (untuk menyarankan area perencanaan kencan, membantu Anda menandai tempat di sekitar, atau memusatkan peta). Kami hanya membaca lokasi Anda saat Anda menggunakan fitur semacam itu; kami tidak melacaknya di latar belakang. Anda dapat mengelola izin di pengaturan perangkat Anda; mematikan salah satunya dapat menonaktifkan fitur pencocokan.</p>

      <h2 id="s5">5. Pencocokan, Kualitas, dan Keadilan</h2>
      <p>5.1 <strong>Cara kerja pencocokan.</strong> Sistem kami mencocokkan pengguna berdasarkan hal-hal yang dapat mencakup preferensi Anda, seberapa lengkap profil Anda, petunjuk kecocokan dari jawaban orientasi Anda, wilayah Anda, berapa lama Anda telah menunggu, serta skor kualitas, reputasi, dan kecocokan internal. Pencocokan bersifat algoritmik dan atas kebijaksanaan kami, dan <strong>kami tidak menjamin pencocokan tertentu, jumlah pencocokan, frekuensi panggilan, atau hasil apa pun — baik romantis maupun lainnya.</strong></p>
      <p>5.2 <strong>Skor internal.</strong> Untuk menjaga agar segala sesuatunya tetap aman dan seimbang, kami menyimpan metrik internal yang bersifat pribadi untuk Account — seperti skor reputasi (dipengaruhi oleh peringkat pasca-panggilan dan laporan) dan skor kualitas pencocokan (dipengaruhi oleh hasil panggilan). Kami menggunakannya untuk pencocokan, kelayakan, pembatasan laju, dan keamanan. Skor tersebut bukan penilaian terhadap Anda sebagai pribadi, tidak ditampilkan kepada pengguna lain, dan bukan janji dari kami.</p>
      <p>5.3 <strong>Kelayakan dan batasan.</strong> Beberapa fitur (seperti bergabung dengan antrean penerima) mungkin memerlukan hal-hal seperti nomor telepon terverifikasi, profil lengkap, foto atau avatar sistem yang disetujui, status baik, verifikasi yang telah diselesaikan, dan tetap berada dalam batasan penggunaan (misalnya batas bulanan untuk panggilan yang diterima, atau batas harian untuk tindakan tertentu). Kami dapat mengubah persyaratan dan batasan ini kapan saja.</p>
      <p>5.4 <strong>Tetap anonim sebelum pengungkapan.</strong> Selama Mini-Date, profil ditampilkan sebagai avatar abstrak. Jangan mencoba mengalahkan anonimitas — misalnya dengan memberikan atau menanyakan nama asli, foto, akun media sosial, nomor telepon, atau detail kontak atau identitas lainnya selama Mini-Date.</p>
      <p>5.5 <strong>Pengungkapan timbal balik.</strong> Profil dan obrolan hanya terbuka jika kedua orang memilih untuk melanjutkan setelah Mini-Date. Keputusan untuk tidak melanjutkan bersifat final untuk panggilan tersebut, dan kami tidak mengungkapkannya dengan cara yang dimaksudkan untuk mempermalukan siapa pun.</p>
      <p>5.6 <strong>Penemuan Glimpse.</strong> Saat Anda memposting Glimpse, Anda memahami bahwa: (a) video dan teks yang dikirim ke <strong>Hopeful</strong> atau <strong>Matched</strong> diperiksa terlebih dahulu oleh moderasi otomatis dan dapat ditolak; (b) di <strong>Hopeful</strong>, video Anda ditampilkan kepada kelompok pengguna yang memenuhi syarat yang diperingkat berdasarkan kecocokan di wilayah Anda untuk jendela tersebut — nama dan profil Anda disembunyikan, tetapi <strong>video menampilkan penampilan Anda</strong>; (c) di <strong>Matched</strong>, <strong>Friends</strong>, dan <strong>Pledged</strong>, video Anda ditampilkan dengan nama dan foto Anda kepada orang-orang yang telah terhubung dengan Anda; (d) rekap harian yang Anda buat dapat menggabungkan klip Anda dengan klip yang dibagikan oleh teman/pasangan Anda; dan (e) Anda tidak boleh memposting Glimpse yang menampilkan siapa pun selain diri Anda tanpa persetujuan mereka, atau yang melanggar Bagian 9.</p>

      <h2 id="s6">6. Credits, Pembelian, Langganan, dan Penagihan</h2>
      <p>6.1 <strong>Apa itu Credits.</strong> Credits adalah lisensi yang terbatas, pribadi, dan tidak dapat dipindahtangankan untuk menggunakan fitur tertentu — dan kami dapat mencabutnya. <strong>Credits bukanlah uang. Credits tidak memiliki nilai tunai, tidak menghasilkan bunga, dan tidak dapat ditukarkan, dipertukarkan, atau dicairkan menjadi apa pun yang bernilai di luar Service.</strong> Anda tidak dapat menjual, menukar, menghadiahkan, memindahkan, atau menggabungkan Credits.</p>
      <p>6.2 <strong>Cara Anda mendapatkan Credits.</strong> Anda dapat memperoleh Credits dengan: (a) membeli paket Credit melalui pembelian dalam aplikasi pada harga yang ditampilkan saat Anda membeli; (b) hibah promosi atau gratis (seperti bonus pendaftaran), atas kebijaksanaan kami; (c) menonton iklan berimbalan di mana ditawarkan, dalam batas yang kami tetapkan; dan (d) metode lain apa pun yang kami tambahkan. Kami dapat mengubah harga Credit, ukuran paket, aturan perolehan, biaya fitur, dan batasan kapan saja; perubahan hanya berlaku ke depan dan tidak memengaruhi Credits yang sudah ada dalam saldo Anda.</p>
      <p>6.3 <strong>Bagaimana Credits dibelanjakan.</strong> Fitur yang menggunakan Credits — seperti memulai Mini-Dates, memulai Direct Calls, membuat rencana kencan AI, menggunakan pendamping suara AI, memposting Glimpse ke audiens berbayar (Hopeful atau Matched), mengekspor rekap Glimpse, dan memposting tempat ke buku harian pasangan — dikenakan biaya sebesar yang ditampilkan di App saat Anda menggunakannya. Beberapa di antaranya mungkin gratis dengan langganan Premium yang aktif, dan beberapa audiens Glimpse (Friends dan Pledged) selalu gratis. Untuk panggilan berdurasi, Credits dapat ditahan saat panggilan dimulai dan diselesaikan berdasarkan berapa lama Anda benar-benar terhubung. Jika panggilan berakhir lebih cepat daripada yang dipesan, Anda mungkin dikenakan biaya secara proporsional, dan jika panggilan gagal terhubung karena kesalahan di pihak kami, kami umumnya akan melepaskan atau mengembalikan Credits yang ditahan.</p>
      <p>6.4 <strong>Pembayaran dan aturan toko aplikasi.</strong> Pembelian dalam aplikasi dan langganan ditangani oleh toko aplikasi tempat Anda mengunduh dan/atau penyedia pembayaran kami, dan juga tunduk pada ketentuan mereka. Kami tidak menyimpan detail kartu lengkap Anda. Kami dapat menambahkan metode pembayaran lain di kemudian hari, dengan ketentuannya sendiri yang ditampilkan saat pembelian.</p>
      <p>6.5 <strong>Tidak ada pengembalian dana.</strong> <strong>Kecuali jika hukum atau aturan toko aplikasi sendiri mensyaratkannya, semua pembelian Credits dan langganan bersifat final dan tidak dapat dikembalikan</strong> — termasuk Credits yang tidak terpakai, bagian langganan yang tidak terpakai, dan kasus di mana akun Anda ditutup, ditangguhkan, atau diakhiri, atau Service dihentikan. Jika kami memilih untuk memberi Anda pengembalian dana atau kredit sekali, itu tidak berarti kami akan melakukannya lagi.</p>
      <p>6.6 <strong>Kedaluwarsa.</strong> Credits saat ini tidak kedaluwarsa, tetapi kami dapat menambahkan aturan kedaluwarsa atau ketidakaktifan yang wajar untuk Credits gratis/promosi, dan — dengan pemberitahuan terlebih dahulu yang wajar — untuk Credits yang dibeli, di mana hukum mengizinkannya.</p>
      <p>6.7 <strong>Jangan curang terhadap sistem.</strong> Jangan: (a) memperoleh Credits, manfaat Premium, atau Virtual Items lainnya melalui penipuan, bug, bot, atau penyalahgunaan mekanik promo/iklan/rujukan; (b) memulai chargeback atau pembalikan pembayaran dengan itikad buruk; atau (c) membeli atau menjual Credits, langganan, atau Accounts di luar Service. Apa pun yang diperoleh dengan melanggar aturan ini menjadi batal.</p>
      <p>6.8 <strong>Catatan kami.</strong> Catatan kami (termasuk buku besar transaksi dan catatan hak kami), kecuali ada kesalahan yang nyata, merupakan keputusan akhir atas saldo Credit, status langganan, dan transaksi Anda.</p>
      <p>6.9 <strong>Langganan Premium (diperpanjang otomatis).</strong> Premium adalah langganan yang diperpanjang otomatis yang dijual melalui toko aplikasi.</p>
      <ul>
        <li><strong>Perpanjangan otomatis.</strong> Anda dikenakan biaya melalui akun toko aplikasi Anda saat Anda membeli. <strong>Langganan diperpanjang secara otomatis untuk setiap periode baru pada harga yang berlaku saat itu kecuali Anda membatalkan setidaknya 24 jam sebelum periode saat ini berakhir</strong> (atau sebagaimana yang dipersyaratkan oleh toko aplikasi).</li>
        <li><strong>Mengelola dan membatalkan.</strong> Anda dapat mengelola atau membatalkan kapan saja di pengaturan langganan toko aplikasi Anda. Menghapus App <strong>tidak</strong> membatalkannya. Pembatalan berlaku pada akhir periode berbayar saat ini, dan Anda tetap memiliki Premium hingga saat itu.</li>
        <li><strong>Perubahan harga.</strong> Kami dapat mengubah harga; perubahan berlaku untuk periode mendatang dan diberitahukan sesuai aturan toko aplikasi, yang mungkin memerlukan persetujuan Anda terlebih dahulu.</li>
        <li><strong>Uji coba gratis / promo.</strong> Jika uji coba gratis atau promo ditawarkan, ia secara otomatis menjadi langganan berbayar kecuali Anda membatalkannya sebelum berakhir; bagian uji coba yang tidak terpakai akan hangus saat Anda berlangganan, jika berlaku.</li>
        <li><strong>Manfaat.</strong> Manfaat Premium (seperti memposting Glimpses atau tempat tanpa biaya Credit, riwayat lebih banyak, atau fitur lainnya) adalah bagian dari lisensi Anda untuk menggunakan Service, bukan properti, dapat berubah, dan berakhir saat langganan Anda berakhir atau dibatalkan.</li>
      </ul>
      <p>6.10 <strong>Ketentuan Apple / Google.</strong> Di mana toko aplikasi mensyaratkannya, ketentuan lisensi dan langganan standarnya juga berlaku, dan operator toko aplikasi dapat menjadi penerima manfaat pihak ketiga yang dapat menegakkan Ketentuan ini (lihat Bagian 14.3).</p>

      <h2 id="s7">7. Kehilangan Credits; Penangguhan dan Pengakhiran oleh Kami</h2>
      <p>7.1 <strong>Anda dapat kehilangan Credits jika melanggar aturan.</strong> <strong>Jika Anda melanggar Ketentuan ini — termasuk aturan perilaku di Bagian 9, aturan penagihan di Bagian 6.7, atau aturan kelayakan di Bagian 3 — kami dapat membatalkan dan menghanguskan sebagian atau seluruh Credits Anda (yang dibeli, diperoleh, atau gratis) dan mencabut manfaat Premium, tanpa pengembalian dana atau kompensasi, di samping tindakan lain yang kami ambil.</strong> Kami dapat melakukan ini dengan atau tanpa peringatan, masa tenang, penangguhan, atau pemblokiran tersendiri.</p>
      <p>7.2 <strong>Kapan kami dapat bertindak.</strong> Kami dapat memperingatkan Anda, membatasi fitur, menerapkan masa tenang, menangguhkan atau memblokir Account Anda secara permanen, dan/atau menghanguskan Credits, jika kami secara wajar meyakini Anda telah: (a) melanggar Ketentuan ini atau kebijakan apa pun yang dirujuknya; (b) melakukan penipuan, penyalahgunaan pembayaran, atau penyalahgunaan chargeback; (c) melecehkan, mengancam, menyakiti, atau membahayakan pengguna mana pun atau staf kami; (d) berbohong tentang usia atau identitas Anda; (e) menggunakan Service untuk ajakan komersial, promosi, atau penipuan; (f) membuat banyak Account atau Account untuk menghindari pemblokiran; atau (g) bertindak dengan cara yang menimbulkan risiko atau kemungkinan paparan hukum bagi kami, pengguna lain, atau pihak ketiga.</p>
      <p>7.3 <strong>Apa yang terjadi jika kami mengakhiri.</strong> Jika kami menangguhkan atau mengakhiri Account Anda: (a) hak Anda untuk menggunakan Service berakhir segera (atau selama periode penangguhan); (b) <strong>semua Credits dihanguskan tanpa pengembalian dana</strong>, sejauh diizinkan oleh hukum; (c) manfaat Premium berhenti (pembatalan atau pengembalian dana langganan apa pun ditangani oleh toko aplikasi berdasarkan aturannya); dan (d) bagian-bagian Ketentuan ini yang seharusnya tetap berlaku (termasuk Bagian 6.5, 7, 10, 11, 14–19) terus berlaku.</p>
      <p>7.4 <strong>Banding.</strong> Jika Anda merasa kami salah dalam tindakan penegakan, kirim email ke <strong><a href="mailto:admin@deployku.com">admin@deployku.com</a></strong>. Kami akan meninjau banding yang sungguh-sungguh tetapi tidak wajib memulihkan Account, Credits, atau manfaat apa pun.</p>
      <p>7.5 <strong>Menutup akun Anda sendiri.</strong> Anda dapat berhenti menggunakan Service dan menghapus Account Anda kapan saja di pengaturan App atau dengan mengirim email ke <strong><a href="mailto:admin@deployku.com">admin@deployku.com</a></strong>. Menghapus Account Anda menghanguskan setiap Credits yang tersisa tanpa pengembalian dana (kecuali jika hukum menyatakan sebaliknya) dan <strong>tidak</strong> dengan sendirinya membatalkan langganan yang diperpanjang otomatis — batalkan langganan tersebut melalui toko aplikasi Anda. Cara kami menangani data Anda saat penghapusan dijelaskan dalam <a href="privacy.html">Kebijakan Privasi</a>.</p>

      <h2 id="s8">8. Perekaman Panggilan, Video, Transkripsi, dan Pemantauan</h2>
      <p>8.1 <strong>Anda menyetujui perekaman.</strong> Untuk melindungi semua orang, <strong>panggilan suara di Service (Mini-Dates dan Direct Calls) direkam dan ditranskripsikan secara otomatis.</strong> App memberi tahu Anda hal ini sebelum setiap panggilan. <strong>Dengan memulai atau bergabung dalam panggilan, Anda menyetujui — dan mengonfirmasi bahwa Anda memiliki hak untuk menyetujui — panggilan tersebut direkam, ditranskripsikan, dianalisis, dan ditinjau demi keamanan.</strong> Jika Anda tidak menyetujuinya, jangan gunakan fitur panggilan.</p>
      <p>8.2 <strong>Apa yang kami lakukan dengan rekaman.</strong> Sebagaimana dijelaskan dalam <a href="privacy.html">Kebijakan Privasi</a>: audio mentah digunakan untuk membuat transkrip dan dihapus segera setelahnya; transkrip (dengan label pembicara otomatis dan ringkasan) disimpan dan hanya tersedia bagi para peserta panggilan serta staf yang berwenang untuk tujuan keamanan, moderasi, pencegahan penipuan, dan kepatuhan hukum.</p>
      <p>8.3 <strong>Keamanan dan pengalaman.</strong> Kami dapat meninjau dan menggunakan rekaman, transkrip, pesan obrolan, video Glimpse, dan konten buku harian pasangan untuk menyelidiki laporan, mendeteksi dan menghentikan penyalahgunaan, menegakkan Ketentuan ini, mematuhi hukum, melindungi pengguna, dan meningkatkan pengalaman Anda — semuanya sesuai dengan Kebijakan Privasi.</p>
      <p>8.4 <strong>Konten Glimpse dan buku harian.</strong> Video Glimpse dan entri buku harian disaring dan/atau dapat ditinjau demi keamanan. Video Glimpse disimpan dan dikirimkan melalui tautan aman bertanda tangan serta hanya ditampilkan kepada audiens yang dijelaskan dalam Bagian 1.5 dan 5.6. Anda bertanggung jawab atas apa yang Anda rekam dan posting.</p>
      <p>8.5 <strong>Jangan merekam pengguna lain.</strong> Jangan merekam, menangkap, mengambil tangkapan layar, menyiarkan, atau menyalin panggilan, suara, video Glimpse, obrolan, entri buku harian, atau profil pengguna lain — dengan cara apa pun, termasuk perangkat luar — tanpa persetujuan jelas dari pengguna tersebut dan kami. Melakukan hal itu merupakan pelanggaran serius terhadap Ketentuan ini.</p>

      <h2 id="s9">9. Aturan Komunitas</h2>
      <p>9.1 Sehubungan dengan Service, Anda setuju untuk <strong>tidak</strong>:</p>
      <ul>
        <li>melecehkan, menyalahgunakan, menguntit, mengintimidasi, mengancam, mencemarkan nama baik, atau menyakiti siapa pun, atau mendorong orang lain untuk melakukannya;</li>
        <li>menggunakan ujaran kebencian, atau mendiskriminasi berdasarkan ras, etnis, kebangsaan, agama, jenis kelamin, identitas gender, orientasi seksual, disabilitas, atau karakteristik terlindungi lainnya;</li>
        <li>membagikan konten — dalam panggilan, video Glimpse, foto, entri buku harian, atau obrolan — yang bersifat seksual eksplisit, cabul, pornografi, kekerasan, atau tidak pantas, atau memaparkan siapa pun pada konten semacam itu tanpa persetujuan;</li>
        <li>merekam atau memposting Glimpse, foto, atau entri buku harian yang menampilkan siapa pun selain diri Anda tanpa persetujuan mereka, atau yang sebenarnya bukan diri Anda;</li>
        <li>berbohong tentang identitas, usia, foto, video, atau afiliasi Anda, menyamar sebagai siapa pun, atau menjalankan profil palsu, duplikat, atau "catfishing";</li>
        <li>meminta uang, hadiah, donasi, informasi keuangan, kata sandi, atau kode satu kali dari pengguna mana pun, atau menjalankan penipuan, kecurangan asmara, skema piramida, atau ajakan komersial apa pun;</li>
        <li>mengiklankan, mempromosikan, atau menjual apa pun, atau menggunakan Service untuk tujuan komersial apa pun, tanpa persetujuan tertulis kami;</li>
        <li>membagikan atau meminta informasi pengenal atau kontak selama panggilan anonim, atau menghindari desain anonimitas dan pengungkapan;</li>
        <li>menyalahgunakan fitur koneksi — misalnya dengan membagikan atau memanen kode teman/pencocokan untuk spam, atau menyalahgunakan Pledge untuk melecehkan atau menipu;</li>
        <li>membagikan informasi pribadi seseorang tanpa persetujuan mereka ("doxxing"), termasuk lokasi dalam buku harian pasangan;</li>
        <li>menggunakan Service jika Anda berusia di bawah 18 tahun, atau berinteraksi dengannya atas nama siapa pun yang berusia di bawah 18 tahun;</li>
        <li>mengirim virus, malware, atau kode berbahaya atau mengganggu apa pun;</li>
        <li>melakukan scraping, crawling, memanen, atau mengumpulkan data tentang pengguna lain (termasuk video atau profil Glimpse), atau mengakses Service dengan cara otomatis (bot, skrip, emulator) untuk tujuan apa pun;</li>
        <li>menyelidiki, memindai, atau menguji keamanan dari, atau merusak, melewati, atau mengalahkan, langkah keamanan, pembatasan laju, anti-penipuan, moderasi, atau login apa pun;</li>
        <li>melakukan rekayasa balik, dekompilasi, pembongkaran, modifikasi, atau membuat karya turunan dari App atau Service, kecuali di mana hukum tidak mengizinkan pembatasan tersebut;</li>
        <li>menggunakan Service untuk membangun produk pesaing, atau menyalin fitur, fungsi, antarmuka, atau grafiknya;</li>
        <li>mengeksploitasi bug, memanipulasi pencocokan, peringkat, status, atau sistem imbalan, atau menyalahgunakan promosi; atau</li>
        <li>menggunakan Service dengan melanggar hukum apa pun.</li>
      </ul>
      <p>9.2 <strong>Pelaporan.</strong> App memungkinkan Anda melaporkan dan memblokir pengguna lain sebelum, selama, dan setelah panggilan, dalam obrolan, dan pada konten Glimpse. Mohon laporkan apa pun yang melanggar aturan ini. Laporan melewati moderasi kami, yang mencakup peninjauan manusia. Mengajukan laporan yang diketahui palsu atau jahat merupakan pelanggaran terhadap Ketentuan ini.</p>
      <p>9.3 <strong>Kami dapat bertindak, tetapi tidak wajib mengawasi semuanya.</strong> Kami tidak berjanji untuk memantau seluruh Content, tetapi kami dapat (sepenuhnya atas kebijaksanaan kami) meninjau, menyaring, memoderasi, menghapus, atau menolak Content apa pun, dan mengambil tindakan berdasarkan Bagian 7, kapan saja dan tanpa pemberitahuan.</p>

      <h2 id="s10">10. Content Anda dan Lisensi yang Anda Berikan kepada Kami</h2>
      <p>10.1 <strong>Anda memiliki Content Anda.</strong> Anda mempertahankan setiap hak kepemilikan yang Anda miliki atas User Content Anda.</p>
      <p>10.2 <strong>Lisensi yang Anda berikan kepada kami.</strong> Dengan mengirimkan User Content (profil Anda, foto, video Glimpse, entri buku harian, suara Anda selama panggilan, dan pesan obrolan), Anda memberikan Deployku lisensi yang bersifat di seluruh dunia, non-eksklusif, bebas royalti, dapat disublisensikan (kepada penyedia layanan kami), dan dapat dipindahtangankan untuk meng-host, menyimpan, menyalin, memproses, mengadaptasi, mentranskripsikan, menganalisis, menampilkan, dan mendistribusikannya — hanya untuk: (a) menjalankan, menyediakan, mengamankan, dan meningkatkan Service; (b) menampilkan profil, video Glimpse, entri buku harian, dan pesan Anda kepada pengguna sebagaimana Service dirancang (misalnya setelah pengungkapan, kepada audiens Glimpse Anda, atau kepada pasangan yang terhubung); (c) menangani moderasi, keamanan, pencegahan penipuan, dan penegakan; serta (d) mematuhi hukum. Lisensi ini berlaku selama kami menyimpan Content tersebut berdasarkan <a href="privacy.html">Kebijakan Privasi</a>, dan tetap berlaku setelah pengakhiran sejauh itu.</p>
      <p>10.3 <strong>Data yang dianonimkan dan diagregasi.</strong> Kami dapat membuat dan menggunakan data yang dianonimkan, dide-identifikasi, atau diagregasi dari Content dan aktivitas Anda — data yang tidak lagi dapat secara wajar mengidentifikasi Anda — untuk tujuan sah apa pun, termasuk meningkatkan pencocokan, keamanan, fitur, dan pengalaman secara keseluruhan.</p>
      <p>10.4 <strong>Janji Anda tentang Content Anda.</strong> Anda mengonfirmasi bahwa: (a) Anda memiliki semua hak yang diperlukan untuk mengirimkan User Content Anda dan memberikan lisensi di atas; (b) User Content Anda (termasuk foto, video Glimpse, dan suara Anda) menampilkan dan merupakan milik Anda, serta tidak menyertakan orang lain yang dapat diidentifikasi tanpa persetujuan mereka; dan (c) tidak dan tidak akan melanggar atau melawan hak kekayaan intelektual, privasi, publisitas, atau hak lain milik siapa pun, atau hukum apa pun.</p>
      <p>10.5 <strong>Umpan balik.</strong> Jika Anda mengirimkan saran atau ide tentang Service kepada kami, kami dapat menggunakannya secara bebas, selamanya, tanpa batasan atau pembayaran kepada Anda.</p>

      <h2 id="s11">11. Kekayaan Intelektual dan Merek Dagang</h2>
      <p>11.1 <strong>Kami memiliki Service.</strong> Service — App, perangkat lunaknya, kode, arsitektur, basis data, algoritma, sistem pencocokan dan penilaian, avatar yang dihasilkan dan desain glif, keluaran AI yang disampaikan oleh Service, antarmuka, desain, teks, grafik, audio, dan segala sesuatu lainnya (kecuali User Content) — adalah milik atau dilisensikan oleh Deployku, dan dilindungi oleh undang-undang hak cipta, merek dagang, rahasia dagang, dan undang-undang lainnya. Setiap hak yang tidak secara tegas kami berikan kepada Anda adalah hak yang kami pertahankan.</p>
      <p>11.2 <strong>Lisensi Anda untuk menggunakannya.</strong> Tunduk pada Ketentuan ini, kami memberi Anda lisensi yang bersifat pribadi, terbatas, non-eksklusif, tidak dapat dipindahtangankan, tidak dapat disublisensikan, dan dapat dicabut untuk mengunduh dan menggunakan App di perangkat yang Anda miliki atau kendalikan, untuk penggunaan pribadi dan non-komersial Anda sendiri.</p>
      <p>11.3 <strong>Merek dagang, termasuk aplikasi yang masih tertunda.</strong> "Heqiyou", logo Heqiyou, dan Marks kami lainnya adalah merek dagang milik Deployku Pte Ltd. <strong>Sebuah aplikasi merek dagang untuk "Heqiyou" saat ini sedang diperiksa oleh Intellectual Property Office of Singapore (IPOS). Fakta bahwa aplikasi ini masih tertunda tidak mengurangi, melepaskan, atau merugikan hak apa pun milik Deployku atas Marks — termasuk hak yang tidak terdaftar dan hak menurut common law, hak dalam passing off, hak cipta atas karya seni logo, dan hak yang berlaku setelah pendaftaran (yang, jika diberikan, berlaku sejak tanggal pengajuan aplikasi).</strong> Ketentuan ini tidak memberi Anda hak apa pun atas Marks. Jangan menggunakan, mendaftarkan, atau mencoba mendaftarkan Marks kami, atau nama, logo, domain, akun media sosial, atau pengenal aplikasi yang membingungkan serupa, di mana pun di dunia. Semua nilai niaga (goodwill) dari penggunaan Marks menjadi milik Deployku.</p>
      <p>11.4 <strong>Klaim pelanggaran.</strong> Jika Anda yakin Content di Service melanggar hak cipta atau hak lain milik Anda, beri tahu kami di <strong><a href="mailto:admin@deployku.com">admin@deployku.com</a></strong> dengan detail yang memadai (karya tersebut, materi yang melanggar, detail kontak Anda, dan pernyataan dengan itikad baik). Kami akan meninjau dan bertindak atas pemberitahuan yang sah sebagaimana dipersyaratkan oleh hukum.</p>

      <h2 id="s12">12. Fitur AI</h2>
      <p>12.1 <strong>Apa yang didukung AI.</strong> Service mencakup fitur AI: transkripsi otomatis dan ringkasan panggilan, perencana kencan AI yang menyarankan rencana perjalanan dari masukan yang Anda dan match Anda berikan, pendamping suara AI yang dapat Anda ajak bicara, dan moderasi konten otomatis. Pemrosesan AI dapat dilakukan oleh penyedia AI pihak ketiga atas nama kami, sebagaimana dijelaskan dalam <a href="privacy.html">Kebijakan Privasi</a>.</p>
      <p>12.2 <strong>Jangan mengandalkan keluaran AI.</strong> Keluaran AI (rencana kencan, saran tempat, transkrip, ringkasan, balasan pendamping, petunjuk kecocokan) adalah <strong>saran otomatis, disediakan "apa adanya" hanya untuk kemudahan</strong>. Keluaran tersebut mungkin salah, tidak lengkap, atau usang. Kami tidak memverifikasi tempat, jam buka, harga, detail transportasi, dan sejenisnya. Terserah Anda untuk memeriksa keluaran AI sebelum mengandalkannya, serta menjaga keputusan dan keselamatan Anda sendiri.</p>
      <p>12.3 <strong>Tempat pihak ketiga.</strong> Kami tidak terhubung dengan, dan tidak bertanggung jawab atas, tempat, bisnis, atau lokasi mana pun yang disarankan oleh fitur AI. Apa pun antara Anda dan tempat-tempat tersebut sepenuhnya merupakan urusan antara Anda dan mereka.</p>
      <p>12.4 <strong>Pendamping suara AI.</strong> Pendamping suara AI adalah agen otomatis, bukan orang sungguhan, dan penyedia AI memproses percakapan untuk menghasilkan balasan. Jangan mengandalkannya untuk nasihat (medis, hukum, keuangan, kesehatan mental, atau lainnya), dan jangan memperlakukannya sebagai pengganti bantuan profesional atau hubungan antarmanusia.</p>

      <h2 id="s13">13. Keamanan dan Berurusan dengan Pengguna Lain</h2>
      <p>13.1 <strong>Anda bertanggung jawab atas interaksi Anda.</strong> Service memperkenalkan orang-orang satu sama lain. <strong>Kami tidak menjalankan pemeriksaan latar belakang kriminal atau pemeriksaan identitas lengkap terhadap pengguna</strong>, dan pemeriksaan apa pun yang kami lakukan (seperti telepon, foto, atau liveness) bersifat terbatas dan mungkin tidak menangkap informasi palsu. Kami tidak membuat janji apa pun tentang identitas, perilaku, niat, kecocokan, atau kejujuran pengguna mana pun.</p>
      <p>13.2 <strong>Berhati-hatilah.</strong> Anda sendiri bertanggung jawab atas cara Anda berurusan dengan pengguna lain, secara daring dan terutama luring. Lakukan tindakan pencegahan yang masuk akal: bertemu di tempat umum, beri tahu seseorang ke mana Anda pergi, jangan membagikan informasi keuangan atau mengirim uang, berhati-hatilah dalam membagikan lokasi yang tepat (termasuk dalam buku harian pasangan), dan jangan hanya mengandalkan sinyal dalam aplikasi. Tips keamanan dalam aplikasi adalah untuk kemudahan dan bukan jaminan keselamatan.</p>
      <p>13.3 <strong>Kami tidak bertanggung jawab atas pengguna lain.</strong> Sejauh diizinkan oleh hukum, Deployku tidak bertanggung jawab atau berkewajiban atas perilaku pengguna mana pun, secara daring atau luring, atau atas kehilangan, cedera, atau kerusakan akibat interaksi antarpengguna — termasuk pertemuan yang diatur melalui Service atau perencana kencan AI-nya.</p>
      <p>13.4 <strong>Keadaan darurat.</strong> Service bukanlah layanan darurat. Jika Anda merasa berada dalam bahaya, hubungi polisi atau layanan darurat setempat segera.</p>

      <h2 id="s14">14. Layanan Pihak Ketiga, Iklan, dan Toko Aplikasi</h2>
      <p>14.1 <strong>Penyedia layanan.</strong> Kami menjalankan Service menggunakan layanan infrastruktur, komunikasi, penyimpanan, pengiriman konten, peta, pembayaran, periklanan, verifikasi, moderasi, dan AI dari pihak ketiga yang bertindak atas nama kami. Cara mereka menangani data pribadi dijelaskan dalam <a href="privacy.html">Kebijakan Privasi</a>. Kami tidak bertanggung jawab atas pemadaman, kesalahan, atau tindakan penyedia ini di luar kendali wajar kami.</p>
      <p>14.2 <strong>Periklanan.</strong> Service dapat menampilkan iklan, termasuk iklan berimbalan opsional. Iklan berasal dari jaringan iklan pihak ketiga; kami tidak mendukung produk atau layanan yang diiklankan, dan segala urusan dengan pengiklan sepenuhnya merupakan urusan antara Anda dan mereka.</p>
      <p>14.3 <strong>Ketentuan toko aplikasi.</strong> Pengunduhan dan penggunaan App oleh Anda, serta langganan apa pun, juga tunduk pada aturan toko aplikasi tempat Anda memperolehnya. Ketentuan ini hanya berlaku antara Anda dan Deployku; operator toko aplikasi bukan pihak dalam Ketentuan ini, tidak wajib menyediakan dukungan untuk App, dan tidak bertanggung jawab atas klaim mengenainya. Di mana aturan toko aplikasi mensyaratkannya, operator tersebut dan afiliasinya adalah penerima manfaat pihak ketiga dari Ketentuan ini dan dapat menegakkannya terhadap Anda.</p>
      <p>14.4 <strong>Tautan dan aplikasi lain.</strong> Service dapat menautkan ke situs atau sumber daya pihak ketiga (termasuk di dalam rencana kencan AI dan peta) dan dapat memungkinkan Anda membuka aplikasi lain — misalnya aplikasi ride-hailing yang telah terisi otomatis dengan tujuan yang disarankan, atau aplikasi perpesanan yang telah terisi otomatis dengan undangan dan kode Anda. Setelah Anda meninggalkan Service untuk aplikasi atau situs lain, ketentuan dan kebijakan privasi pihak ketiga tersebut yang berlaku. Kami tidak bertanggung jawab atas konten, produk, layanan, harga, atau ketersediaan mereka.</p>

      <h2 id="s15">15. Penafian Jaminan</h2>
      <p>15.1 <strong>SERVICE DISEDIAKAN "APA ADANYA" DAN "SEBAGAIMANA TERSEDIA", DENGAN SEGALA KESALAHANNYA DAN TANPA JAMINAN APA PUN.</strong> Sejauh diizinkan oleh hukum, Deployku menafikan semua jaminan dan ketentuan, baik tersurat, tersirat, maupun menurut undang-undang — termasuk jaminan tersirat apa pun atas keadaan dapat diperdagangkan, kualitas yang memuaskan, kesesuaian untuk tujuan tertentu, hak milik, kenikmatan yang tenang, keakuratan, dan tanpa pelanggaran, serta jaminan apa pun yang timbul dari cara kami bertransaksi atau apa yang lazim dalam perdagangan.</p>
      <p>15.2 Secara khusus, kami tidak menjanjikan bahwa: (a) Service akan tidak terganggu, tepat waktu, aman, bebas kesalahan, atau bebas dari virus atau komponen berbahaya; (b) pencocokan, panggilan, pesan, transkrip, keluaran AI, video Glimpse, atau Content lainnya akan akurat, andal, lengkap, atau tersedia; (c) cacat akan diperbaiki; atau (d) Service akan memenuhi harapan Anda atau mengarah pada hubungan, kencan, atau hasil lainnya.</p>
      <p>15.3 Beberapa tempat tidak mengizinkan jaminan tertentu untuk dikecualikan; di sana, hal di atas berlaku sejauh maksimum yang diizinkan, dan tidak ada dalam Ketentuan ini yang mengecualikan hak yang tidak dapat dikecualikan secara hukum.</p>

      <h2 id="s16">16. Batasan Tanggung Jawab Kami</h2>
      <p>16.1 Sejauh diizinkan oleh hukum, Deployku beserta direktur, pejabat, karyawan, agen, pemberi lisensi, dan penyedia layanannya tidak akan bertanggung jawab atas: (a) kerugian tidak langsung, insidental, khusus, konsekuensial, sebagai contoh, atau hukuman apa pun; (b) hilangnya keuntungan, pendapatan, nilai niaga, data, peluang, atau penghematan yang diharapkan; (c) kerusakan apa pun akibat penggunaan Anda atas (atau ketidakmampuan menggunakan) Service; (d) perilaku atau Content pengguna atau pihak ketiga mana pun, termasuk perilaku yang berbahaya, menyinggung, atau ilegal, dan termasuk pertemuan yang timbul dari Service; atau (e) akses tidak sah ke atau perubahan data Anda — baik klaim tersebut didasarkan pada jaminan, kontrak, perbuatan melawan hukum (termasuk kelalaian), undang-undang, atau hal lain apa pun, dan bahkan jika kami telah diperingatkan bahwa kerugian semacam itu mungkin terjadi.</p>
      <p>16.2 Sejauh diizinkan oleh hukum, <strong>total tanggung jawab kami untuk semua klaim yang berkaitan dengan Service atau Ketentuan ini tidak akan melebihi jumlah yang lebih besar antara (a) apa yang Anda bayarkan kepada kami dalam 12 bulan sebelum peristiwa yang menjadi dasar klaim, dan (b) seratus dolar Singapura (SGD 100).</strong></p>
      <p>16.3 Tidak ada dalam Ketentuan ini yang mengecualikan atau membatasi tanggung jawab atas kematian atau cedera diri yang disebabkan oleh kelalaian, atas penipuan atau pernyataan keliru yang menipu, atau atas apa pun yang tidak dapat dikecualikan atau dibatasi berdasarkan hukum. Batasan dalam Bagian ini berlaku hanya sejauh diizinkan oleh hukum.</p>
      <p>16.4 Anda setuju bahwa Bagian 15 dan 16 merupakan cara yang adil untuk membagi risiko di antara kita, dan merupakan bagian dasar dari kesepakatan kita — dan bahwa kami tidak dapat menawarkan Service dengan ketentuan ini tanpanya.</p>

      <h2 id="s17">17. Ganti Rugi</h2>
      <p>Sejauh diizinkan oleh hukum, Anda setuju untuk membela, mengganti rugi, dan membebaskan Deployku beserta direktur, pejabat, karyawan, agen, dan penyedia layanannya dari klaim, tuntutan, tindakan, kerugian, kewajiban, kerusakan, biaya, dan pengeluaran apa pun (termasuk biaya hukum yang wajar) yang timbul dari: (a) User Content Anda (termasuk video Glimpse dan entri buku harian); (b) penggunaan atau penyalahgunaan Service oleh Anda; (c) pelanggaran Anda terhadap Ketentuan ini atau hukum apa pun; (d) interaksi Anda dengan pengguna lain, secara daring atau luring; atau (e) pelanggaran Anda terhadap hak siapa pun. Kami dapat, atas biaya Anda, mengambil alih pembelaan dan kendali eksklusif atas hal apa pun yang seharusnya Anda ganti rugi, dan Anda setuju untuk bekerja sama.</p>

      <h2 id="s18">18. Hukum yang Berlaku dan Sengketa</h2>
      <p>18.1 <strong>Hukum yang berlaku.</strong> Ketentuan ini, dan sengketa apa pun yang berkaitan dengannya atau dengan Service (baik kontrak maupun bukan), diatur oleh hukum Singapura, dengan mengabaikan aturan konflik hukum.</p>
      <p>18.2 <strong>Bicaralah dengan kami terlebih dahulu.</strong> Sebelum memulai proses hukum formal, kirim email ke <strong><a href="mailto:admin@deployku.com">admin@deployku.com</a></strong> yang menjelaskan sengketa tersebut dan upayakan dengan itikad baik untuk menyelesaikannya bersama kami selama setidaknya 30 hari.</p>
      <p>18.3 <strong>Pengadilan.</strong> Tunduk pada Bagian 18.2, pengadilan Singapura memiliki yurisdiksi eksklusif atas sengketa apa pun yang berkaitan dengan Ketentuan ini atau Service, dan masing-masing dari kita tunduk pada pengadilan tersebut. Tidak ada di sini yang menghalangi salah satu dari kita untuk mengajukan upaya hukum mendesak berupa perintah pengadilan (injunctive relief) di pengadilan yang berwenang mana pun, atau membatasi hak konsumen wajib apa pun yang Anda miliki untuk mengajukan proses hukum di tempat tinggal Anda.</p>
      <p>18.4 <strong>Tidak ada gugatan kelompok.</strong> Sejauh diizinkan oleh hukum, Anda harus mengajukan sengketa secara individual, bukan sebagai penggugat atau anggota kelompok dalam proses hukum kelas, kolektif, atau perwakilan apa pun.</p>
      <p>18.5 <strong>Batas satu tahun.</strong> Sejauh diizinkan oleh hukum, klaim apa pun yang berkaitan dengan Service harus dimulai dalam satu (1) tahun setelah timbul; setelah itu klaim tersebut secara permanen terhalang.</p>

      <h2 id="s19">19. Umum</h2>
      <p>19.1 <strong>Perubahan pada Ketentuan ini.</strong> Kami dapat memperbarui Ketentuan ini. Jika perubahannya bersifat material, kami akan memberi tahu Anda melalui App atau cara wajar lainnya, dan Ketentuan yang diperbarui akan menampilkan tanggal berlaku yang baru. Menggunakan Service setelah tanggal tersebut berarti Anda menerima Ketentuan yang baru. Jika Anda tidak setuju, hentikan penggunaan Service dan, jika mau, hapus Account Anda.</p>
      <p>19.2 <strong>Keseluruhan perjanjian.</strong> Ketentuan ini, beserta <a href="privacy.html">Kebijakan Privasi</a> dan ketentuan tambahan apa pun yang ditampilkan untuk fitur atau pembelian tertentu, merupakan keseluruhan perjanjian antara Anda dan Deployku tentang Service, dan menggantikan perjanjian sebelumnya apa pun mengenai topik tersebut.</p>
      <p>19.3 <strong>Keterpisahan.</strong> Jika ada bagian dari Ketentuan ini yang dinyatakan tidak sah atau tidak dapat ditegakkan, bagian tersebut diterapkan sejauh mungkin dan sisanya tetap berlaku.</p>
      <p>19.4 <strong>Tidak ada pelepasan hak.</strong> Jika kami tidak menegakkan suatu hak atau aturan, itu bukan pelepasan haknya. Setiap pelepasan hak harus dibuat secara tertulis dan ditandatangani oleh kami.</p>
      <p>19.5 <strong>Pengalihan.</strong> Anda tidak dapat mengalihkan atau memindahkan Ketentuan ini atau Account Anda. Kami dapat mengalihkan atau memindahkannya (seluruhnya atau sebagian) secara bebas, termasuk dalam merger, akuisisi, reorganisasi, atau penjualan aset.</p>
      <p>19.6 <strong>Peristiwa di luar kendali kami.</strong> Kami tidak bertanggung jawab atas keterlambatan atau kegagalan apa pun yang disebabkan oleh hal-hal di luar kendali wajar kami, termasuk bencana alam, epidemi, perang, terorisme, kerusuhan sipil, sengketa perburuhan, tindakan pemerintah, kegagalan utilitas atau telekomunikasi, atau kegagalan penyedia pihak ketiga.</p>
      <p>19.7 <strong>Tidak ada kemitraan.</strong> Ketentuan ini tidak menciptakan kemitraan, usaha patungan, hubungan kerja, fidusia, atau keagenan apa pun antara Anda dan Deployku.</p>
      <p>19.8 <strong>Keberlanjutan.</strong> Bagian-bagian dari Ketentuan ini yang menurut sifatnya seharusnya tetap berlaku setelah pengakhiran akan tetap berlaku, termasuk Bagian 6.5, 7, 10, 11, 14–19.</p>
      <p>19.9 <strong>Bahasa.</strong> Ketentuan ini ditulis dalam bahasa Inggris. Terjemahan apa pun hanya untuk kemudahan; jika terjadi pertentangan, versi bahasa Inggris yang berlaku, kecuali jika hukum menyatakan sebaliknya.</p>
      <p>19.10 <strong>Komunikasi elektronik.</strong> Anda setuju untuk menerima komunikasi dari kami secara elektronik (pemberitahuan dalam aplikasi, notifikasi push, SMS ke nomor terdaftar Anda, atau email jika disediakan), dan bahwa komunikasi tersebut memenuhi persyaratan hukum apa pun untuk komunikasi tertulis.</p>

      <h2 id="s20">20. Kontak</h2>
      <p><strong>Deployku Pte Ltd</strong><br />
      Email: <strong><a href="mailto:admin@deployku.com">admin@deployku.com</a></strong></p>
      <p>Untuk dukungan, banding, pemberitahuan hukum, dan klaim pelanggaran, gunakan email di atas dan sertakan detail yang memadai agar kami dapat menemukan Account Anda dan menangani permintaan Anda.</p>

      <p class="doc-note">Dengan menggunakan Heqiyou, Anda mengonfirmasi bahwa Anda telah membaca, memahami, dan menyetujui Syarat dan Ketentuan ini serta <a href="privacy.html">Kebijakan Privasi</a> yang menyertainya.</p>

    `
};
