window.DK_TRANSLATIONS = window.DK_TRANSLATIONS || {};
window.DK_TRANSLATIONS.tl = {
  _lang: "tl",
  _title: "Terms and Conditions — Heqiyou · Deployku",
  "eyebrow": "Legal · Heqiyou",
  "h1": "Terms and Conditions",
  "meta": "<span>Effective Date: 28 June 2026</span><span>Version 1.3</span><span>Deployku Pte Ltd · Singapore</span>",
  "intro": `Ang Terms and Conditions na ito (ang "<strong>Terms</strong>") ang kasunduan sa pagitan mo at ng <strong>Deployku Pte Ltd</strong>, isang kumpanyang naka-rehistro sa Singapore ("<strong>Deployku</strong>", "<strong>we</strong>", "<strong>us</strong>" o "<strong>our</strong>"). Sinasaklaw nito ang paggamit mo ng Heqiyou app at lahat ng nandito — lahat ng features, content, at mga kaugnay na website at services (sama-sama, ang "<strong>Service</strong>" o "<strong>App</strong>").`,
  "nav.product": "Heqiyou",
  "nav.privacy": "Privacy",
  "nav.terms": "Terms",
  "nav.cta": "Makipag-ugnayan",
  "foot.tagline": `Isang Singapore studio na gumagawa ng mga produktong nagpapagalaw sa Southeast Asia.`,
  "foot.company": "Kumpanya",
  "foot.whatwedo": "Ang ginagawa namin",
  "foot.approach": "Approach",
  "foot.about": "Tungkol sa amin",
  "foot.careers": "Careers",
  "foot.products": "Mga Produkto",
  "foot.heqiyou": "Heqiyou",
  "foot.legal": "Legal",
  "foot.privacyLink": "Privacy Policy",
  "foot.termsLink": "Terms &amp; Conditions",
  "foot.contact": "Contact",
  "foot.email": "Email",
  "foot.getintouch": "Makipag-ugnayan",
  "foot.copyright": "© 2026 Deployku Pte Ltd. Lahat ng karapatan ay nakalaan.",
  "foot.built": "Ginawa sa Singapore · para sa Southeast Asia",
  "body": `

      <p><strong>Pakibasa ang Terms na ito. Sa paggawa ng account o paggamit ng Service, sumasang-ayon ka sa Terms na ito at sa aming <a href="privacy.html">Privacy Policy</a>. Kung hindi ka sang-ayon, huwag mong gamitin ang Service.</strong></p>

      <div class="notice-card">
        <p><strong>Ang mga mahahalagang dapat malaman agad:</strong></p>
        <ul>
          <li><strong>Kailangan mong 18 pataas para magamit ang Service.</strong></li>
          <li><strong>Ang mga voice call ay nire-record at tina-transcribe para sa safety</strong> (tingnan ang Section 8 at ang <a href="privacy.html">Privacy Policy</a>). Ang pagtawag o pagsali sa isang call ay nangangahulugang nagbibigay ka ng consent dito. Kung wala kang consent, huwag mong gamitin ang calling features.</li>
          <li><strong>Ang "Glimpse" ay nagbibigay-daan sa iyong mag-post ng maikling video ng sarili mo.</strong> Sa anonymous discovery view ay nananatiling nakatago ang pangalan at profile mo, pero <strong>ipinapakita pa rin ng video ang mukha at itsura mo</strong>. Sa pag-post nito, sumasang-ayon kang puwede itong i-screen at ipakita sa audience na pipiliin mo.</li>
          <li><strong>Ang Credits ay hindi pera. Hindi ito refundable, at puwede mo itong mawala kung lalabagin mo ang Terms na ito</strong> (tingnan ang Section 7).</li>
          <li><strong>Ang "Premium" ay isang subscription na nagre-renew at sinisingil ka nang automatic hangga't hindi mo kina-cancel</strong> (tingnan ang Section 6.9).</li>
          <li><strong>Nililimitahan ng Terms na ito ang aming legal na responsibilidad sa iyo at may kasamang indemnity na pabor sa amin</strong> (tingnan ang Sections 15–17).</li>
        </ul>
      </div>

      <h2 id="s1">1. Tungkol sa Service</h2>
      <p>1.1 Ang Heqiyou ay isang voice-first dating at social app. Sa halip na mag-swipe ng mga litrato, nakikilala mo ang mga tao sa maikli, anonymous na voice call ("<strong>Mini-Dates</strong>"). Nananatiling nakatago ang mga pangalan at litrato habang nasa call. Kapag <strong>kayong dalawa</strong> lang ang pumiling magpatuloy pagkatapos saka lang nire-reveal ang mga profile niyo sa isa't isa at magbubukas ang isang private chat.</p>
      <p>1.2 Maaaring kasama sa Service ang: sign-up gamit ang phone number o sa pamamagitan ng third party tulad ng Apple o Google; anonymous na voice call; queue-based na matching; mga compatibility hint; chat pagkatapos ng match; direct (non-anonymous) na call sa pagitan ng matched users; isang AI date-planning helper (na maaaring magmungkahi ng starting area mula sa location ng device mo at magbigay-daan sa iyong buksan ang mga app tulad ng ride-hailing na naka-pre-fill na ang destinasyon); isang AI voice companion; mga maikling video na may opsyonal na caption at isang day-recap export ("<strong>Glimpse</strong>"); mga friend connection at isang exclusive-commitment feature ("<strong>Pledge</strong>"); isang shared na "couple diary" ng mga lugar ("<strong>Places</strong>"); paggawa ng profile at litrato; pagbili ng Credits; isang <strong>Premium</strong> subscription; at mga ad na puwede mong panoorin para sa rewards.</p>
      <p>1.3 Available lang ang Service sa mga rehiyong pipiliin namin ("<strong>Supported Regions</strong>"). Ang matching at Glimpse discovery ay karaniwang limitado lang sa mga taong nasa parehong Supported Region. Puwede kaming magdagdag, mag-alis o magbago ng Supported Regions anumang oras, nang walang abiso.</p>
      <p>1.4 Patuloy naming pinapabuti ang Service. Puwede kaming magdagdag, magbago, mag-pause o mag-alis ng mga feature (kabilang ang mga nasa development pa, tulad ng mas matibay na identity check o bagong payment options), o maglagay ng mga limitasyon sa features, anumang oras at ayon sa aming pagpapasya. Kung may pagbabagong seryoso at negatibong nakakaapekto sa isang paid feature, susubukan naming bigyan ka ng advance notice.</p>
      <p>1.5 <strong>Glimpse.</strong> Ang Glimpse ay nagbibigay-daan sa iyong mag-record ng maikling video (ilang segundo) ng sarili mo, magdagdag ng opsyonal na maikling caption, at i-post ito sa isang paulit-ulit na time "window" para sa audience na pipiliin mo: <strong>Hopeful</strong> (anonymous discovery), <strong>Matched</strong>, <strong>Friends</strong>, o <strong>Pledged</strong>. Ang mga video at caption na ipinapadala sa Hopeful o Matched na audience ay sina-screen ng automated moderation bago lumitaw, at ipinapakita kasama ng isang abstract glyph at compatibility score — hindi ang pangalan o profile mo (kahit ipinapakita ng video ang itsura mo). Ang mga video na ipinapadala sa Friends o sa isang Pledged partner ay ipinapakita kasama ng pangalan at litrato mo sa mga taong iyon. Puwede ring pagsama-samahin ng Glimpse ang mga clip ng isang araw (sa iyo at sa mga kaibigan/partner mo) sa isang maikling recap video na puwede mong i-save o i-share. Ang pag-post sa Hopeful o Matched, at pag-export ng recap, ay maaaring magkaroon ng bayad sa Credits o kasama na sa Premium; ang mga Friends/Pledged post ay libre (tingnan ang Section 6).</p>
      <p>1.6 <strong>Connections, Friends at Pledge.</strong> Puwede kang bumuo ng patuloy na connection sa ibang users: isang <strong>Match</strong> (pagkatapos ng magkasamang Mini-Date), isang <strong>Friend</strong> (idinadagdag gamit ang personal na friend code), at isang <strong>Pledge</strong> (isang magkaparehong, exclusive na commitment sa pagitan ng matched users, na binubuo gamit ang isang match code). Habang naka-pledge ka, ang ilang blind-date at matching features ay naka-off, at ang ilang feature ay gumagana lang sa pledged partner mo. Puwede mong tapusin ang anumang connection anumang oras.</p>
      <p>1.7 <strong>Places (couple diary).</strong> Ang mga konektadong users (matched o pledged) ay puwedeng mag-ingat ng shared na diary ng mga lugar na napuntahan nilang magkasama — kabilang ang mga pangalan at lokasyon ng lugar, petsa, litrato, caption at notes na idinagdag ng sinuman sa kanila. Parehong nakikita ng dalawang miyembro ng connection ang diary. Ang pag-post ng isang lugar ay maaaring magkaroon ng bayad sa Credits o kasama na sa Premium (tingnan ang Section 6).</p>
      <p>1.8 <strong>AI voice companion.</strong> Maaaring bigyan ka ng Service ng pagkakataong magkaroon ng live na voice chat sa isang automated AI companion (hindi ibang tao). Ito ay time-limited at maaaring magkaroon ng bayad sa Credits.</p>
      <p>1.9 <strong>Ambassador mode.</strong> Maaari naming imbitahan ang ilang users sa isang opsyonal na "ambassador" mode na tumutulong mag-seed ng matching queue. Kung io-on mo ito, ang ilan sa mga call mo ay maaaring ma-flag para hindi isama sa ilang metrics, at ang isang call na sisimulan mo sa mode na ito ay maaaring hindi magkaroon ng bayad sa Credits. Puwede kaming magbigay, magbago o mag-alis ng ambassador eligibility ayon sa aming pagpapasya.</p>

      <h2 id="s2">2. Mga Depinisyon</h2>
      <p>Sa Terms na ito:</p>
      <ul>
        <li>Ang "<strong>Account</strong>" ay ang account na ireregister mo sa Service.</li>
        <li>Ang "<strong>Content</strong>" ay anumang data, text, audio, voice, video, images, litrato, profile, mensahe, transcript, rating, report, place entry o iba pang materyal sa Service.</li>
        <li>Ang "<strong>User Content</strong>" ay ang Content na ibinibigay mo — ang profile mo, litrato, <strong>Glimpse videos</strong>, <strong>couple-diary entries (places, litrato, caption at notes)</strong>, ang boses mo habang nasa call, at chat messages.</li>
        <li>Ang "<strong>Credits</strong>" ay ang mga in-app unit na ginagamit pambayad sa ilang feature (tingnan ang Section 6).</li>
        <li>Ang "<strong>Premium</strong>" ay isang auto-renewing na bayad na subscription na nag-a-unlock ng ilang feature at/o nag-aalis ng ilang Credit charge (tingnan ang Section 6.9).</li>
        <li>Ang "<strong>Mini-Date</strong>" ay isang anonymous, time-limited na voice call sa pagitan ng dalawang users na isinaayos ng aming matching system.</li>
        <li>Ang "<strong>Direct Call</strong>" ay isang non-anonymous na voice call sa pagitan ng mga users na na-match na.</li>
        <li>Ang "<strong>Match</strong>" ay ang kalagayan kung saan parehong pumiling magpatuloy ang dalawang users pagkatapos ng Mini-Date, kaya nire-reveal ang mga profile nila sa isa't isa.</li>
        <li>Ang "<strong>Glimpse</strong>" o "<strong>Glimpse Clip</strong>" ay isang maikling video ng sarili mo na ipo-post mo.</li>
        <li>Ang "<strong>Connection</strong>" ay isang patuloy na link sa pagitan ng dalawang users — isang Match, isang Friend, o isang Pledge.</li>
        <li>Ang "<strong>Friend</strong>" ay isang non-romantic na connection na idinagdag gamit ang friend code.</li>
        <li>Ang "<strong>Pledge</strong>" ay isang magkaparehong, exclusive na commitment sa pagitan ng dalawang matched users.</li>
        <li>Ang "<strong>Places</strong>" o ang "<strong>Couple Diary</strong>" ay ang shared na diary kung saan nagre-record ang isang Connection ng mga lugar, litrato, caption at notes.</li>
        <li>Ang "<strong>Marks</strong>" ay ang pangalang "Heqiyou", logo, word marks, at lahat ng kaugnay na branding at design.</li>
        <li>Ang "<strong>Virtual Items</strong>" ay ang Credits, Premium benefits at anumang iba pang virtual goods o feature sa Service.</li>
      </ul>

      <h2 id="s3">3. Sino ang Puwedeng Gumamit ng Service</h2>
      <p>3.1 <strong>Kailangan mong 18+.</strong> Kailangan mong nasa hindi bababa sa 18 taong gulang para gumawa ng Account o gumamit ng Service, at kinukumpirma mong ikaw ay ganoon. Puwede naming isara ang anumang Account na may makatuwirang paniniwala kaming pag-aari ng isang taong wala pang 18, nang walang refund, at puwede kaming humingi ng patunay ng edad anumang oras.</p>
      <p>3.2 <strong>Pinapayagan kang sumang-ayon, at malinis ang record mo.</strong> Kinukumpirma mong: (a) puwede kang legal na pumasok sa kontratang ito; (b) walang anuman sa batas kung saan ka nakatira ang pumipigil sa iyong gamitin ang Service; (c) hindi ka kailanman nahatulan, at hindi nahaharap sa kaso, para sa isang seryosong krimen, isang sexual offence, o anumang krimeng may kinalaman sa karahasan o banta ng karahasan; at (d) hindi ka kailangang mag-rehistro bilang sex offender saan man.</p>
      <p>3.3 <strong>Kung saan mo ito puwedeng gamitin.</strong> Ang Service ay para lamang sa paggamit sa Supported Regions. Huwag itong gamitin — o subukang iwasan ang mga regional na limitasyon (halimbawa sa pamamagitan ng VPN, pekeng location, o pekeng sign-up details) — mula sa labas ng isang Supported Region.</p>
      <p>3.4 <strong>Isang account bawat isa.</strong> Puwede ka lang magkaroon ng isang Account, para sa sarili mong personal, non-commercial na paggamit. Huwag gumawa o magpatakbo ng Account para sa ibang tao, isang organisasyon, o isang bot.</p>
      <p>3.5 <strong>Walang pagbabalik pagkatapos ng ban.</strong> Kung na-suspend, na-ban o na-remove ka na namin dati, huwag gumawa ng bagong Account maliban kung bibigyan ka namin ng nakasulat na pahintulot.</p>

      <h2 id="s4">4. Ang Iyong Account</h2>
      <p>4.1 <strong>Pag-sign up.</strong> Para magamit ang Service ay magrehistro ka gamit ang isang valid na mobile number na puwedeng tumanggap ng one-time codes, o sa pag-sign in gamit ang isang supported provider tulad ng Apple o Google. Ang isang verified na phone number ay nananatiling pangunahing identity mo para sa ilang feature. Dadaan ka sa onboarding — magbibigay ng pangalan o display name, date of birth, gender, lungsod, at ilang preference. Puwede ka ring magdagdag ng email address at profile photo.</p>
      <p>4.2 <strong>Panatilihing tama.</strong> Bigyan mo kami ng totoo, kasalukuyan at kumpletong impormasyon, kabilang ang totoong date of birth mo, at panatilihin itong updated. Ang pagsisinungaling tungkol sa edad, identity o iba pang sign-up details mo ay isang seryosong paglabag sa Terms na ito.</p>
      <p>4.3 <strong>Panatilihing secure.</strong> Responsable ka sa lahat ng nangyayari sa Account mo at sa pagprotekta sa device at phone number mo. Sabihin mo agad sa amin sa <strong><a href="mailto:admin@deployku.com">admin@deployku.com</a></strong> kung sa tingin mo ay may nag-access sa Account mo nang walang pahintulot.</p>
      <p>4.4 <strong>Verification.</strong> Maaari ka naming hilingang i-verify ang identity, edad, phone, litrato o "liveness" mo (kabilang sa pamamagitan ng mga panlabas na verification provider) bago o habang ginagamit mo ang Service, o para mag-unlock ng ilang feature (tulad ng pagtanggap ng calls). Kung hindi mo kumpletuhin ang isang kinakailangang check, maaaring malimitahan o ma-suspend ang access mo.</p>
      <p>4.5 <strong>Pag-check ng litrato at video.</strong> Ang mga litrato at Glimpse videos na ina-upload mo ay maaaring i-check ng automated systems at/o ng mga tao bago lumitaw. Puwede naming tanggihan, alisin o tumangging ipakita ang anumang litrato o video ayon sa aming pagpapasya — halimbawa kung may nudity, armas, droga, o nakakasakit na materyal ito, o kung hindi ikaw ang ipinapakita.</p>
      <p>4.6 <strong>Device permissions.</strong> Ang ilang feature ay nangangailangan ng device permissions — halimbawa microphone (calls at ang AI companion), camera (Glimpse at litrato), photo library (uploads), at opsyonal na location (para magmungkahi ng date-planning area, tumulong i-tag ang mga kalapit na lugar, o i-center ang isang mapa). Binabasa lang namin ang location mo kapag ginagamit mo ang ganoong feature; hindi namin ito tina-track sa background. Puwede mong pamahalaan ang permissions sa device settings mo; ang pag-off ng isa ay maaaring mag-disable sa matching feature.</p>

      <h2 id="s5">5. Matching, Quality at Fairness</h2>
      <p>5.1 <strong>Paano gumagana ang matching.</strong> Nagma-match ang aming systems ng mga users batay sa mga bagay na maaaring kasama ang preferences mo, kung gaano kakumpleto ang profile mo, mga compatibility hint mula sa onboarding answers mo, rehiyon mo, kung gaano katagal ka naghintay, at internal na quality, reputation at compatibility scores. Ang matching ay algorithmic at ayon sa aming pagpapasya, at <strong>hindi namin ginagarantiya ang anumang partikular na match, bilang ng matches, dalas ng call, o resulta — romantic man o iba pa.</strong></p>
      <p>5.2 <strong>Internal scores.</strong> Para panatilihing ligtas at balanse, nag-iingat kami ng pribado, internal na metrics para sa mga Account — tulad ng reputation scores (naaapektuhan ng post-call ratings at reports) at match-quality scores (naaapektuhan ng call outcomes). Ginagamit namin ang mga ito para sa matching, eligibility, rate-limiting at safety. Hindi ito paghatol sa iyo bilang tao, hindi ipinapakita sa ibang users, at hindi isang pangako mula sa amin.</p>
      <p>5.3 <strong>Eligibility at mga limitasyon.</strong> Ang ilang feature (tulad ng pagsali sa receiving queue) ay maaaring mangailangan ng mga bagay tulad ng verified na phone number, kumpletong profile, approved na litrato o system avatar, magandang standing, kumpletong verification, at pananatili sa loob ng usage limits (halimbawa monthly caps sa mga natanggap na call, o daily caps sa ilang aksyon). Puwede naming baguhin ang mga requirement at limitasyong ito anumang oras.</p>
      <p>5.4 <strong>Manatiling anonymous bago ang reveal.</strong> Sa isang Mini-Date, ipinapakita ang mga profile bilang abstract avatar. Huwag subukang talunin ang anonymity — halimbawa sa pagbibigay o paghingi ng totoong pangalan, litrato, social handle, phone number, o iba pang contact o identifying details habang nasa Mini-Date.</p>
      <p>5.5 <strong>Mutual reveal.</strong> Ang mga profile at chat ay nag-a-unlock lang kung parehong pumili ang dalawang tao na magpatuloy pagkatapos ng Mini-Date. Ang desisyong huwag magpatuloy ay final para sa call na iyon, at hindi namin ito inire-reveal sa paraang sadyang nakakahiya sa kahit sino.</p>
      <p>5.6 <strong>Glimpse discovery.</strong> Kapag nag-post ka ng Glimpse, nauunawaan mong: (a) ang mga video at caption na ipinapadala sa <strong>Hopeful</strong> o <strong>Matched</strong> ay sina-screen muna ng automated moderation at maaaring tanggihan; (b) sa <strong>Hopeful</strong>, ipinapakita ang video mo sa isang compatibility-ranked na grupo ng mga eligible na user sa rehiyon mo para sa window na iyon — nakatago ang pangalan at profile mo, pero <strong>ipinapakita ng video ang itsura mo</strong>; (c) sa <strong>Matched</strong>, <strong>Friends</strong> at <strong>Pledged</strong>, ipinapakita ang video mo kasama ng pangalan at litrato mo sa mga taong kinonekta mo; (d) ang isang day-recap na gagawin mo ay maaaring pagsamahin ang mga clip mo sa mga ipinasa ng mga kaibigan/partner mo; at (e) hindi ka dapat mag-post ng Glimpse na nagpapakita ng iba bukod sa sarili mo nang walang consent nila, o isang lumalabag sa Section 9.</p>

      <h2 id="s6">6. Credits, Purchases, Subscriptions at Billing</h2>
      <p>6.1 <strong>Ano ang Credits.</strong> Ang Credits ay isang limitado, personal, non-transferable na lisensya para gamitin ang ilang feature — at puwede namin itong bawiin. <strong>Ang Credits ay hindi pera. Walang cash value ito, walang kinikitang interes, at hindi puwedeng i-redeem, i-exchange o i-cash out para sa anumang bagay na may halaga sa labas ng Service.</strong> Hindi mo puwedeng ibenta, ipagpalit, ipamigay, i-transfer o i-pool ang Credits.</p>
      <p>6.2 <strong>Paano ka makakakuha ng Credits.</strong> Puwede kang makakuha ng Credits sa pamamagitan ng: (a) pagbili ng Credit packs sa in-app purchase sa presyong ipinapakita kapag bumili ka; (b) promotional o libreng grant (tulad ng sign-up bonus), ayon sa aming pagpapasya; (c) panonood ng rewarded ads kung saan inaalok, sa loob ng mga limitasyong itinatakda namin; at (d) anumang iba pang paraan na idadagdag namin. Puwede naming baguhin ang Credit prices, pack sizes, earning rules, feature costs at limitasyon anumang oras; ang mga pagbabago ay para lang sa hinaharap at hindi nakakaapekto sa Credits na nasa balance mo na.</p>
      <p>6.3 <strong>Paano ginagastos ang Credits.</strong> Ang mga feature na gumagamit ng Credits — tulad ng pagsisimula ng Mini-Dates, pagsisimula ng Direct Calls, paggawa ng AI date plans, paggamit ng AI voice companion, pag-post ng Glimpse sa isang paid audience (Hopeful o Matched), pag-export ng Glimpse recap, at pag-post ng lugar sa couple diary — ay nagkakahalaga ng halagang ipinapakita sa App kapag ginamit mo ang mga ito. Ang ilan sa mga ito ay maaaring libre sa isang active na Premium subscription, at ang ilang Glimpse audiences (Friends at Pledged) ay palaging libre. Para sa mga timed call, maaaring i-hold ang Credits kapag nagsimula ang call at i-settle batay sa kung gaano katagal kang aktuwal na nakakonekta. Kung mas maaga matatapos ang call kaysa sa naka-book, maaari kang masingil nang proporsyonal, at kung nabigong kumonekta ang isang call dahil sa kasalanan sa aming panig, sa pangkalahatan ay ire-release o ire-refund namin ang naka-hold na Credits.</p>
      <p>6.4 <strong>Payments at mga patakaran ng app store.</strong> Ang mga in-app purchase at subscription ay hinahawakan ng app store kung saan mo na-download at/o ng aming payment providers, at napapailalim din sa kanilang mga terms. Hindi namin sino-store ang buong card details mo. Maaari kaming magdagdag ng iba pang payment methods sa kalaunan, na may sariling terms na ipinapakita kapag bumili.</p>
      <p>6.5 <strong>Walang refund.</strong> <strong>Maliban kung kailangan ito ng batas o ng sariling mga patakaran ng app store, lahat ng pagbili ng Credits at subscriptions ay final at non-refundable</strong> — kabilang ang hindi nagamit na Credits, hindi nagamit na bahagi ng isang subscription, at mga kaso kung saan nasara, na-suspend o na-terminate ang account mo, o naitigil ang Service. Kung magpasya kaming magbigay sa iyo ng refund o credit minsan, hindi ibig sabihin nito na gagawin namin ulit ito.</p>
      <p>6.6 <strong>Expiry.</strong> Ang Credits ay hindi sa kasalukuyan nag-e-expire, pero maaari kaming magdagdag ng makatuwirang expiry o inactivity rules para sa free/promotional Credits, at — na may makatuwirang advance notice — para sa biniling Credits, kung saan pinapayagan ng batas.</p>
      <p>6.7 <strong>Walang pandaraya sa system.</strong> Huwag: (a) kumuha ng Credits, Premium benefits o iba pang Virtual Items sa pamamagitan ng pandaraya, bugs, bots, o pang-aabuso sa promo/ad/referral mechanics; (b) magsimula ng masamang-intensyon na chargebacks o payment reversals; o (c) bumili o magbenta ng Credits, subscriptions o Accounts sa labas ng Service. Anumang nakuha sa paglabag sa patakarang ito ay walang bisa.</p>
      <p>6.8 <strong>Ang aming records.</strong> Ang aming records (kabilang ang aming transaction ledger at entitlement records) ay, maliban kung may malinaw na error, ang huling salita sa Credit balance, subscription status at transactions mo.</p>
      <p>6.9 <strong>Premium subscription (auto-renewing).</strong> Ang Premium ay isang auto-renewing na subscription na ibinebenta sa pamamagitan ng app store.</p>
      <ul>
        <li><strong>Auto-renewal.</strong> Sinisingil ka sa pamamagitan ng app store account mo kapag bumili ka. <strong>Nagre-renew ito nang automatic para sa bawat bagong period sa kasalukuyang presyo maliban kung mag-cancel ka nang hindi bababa sa 24 oras bago matapos ang kasalukuyang period</strong> (o ayon sa hinihingi ng app store).</li>
        <li><strong>Pamamahala at pag-cancel.</strong> Puwede mong pamahalaan o i-cancel anumang oras sa subscription settings ng app store mo. Ang pag-delete sa App ay <strong>hindi</strong> nag-cancel nito. Ang pag-cancel ay nagkaka-bisa sa katapusan ng kasalukuyang bayad na period, at pananatilihin mo ang Premium hanggang doon.</li>
        <li><strong>Pagbabago ng presyo.</strong> Maaari naming baguhin ang presyo; ang mga pagbabago ay para sa mga susunod na period at iaabiso ayon sa mga patakaran ng app store, na maaaring mangailangan muna ng pagsang-ayon mo.</li>
        <li><strong>Free trials / promos.</strong> Kung may inaalok na free trial o promo, awtomatiko itong nagiging bayad na subscription maliban kung mag-cancel ka bago ito matapos; anumang hindi nagamit na bahagi ng isang trial ay nawawala kapag nag-subscribe ka, kung saan naaangkop.</li>
        <li><strong>Benefits.</strong> Ang Premium benefits (tulad ng pag-post ng Glimpses o places nang walang Credit charge, mas maraming history, o iba pang feature) ay bahagi ng lisensya mo na gamitin ang Service, ay hindi ari-arian, ay maaaring magbago, at natatapos kapag natapos o na-cancel ang subscription mo.</li>
      </ul>
      <p>6.10 <strong>Apple / Google terms.</strong> Kung saan kinakailangan ito ng app store, naaangkop din ang standard na lisensya at subscription terms nito, at ang app store operator ay maaaring isang third-party beneficiary na puwedeng magpatupad ng Terms na ito (tingnan ang Section 14.3).</p>

      <h2 id="s7">7. Pagkawala ng Credits; Suspension at Termination ng Amin</h2>
      <p>7.1 <strong>Puwede kang mawalan ng Credits kung lalabagin mo ang mga patakaran.</strong> <strong>Kung lalabagin mo ang Terms na ito — kabilang ang conduct rules sa Section 9, ang billing rules sa Section 6.7, o ang eligibility rules sa Section 3 — puwede naming kanselahin at i-forfeit ang anuman o lahat ng Credits mo (binili, kinita o libre) at bawiin ang Premium benefits, nang walang refund o kompensasyon, bukod pa sa anumang ibang aksyong gagawin namin.</strong> Puwede namin itong gawin nang may o walang hiwalay na babala, cooldown, suspension o ban.</p>
      <p>7.2 <strong>Kailan kami puwedeng kumilos.</strong> Maaari ka naming balaan, paghigpitan ang mga feature, mag-apply ng cooldown, mag-suspend o permanenteng mag-ban sa Account mo, at/o mag-forfeit ng Credits, kung may makatuwirang paniniwala kaming: (a) nilabag mo ang Terms na ito o anumang patakarang tinutukoy nito; (b) gumawa ng pandaraya, payment abuse o chargeback abuse; (c) nang-harass, nananakot, nanakit o nanganib sa kahit sinong user o sa staff namin; (d) nagsinungaling tungkol sa edad o identity mo; (e) ginamit ang Service para sa commercial solicitation, promotion o scamming; (f) gumawa ng maraming o ban-evading na Accounts; o (g) kung hindi man, kumilos sa paraang lumilikha ng panganib o posibleng legal exposure para sa amin, ibang users, o third parties.</p>
      <p>7.3 <strong>Ano ang mangyayari kung mag-terminate kami.</strong> Kung mag-suspend o mag-terminate kami ng Account mo: (a) ang karapatan mong gamitin ang Service ay natatapos agad (o para sa panahon ng suspension); (b) <strong>lahat ng Credits ay na-forfeit nang walang refund</strong>, sa pinakamalawak na pinapayagan ng batas; (c) titigil ang Premium benefits (anumang subscription cancellation o refund ay hinahawakan ng app store ayon sa mga patakaran nito); at (d) ang mga bahagi ng Terms na ito na dapat manatili (kabilang ang Sections 6.5, 7, 10, 11, 14–19) ay patuloy na naaangkop.</p>
      <p>7.4 <strong>Appeals.</strong> Kung sa tingin mo ay nagkamali kami sa isang enforcement action, mag-email sa <strong><a href="mailto:admin@deployku.com">admin@deployku.com</a></strong>. Susuriin namin ang mga tunay na appeal pero hindi kailangang ibalik ang anumang Account, Credits o benefits.</p>
      <p>7.5 <strong>Pagsasara ng sarili mong account.</strong> Puwede mong itigil ang paggamit ng Service at i-delete ang Account mo anumang oras sa App settings o sa pag-email sa <strong><a href="mailto:admin@deployku.com">admin@deployku.com</a></strong>. Ang pag-delete sa Account mo ay nag-fo-forfeit sa anumang natitirang Credits nang walang refund (maliban kung iba ang sabi ng batas) at <strong>hindi</strong> mismo nag-cancel ng isang auto-renewing na subscription — i-cancel iyon sa pamamagitan ng app store mo. Kung paano namin hinahawakan ang data mo sa pag-delete ay nasa <a href="privacy.html">Privacy Policy</a>.</p>

      <h2 id="s8">8. Call Recording, Video, Transcription at Monitoring</h2>
      <p>8.1 <strong>Nagbibigay ka ng consent sa recording.</strong> Para protektahan ang lahat, <strong>ang mga voice call sa Service (Mini-Dates at Direct Calls) ay nire-record at awtomatikong tina-transcribe.</strong> Sinasabi sa iyo ng App ito bago ang bawat call. <strong>Sa pagsisimula o pagsali sa isang call, nagbibigay ka ng consent — at kinukumpirma mong may karapatan kang magbigay ng consent — na ang call na iyon ay nire-record, tina-transcribe, ina-analyze at sinusuri para sa safety.</strong> Kung wala kang consent, huwag mong gamitin ang calling features.</p>
      <p>8.2 <strong>Ano ang ginagawa namin sa mga recording.</strong> Tulad ng ipinaliwanag sa <a href="privacy.html">Privacy Policy</a>: ang raw audio ay ginagamit para gumawa ng transcript at agad na dine-delete pagkatapos; ang transcript (na may automatic speaker labels at summary) ay iniingatan at available lang sa mga participant ng call at sa mga authorized na staff para sa safety, moderation, fraud-prevention at legal-compliance na layunin.</p>
      <p>8.3 <strong>Safety at experience.</strong> Maaari naming suriin at gamitin ang mga recording, transcript, chat messages, Glimpse videos at couple-diary content para imbestigahan ang mga report, tuklasin at pigilan ang abuso, ipatupad ang Terms na ito, sumunod sa batas, protektahan ang mga user, at pabutihin ang experience mo — lahat ayon sa Privacy Policy.</p>
      <p>8.4 <strong>Glimpse at diary content.</strong> Ang mga Glimpse video at diary entries ay sina-screen at/o maaaring suriin para sa safety. Ang mga Glimpse video ay nakaimbak at inihahatid sa pamamagitan ng secure, signed links at ipinapakita lang sa mga audience na inilarawan sa Sections 1.5 at 5.6. Responsable ka sa kung ano ang nire-record at pino-post mo.</p>
      <p>8.5 <strong>Huwag i-record ang ibang users.</strong> Huwag i-record, i-capture, i-screenshot, i-broadcast o kung hindi man kopyahin ang call, boses, Glimpse video, chat, diary entry o profile ng ibang user — sa anumang paraan, kabilang ang isang panlabas na device — nang walang malinaw na consent ng user na iyon at namin. Ang paggawa nito ay isang seryosong paglabag sa Terms na ito.</p>

      <h2 id="s9">9. Mga Patakaran ng Komunidad</h2>
      <p>9.1 Kaugnay ng Service, sumasang-ayon kang <strong>hindi</strong>:</p>
      <ul>
        <li>mang-harass, mang-abuso, mang-stalk, manakot, mananakot, manira o manakit ng kahit sino, o hikayatin ang iba na gawin ito;</li>
        <li>gumamit ng hate speech, o mang-discriminate batay sa lahi, etnisidad, nasyonalidad, relihiyon, kasarian, gender identity, sexual orientation, kapansanan, o anumang iba pang protektadong katangian;</li>
        <li>mag-share ng content — sa mga call, Glimpse videos, litrato, diary entries o chat — na sexually explicit, obscene, pornographic, marahas o kung hindi man kahindik-hindik, o ilantad ang kahit sino sa ganoong content nang walang consent;</li>
        <li>mag-record o mag-post ng Glimpse, litrato o diary entry na nagpapakita ng iba bukod sa sarili mo nang walang consent nila, o isang hindi talaga ikaw;</li>
        <li>magsinungaling tungkol sa identity, edad, litrato, video o affiliation mo, magpanggap na ibang tao, o magpatakbo ng peke, dobleng o "catfishing" na profile;</li>
        <li>humingi sa kahit sinong user ng pera, regalo, donasyon, financial information, password o one-time codes, o magpatakbo ng anumang scam, romance fraud, pyramid scheme o commercial solicitation;</li>
        <li>mag-advertise, mag-promote o magbenta ng kahit ano, o gamitin ang Service para sa anumang commercial na layunin, nang walang nakasulat naming consent;</li>
        <li>mag-share o humingi ng identifying o contact information habang nasa anonymous calls, o kung hindi man iwasan ang anonymity at reveal design;</li>
        <li>abusuhin ang connection features — halimbawa sa pag-share o pag-harvest ng friend/match codes para sa spam, o pang-aabuso sa Pledge para mang-harass o manlinlang;</li>
        <li>mag-share ng pribadong impormasyon ng isang tao nang walang consent nila ("doxxing"), kabilang ang mga lokasyon sa isang couple diary;</li>
        <li>gumamit ng Service kung wala kang 18, o makipag-ugnayan dito sa ngalan ng sinumang wala pang 18;</li>
        <li>magpadala ng viruses, malware o anumang nakakapinsala o nakakagulong code;</li>
        <li>mag-scrape, mag-crawl, mag-harvest o mangolekta ng data tungkol sa ibang users (kabilang ang Glimpse videos o profiles), o mag-access ng Service sa automated means (bots, scripts, emulators) para sa anumang layunin;</li>
        <li>mag-probe, mag-scan o mag-test ng security ng, o sirain, lampasan o talunin, ang anumang security, rate-limiting, anti-fraud, moderation o login measure;</li>
        <li>mag-reverse engineer, mag-decompile, mag-disassemble, mag-modify o gumawa ng derivative works ng App o Service, maliban kung saan hindi pinapayagan ng batas ang restriksyong iyon;</li>
        <li>gumamit ng Service para bumuo ng isang competing product, o kopyahin ang anuman sa mga feature, function, interface o graphics nito;</li>
        <li>mag-exploit ng bugs, mang-manipula ng matching, ratings, standing o reward systems, o mang-abuso ng promotions; o</li>
        <li>gumamit ng Service sa paglabag sa anumang batas.</li>
      </ul>
      <p>9.2 <strong>Reporting.</strong> Ang App ay nagbibigay-daan sa iyong mag-report at mag-block ng ibang users bago, habang at pagkatapos ng calls, sa chat, at sa Glimpse content. Pakireport ang anumang lumalabag sa mga patakarang ito. Ang mga report ay dumadaan sa aming moderation, na may kasamang human review. Ang pag-file ng tahasang peke o malisyosong report ay mismong isang paglabag sa Terms na ito.</p>
      <p>9.3 <strong>Puwede kaming kumilos, pero hindi kailangang bantayan ang lahat.</strong> Hindi namin ipinapangakong i-monitor ang lahat ng Content, pero puwede naming (ganap na ayon sa aming pagpapasya) suriin, i-screen, i-moderate, alisin o tanggihan ang anumang Content, at kumilos sa ilalim ng Section 7, anumang oras at nang walang abiso.</p>

      <h2 id="s10">10. Ang Iyong Content at ang Lisensyang Ibinibigay Mo sa Amin</h2>
      <p>10.1 <strong>Pag-aari mo ang Content mo.</strong> Iniingatan mo ang anumang karapatan sa pagmamay-ari na mayroon ka sa User Content mo.</p>
      <p>10.2 <strong>Ang lisensyang ibinibigay mo sa amin.</strong> Sa pagsumite ng User Content (ang profile, litrato, Glimpse videos, diary entries, boses mo habang nasa call, at chat messages mo), binibigyan mo ang Deployku ng isang worldwide, non-exclusive, royalty-free, sublicensable (sa aming service providers) at transferable na lisensya para i-host, i-store, kopyahin, i-process, i-adapt, i-transcribe, i-analyze, i-display at i-distribute ito — para lamang sa: (a) pagpapatakbo, pagbibigay, pag-secure at pagpapabuti ng Service; (b) pagpapakita ng profile, Glimpse videos, diary entries at messages mo sa mga user ayon sa pagkakadisenyo ng Service (halimbawa pagkatapos ng reveal, sa Glimpse audience mo, o sa isang konektadong partner); (c) paghawak ng moderation, safety, fraud-prevention at enforcement; at (d) pagsunod sa batas. Ang lisensyang ito ay tumatagal hangga't iniingatan namin ang Content na iyon sa ilalim ng <a href="privacy.html">Privacy Policy</a>, at nananatili pagkatapos ng termination sa lawak na iyon.</p>
      <p>10.3 <strong>Anonymized at aggregated data.</strong> Maaari kaming gumawa at gumamit ng anonymized, de-identified o aggregated na data mula sa Content at aktibidad mo — data na hindi na makatuwirang makakapagpakilala sa iyo — para sa anumang legal na layunin, kabilang ang pagpapabuti ng matching, safety, features at ng kabuuang experience.</p>
      <p>10.4 <strong>Ang mga pangako mo tungkol sa Content mo.</strong> Kinukumpirma mong: (a) mayroon kang lahat ng karapatang kailangan para isumite ang User Content mo at ibigay ang lisensya sa itaas; (b) ang User Content mo (kabilang ang litrato, Glimpse videos at boses mo) ay nagpapakita at pag-aari mo, at hindi kasama ang sinumang iba pang nakikilalang tao nang walang consent nila; at (c) hindi ito at hindi nito lalabagin o vile-violate ang intellectual-property, privacy, publicity o iba pang karapatan ng kahit sino, o anumang batas.</p>
      <p>10.5 <strong>Feedback.</strong> Kung magpapadala ka sa amin ng mga mungkahi o ideya tungkol sa Service, puwede namin itong gamitin nang malaya, magpakailanman, nang walang restriksyon o bayad sa iyo.</p>

      <h2 id="s11">11. Intellectual Property at Trademarks</h2>
      <p>11.1 <strong>Pag-aari namin ang Service.</strong> Ang Service — ang App, software, code, architecture, databases, algorithms, matching at scoring systems, mga generated avatar at glyph design, AI outputs na inihahatid ng Service, interfaces, design, text, graphics, audio at lahat ng iba pa (maliban sa User Content) — ay pag-aari o lisensyado ng Deployku, at protektado ng copyright, trademark, trade-secret at iba pang batas. Anumang karapatang hindi namin tahasang ibinibigay sa iyo ay nakalaan.</p>
      <p>11.2 <strong>Ang lisensya mo para gamitin ito.</strong> Napapailalim sa Terms na ito, binibigyan ka namin ng personal, limitado, non-exclusive, non-transferable, non-sublicensable, revocable na lisensya para i-download at gamitin ang App sa mga device na pag-aari o kontrolado mo, para sa sarili mong personal, non-commercial na paggamit.</p>
      <p>11.3 <strong>Trademarks, kabilang ang pending na aplikasyon.</strong> Ang "Heqiyou", ang Heqiyou logo at ang aming iba pang Marks ay mga trademark ng Deployku Pte Ltd. <strong>Isang trademark application para sa "Heqiyou" ang kasalukuyang sinusuri ng Intellectual Property Office of Singapore (IPOS). Ang katotohanang pending pa ang aplikasyong ito ay hindi nagbabawas, nag-wawaive o nakakasira sa anuman sa mga karapatan ng Deployku sa Marks — kabilang ang unregistered at common-law na karapatan, mga karapatan sa passing off, copyright sa logo artwork, at mga karapatang nagkaka-bisa sa pagkaka-rehistro (na, kung ipagkaloob, ay naaangkop mula sa filing date ng aplikasyon).</strong> Ang Terms na ito ay hindi nagbibigay sa iyo ng karapatan sa Marks. Huwag gamitin, i-rehistro, o subukang i-rehistro ang anuman sa aming Marks, o anumang nakakalitong magkahawig na pangalan, logo, domain, social handle o app identifier, saan man sa mundo. Lahat ng goodwill mula sa anumang paggamit ng Marks ay pag-aari ng Deployku.</p>
      <p>11.4 <strong>Mga claim sa infringement.</strong> Kung naniniwala kang ang Content sa Service ay lumalabag sa copyright o iba pang karapatan mo, sabihin sa amin sa <strong><a href="mailto:admin@deployku.com">admin@deployku.com</a></strong> nang may sapat na detalye (ang gawa, ang lumalabag na materyal, ang contact details mo, at isang good-faith na pahayag). Susuriin at aaksyunan namin ang mga valid na abiso ayon sa hinihingi ng batas.</p>

      <h2 id="s12">12. AI Features</h2>
      <p>12.1 <strong>Ano ang AI-powered.</strong> Kasama sa Service ang mga AI feature: automatic transcription at summaries ng calls, isang AI date planner na nagmumungkahi ng itineraries mula sa inputs na ibinibigay mo at ng match mo, isang AI voice companion na puwede mong kausapin, at automated content moderation. Ang AI processing ay maaaring gawin ng third-party AI providers sa ngalan namin, gaya ng inilarawan sa <a href="privacy.html">Privacy Policy</a>.</p>
      <p>12.2 <strong>Huwag umasa sa AI outputs.</strong> Ang AI outputs (date plans, venue suggestions, transcripts, summaries, companion replies, compatibility hints) ay <strong>automatic na mungkahi, ibinibigay nang "as is" para lang sa convenience</strong>. Maaaring mali, hindi kumpleto o luma na ang mga ito. Hindi namin vine-verify ang mga venue, oras ng pagbubukas, presyo, transport details at iba pa. Nasa iyo ang pag-check sa AI outputs bago umasa dito, at pag-aalaga sa sarili mong mga desisyon at safety.</p>
      <p>12.3 <strong>Third-party venues.</strong> Hindi kami konektado sa, at hindi responsable para sa, anumang venue, negosyo o lugar na imumungkahi ng isang AI feature. Ang anuman sa pagitan mo at ng mga lugar na iyon ay puro sa pagitan mo at nila.</p>
      <p>12.4 <strong>AI voice companion.</strong> Ang AI voice companion ay isang automated agent, hindi tunay na tao, at isang AI provider ang nagpo-process sa pag-uusap para makabuo ng replies. Huwag umasa dito para sa payo (medical, legal, financial, mental-health o iba pa), at huwag itong ituring na kapalit ng professional na tulong o relasyon ng tao.</p>

      <h2 id="s13">13. Safety at Pakikitungo sa Ibang Users</h2>
      <p>13.1 <strong>Responsable ka sa mga interaksyon mo.</strong> Ang Service ay nagpapakilala ng mga tao sa isa't isa. <strong>Hindi kami nagpapatakbo ng criminal-background o buong identity checks sa mga user</strong>, at anumang checks na ginagawa namin (tulad ng phone, litrato o liveness) ay limitado at maaaring hindi makahuli ng maling impormasyon. Wala kaming pinapangako tungkol sa identity, asal, intensyon, compatibility o katapatan ng sinumang user.</p>
      <p>13.2 <strong>Mag-ingat.</strong> Ikaw lang ang responsable sa kung paano ka nakikitungo sa ibang users, online at lalo na offline. Gumawa ng common-sense na pag-iingat: magkita sa publiko, sabihin sa isang tao kung saan ka pupunta, huwag mag-share ng financial information o magpadala ng pera, mag-ingat sa pag-share ng tumpak na lokasyon (kabilang sa isang couple diary), at huwag umasa lang sa in-app signals. Ang in-app safety tips ay para sa convenience at hindi garantiya ng safety.</p>
      <p>13.3 <strong>Hindi kami liable para sa ibang users.</strong> Sa pinakamalawak na pinapayagan ng batas, hindi responsable o liable ang Deployku para sa asal ng kahit sinong user, online o offline, o para sa anumang pagkawala, pinsala o danyos mula sa interaksyon sa pagitan ng mga user — kabilang ang mga pagkikitang isinaayos sa pamamagitan ng Service o ng AI date planner nito.</p>
      <p>13.4 <strong>Mga emergency.</strong> Ang Service ay hindi isang emergency service. Kung sa tingin mo ay nasa panganib ka, makipag-ugnayan agad sa lokal na pulisya o emergency services.</p>

      <h2 id="s14">14. Third-Party Services, Ads at App Stores</h2>
      <p>14.1 <strong>Service providers.</strong> Pinapatakbo namin ang Service gamit ang infrastructure, communications, storage, content delivery, maps, payment, advertising, verification, moderation at AI services mula sa mga third party na kumikilos sa ngalan namin. Kung paano nila hinahawakan ang personal data ay nasa <a href="privacy.html">Privacy Policy</a>. Hindi kami responsable para sa mga outage, error o gawa ng mga provider na ito na lampas sa aming makatuwirang kontrol.</p>
      <p>14.2 <strong>Advertising.</strong> Maaaring magpakita ang Service ng mga ad, kabilang ang opsyonal na rewarded ads. Ang mga ad ay nanggagaling sa third-party ad networks; hindi namin ine-endorso ang mga advertised na produkto o serbisyo, at anumang pakikitungo sa mga advertiser ay puro sa pagitan mo at nila.</p>
      <p>14.3 <strong>App store terms.</strong> Ang pag-download at paggamit mo ng App, at anumang subscription, ay napapailalim din sa mga patakaran ng app store kung saan mo ito nakuha. Ang Terms na ito ay sa pagitan mo at ng Deployku lamang; ang app store operator ay hindi parte nito, hindi kailangang magbigay ng support para sa App, at hindi responsable sa mga claim tungkol dito. Kung saan kinakailangan ito ng mga patakaran ng app store, ang operator na iyon at ang mga affiliate nito ay mga third-party beneficiary ng Terms na ito at puwedeng ipatupad ang mga ito laban sa iyo.</p>
      <p>14.4 <strong>Links at iba pang apps.</strong> Maaaring mag-link ang Service sa mga third-party site o resource (kabilang sa loob ng AI date plans at maps) at maaaring magbigay-daan sa iyong buksan ang ibang app — halimbawa isang ride-hailing app na naka-pre-fill na ang imumungkahing destinasyon, o isang messaging app na naka-pre-fill na ang isang imbitasyon at code mo. Kapag umalis ka na sa Service para sa ibang app o site, naaangkop ang sariling terms at privacy policy ng third party na iyon. Hindi kami responsable para sa content, products, services, pricing o availability nila.</p>

      <h2 id="s15">15. Disclaimer ng mga Warranty</h2>
      <p>15.1 <strong>ANG SERVICE AY IBINIBIGAY "AS IS" AT "AS AVAILABLE", NA MAY LAHAT NG DEPEKTO AT WALANG ANUMANG WARRANTY.</strong> Sa pinakamalawak na pinapayagan ng batas, itinatanggi ng Deployku ang lahat ng warranty at kondisyon, express, implied man o statutory — kabilang ang anumang implied warranties ng merchantability, satisfactory quality, fitness for a particular purpose, title, quiet enjoyment, accuracy at non-infringement, at anumang warranty na nagmumula sa kung paano kami nakitungo o sa kung ano ang kaugalian sa kalakalan.</p>
      <p>15.2 Sa partikular, hindi namin ipinapangakong: (a) ang Service ay magiging walang patid, nasa oras, secure, error-free o walang viruses o nakakapinsalang component; (b) anumang matches, calls, messages, transcripts, AI outputs, Glimpse videos o iba pang Content ay magiging tumpak, maaasahan, kumpleto o available; (c) maaayos ang mga depekto; o (d) matutugunan ng Service ang mga inaasahan mo o hahantong sa anumang relasyon, date o iba pang resulta.</p>
      <p>15.3 Ang ilang lugar ay hindi nagpapahintulot na ibukod ang ilang warranty; doon, ang nasa itaas ay naaangkop sa pinakamataas na lawak na pinapayagan, at walang anuman sa Terms na ito ang nagbubukod sa mga karapatang hindi legal na maibubukod.</p>

      <h2 id="s16">16. Limitasyon sa Aming Liability</h2>
      <p>16.1 Sa pinakamalawak na pinapayagan ng batas, ang Deployku at ang mga direktor, opisyal, empleyado, ahente, licensor at service provider nito ay hindi magiging liable para sa: (a) anumang indirect, incidental, special, consequential, exemplary o punitive na danyos; (b) nawalang kita, revenue, goodwill, data, oportunidad o inaasahang savings; (c) anumang pinsala mula sa paggamit mo (o kawalan ng kakayahang gamitin) ang Service; (d) ang asal o Content ng sinumang user o third party, kabilang ang nakakapinsala, nakakasakit o ilegal na asal, at kabilang ang mga pagkikitang nagmumula sa Service; o (e) hindi awtorisadong pag-access o pagbabago sa data mo — claim man ay batay sa warranty, kontrata, tort (kabilang ang negligence), batas o kahit ano pa, at kahit binalaan kami na posible ang ganoong danyos.</p>
      <p>16.2 Sa pinakamalawak na pinapayagan ng batas, <strong>ang aming kabuuang liability para sa lahat ng claim na may kaugnayan sa Service o sa Terms na ito ay hindi lalampas sa mas malaki sa (a) kung ano ang binayad mo sa amin sa loob ng 12 buwan bago ang pangyayaring sanhi ng claim, at (b) isang daang Singapore dollars (SGD 100).</strong></p>
      <p>16.3 Walang anuman sa Terms na ito ang nagbubukod o naglilimita sa liability para sa kamatayan o personal na pinsalang dulot ng negligence, para sa pandaraya o fraudulent misrepresentation, o para sa anumang hindi maibubukod o malilimitahan sa ilalim ng batas. Ang mga limitasyon sa Section na ito ay naaangkop lamang hanggang sa pinapayagan ng batas.</p>
      <p>16.4 Sumasang-ayon ka na ang Sections 15 at 16 ay isang patas na paraan para magbahagi ng panganib sa pagitan natin, at isang batayang bahagi ng kasunduan natin — at na hindi namin maiaalok ang Service sa mga terms na ito nang wala ang mga ito.</p>

      <h2 id="s17">17. Indemnity</h2>
      <p>Sa pinakamalawak na pinapayagan ng batas, sumasang-ayon kang ipagtanggol, i-indemnify at iligtas ang Deployku at ang mga direktor, opisyal, empleyado, ahente at service provider nito mula sa anumang claims, demands, actions, losses, liabilities, damages, costs at expenses (kabilang ang makatuwirang legal fees) na nagmumula sa: (a) ang User Content mo (kabilang ang Glimpse videos at diary entries); (b) ang paggamit o maling paggamit mo ng Service; (c) ang paglabag mo sa Terms na ito o anumang batas; (d) ang mga interaksyon mo sa ibang users, online o offline; o (e) ang paglabag mo sa mga karapatan ng kahit sino. Maaari naming, sa gastos mo, kunin ang exclusive na depensa at kontrol ng anumang bagay na kung hindi ay ii-indemnify mo, at sumasang-ayon kang makipag-cooperate.</p>

      <h2 id="s18">18. Governing Law at mga Dispute</h2>
      <p>18.1 <strong>Governing law.</strong> Ang Terms na ito, at anumang dispute na may kaugnayan dito o sa Service (kontrata man o hindi), ay pinamamahalaan ng mga batas ng Singapore, na hindi pinapansin ang conflict-of-laws rules.</p>
      <p>18.2 <strong>Kausapin muna kami.</strong> Bago magsimula ng pormal na proceedings, mag-email sa <strong><a href="mailto:admin@deployku.com">admin@deployku.com</a></strong> na inilalarawan ang dispute at subukang lutasin ito nang may mabuting loob kasama namin sa loob ng hindi bababa sa 30 araw.</p>
      <p>18.3 <strong>Mga korte.</strong> Napapailalim sa Section 18.2, ang mga korte ng Singapore ang may exclusive jurisdiction sa anumang dispute na may kaugnayan sa Terms na ito o sa Service, at bawat isa sa atin ay sumusuko sa mga korteng iyon. Walang anuman dito ang pumipigil sa kahit sino sa atin na humingi ng agarang injunctive relief sa anumang karampatang korte, o naglilimita sa anumang mandatory consumer rights na mayroon ka para magsimula ng proceedings kung saan ka nakatira.</p>
      <p>18.4 <strong>Walang class actions.</strong> Hanggang sa pinapayagan ng batas, kailangan mong dalhin ang mga dispute nang isa-isa, hindi bilang plaintiff o class member sa anumang class, collective o representative proceeding.</p>
      <p>18.5 <strong>One-year limit.</strong> Hanggang sa pinapayagan ng batas, anumang claim na may kaugnayan sa Service ay kailangang simulan sa loob ng isang (1) taon pagkatapos itong lumitaw; pagkatapos noon ay permanenteng nabar.</p>

      <h2 id="s19">19. Pangkalahatan</h2>
      <p>19.1 <strong>Mga pagbabago sa Terms na ito.</strong> Maaari naming i-update ang Terms na ito. Kung material ang mga pagbabago, aabisuhan ka namin sa pamamagitan ng App o ibang makatuwirang paraan, at ang updated na Terms ay magpapakita ng bagong effective date. Ang paggamit ng Service pagkatapos ng petsang iyon ay nangangahulugang tinatanggap mo ang bagong Terms. Kung hindi ka sang-ayon, itigil ang paggamit ng Service at, kung gusto mo, i-delete ang Account mo.</p>
      <p>19.2 <strong>Buong kasunduan.</strong> Ang Terms na ito, kasama ang <a href="privacy.html">Privacy Policy</a> at anumang dagdag na terms na ipinapakita para sa mga partikular na feature o purchase, ang buong kasunduan sa pagitan mo at ng Deployku tungkol sa Service, at pumapalit sa anumang naunang kasunduan sa paksa.</p>
      <p>19.3 <strong>Severability.</strong> Kung ang anumang bahagi ng Terms na ito ay matagpuang invalid o hindi maipapatupad, ang bahaging iyon ay ina-apply hanggang sa makakaya at ang natitira ay nananatiling may bisa.</p>
      <p>19.4 <strong>Walang waiver.</strong> Kung hindi namin ipinatupad ang isang karapatan o patakaran, hindi iyon isang waiver nito. Anumang waiver ay dapat nakasulat at nilagdaan namin.</p>
      <p>19.5 <strong>Assignment.</strong> Hindi mo puwedeng i-assign o i-transfer ang Terms na ito o ang Account mo. Puwede naming i-assign o i-transfer ang mga ito (sa kabuuan o bahagi) nang malaya, kabilang sa isang merger, acquisition, reorganisation o sale of assets.</p>
      <p>19.6 <strong>Mga pangyayaring lampas sa aming kontrol.</strong> Hindi kami liable para sa anumang pagkaantala o kabiguang dulot ng mga bagay na lampas sa aming makatuwirang kontrol, kabilang ang mga natural na sakuna, epidemya, digmaan, terorismo, kaguluhang sibil, labor disputes, aksyon ng gobyerno, kabiguan ng utility o telecom, o kabiguan ng third-party providers.</p>
      <p>19.7 <strong>Walang partnership.</strong> Ang Terms na ito ay hindi lumilikha ng anumang partnership, joint venture, employment, fiduciary o agency na relasyon sa pagitan mo at ng Deployku.</p>
      <p>19.8 <strong>Survival.</strong> Ang mga bahagi ng Terms na ito na sa kanilang likas na katangian ay dapat magpatuloy pagkatapos ng termination ay mananatili, kabilang ang Sections 6.5, 7, 10, 11, 14–19.</p>
      <p>19.9 <strong>Wika.</strong> Ang Terms na ito ay nakasulat sa English. Anumang translation ay para sa convenience lamang; kung may conflict, nananalo ang English na bersyon, maliban kung iba ang sabi ng batas.</p>
      <p>19.10 <strong>Electronic communications.</strong> Sumasang-ayon kang tumanggap ng komunikasyon mula sa amin nang electronic (in-app notices, push notifications, SMS sa registered number mo, o email kung saan ibinigay), at na ang mga ito ay tumutugon sa anumang legal na requirement para sa nakasulat na komunikasyon.</p>

      <h2 id="s20">20. Contact</h2>
      <p><strong>Deployku Pte Ltd</strong><br />
      Email: <strong><a href="mailto:admin@deployku.com">admin@deployku.com</a></strong></p>
      <p>Para sa support, appeals, legal notices at infringement claims, gamitin ang email sa itaas at isama ang sapat na detalye para mahanap namin ang Account mo at mahawakan ang kahilingan mo.</p>

      <p class="doc-note">Sa paggamit ng Heqiyou ay kinukumpirma mong nabasa, naunawaan at sumang-ayon ka sa Terms and Conditions na ito at sa kalakip na <a href="privacy.html">Privacy Policy</a>.</p>

    `
};
