window.DK_TRANSLATIONS = window.DK_TRANSLATIONS || {};
window.DK_TRANSLATIONS.ms = {
  _lang: "ms",
  _title: "Terma dan Syarat — Heqiyou · Deployku",
  "eyebrow": "Undang-undang · Heqiyou",
  "h1": "Terma dan Syarat",
  "meta": "<span>Tarikh Berkuat Kuasa: 28 June 2026</span><span>Versi 1.3</span><span>Deployku Pte Ltd · Singapura</span>",
  "intro": `Terma dan Syarat ini ("<strong>Terma</strong>") merupakan perjanjian antara anda dengan <strong>Deployku Pte Ltd</strong>, sebuah syarikat yang didaftarkan di Singapura ("<strong>Deployku</strong>", "<strong>kami</strong>", "<strong>kita</strong>" atau "<strong>milik kami</strong>"). Terma ini merangkumi penggunaan anda terhadap aplikasi Heqiyou dan segala yang terkandung di dalamnya — semua ciri, kandungan, serta laman web dan perkhidmatan berkaitan (secara bersama, "<strong>Service</strong>" (Perkhidmatan) atau "<strong>App</strong>" (Aplikasi)).`,
  "nav.product": "Heqiyou",
  "nav.privacy": "Privasi",
  "nav.terms": "Terma",
  "nav.cta": "Hubungi kami",
  "foot.tagline": `Sebuah studio Singapura yang membina produk yang menggerakkan Asia Tenggara.`,
  "foot.company": "Syarikat",
  "foot.whatwedo": "Apa yang kami lakukan",
  "foot.approach": "Pendekatan",
  "foot.about": "Tentang kami",
  "foot.careers": "Kerjaya",
  "foot.products": "Produk",
  "foot.heqiyou": "Heqiyou",
  "foot.legal": "Undang-undang",
  "foot.privacyLink": "Dasar Privasi",
  "foot.termsLink": "Terma &amp; Syarat",
  "foot.contact": "Hubungi",
  "foot.email": "E-mel",
  "foot.getintouch": "Hubungi kami",
  "foot.copyright": "© 2026 Deployku Pte Ltd. Hak cipta terpelihara.",
  "foot.built": "Dibina di Singapura · untuk Asia Tenggara",
  "body": `

      <p><strong>Sila baca Terma ini. Dengan mencipta akaun atau menggunakan Service, anda bersetuju dengan Terma ini dan dengan <a href="privacy.html">Dasar Privasi</a> kami. Jika anda tidak bersetuju, jangan gunakan Service.</strong></p>

      <div class="notice-card">
        <p><strong>Perkara penting yang perlu diketahui terlebih dahulu:</strong></p>
        <ul>
          <li><strong>Anda mestilah berumur 18 tahun atau lebih untuk menggunakan Service.</strong></li>
          <li><strong>Panggilan suara dirakam dan ditranskripsikan untuk tujuan keselamatan</strong> (lihat Seksyen 8 dan <a href="privacy.html">Dasar Privasi</a>). Membuat atau menyertai panggilan bermakna anda memberi persetujuan terhadap perkara ini. Jika anda tidak bersetuju, jangan gunakan ciri panggilan.</li>
          <li><strong>"Glimpse" membolehkan anda menyiarkan video pendek tentang diri anda.</strong> Dalam paparan penemuan tanpa nama, nama dan profil anda kekal tersembunyi, tetapi <strong>video masih menunjukkan wajah dan penampilan anda</strong>. Dengan menyiarkannya, anda bersetuju bahawa ia boleh disaring dan ditunjukkan kepada khalayak yang anda pilih.</li>
          <li><strong>Credits bukan wang. Ia tidak boleh dikembalikan, dan anda boleh kehilangannya jika anda melanggar Terma ini</strong> (lihat Seksyen 7).</li>
          <li><strong>"Premium" ialah langganan yang diperbaharui dan mengenakan caj kepada anda secara automatik sehingga anda membatalkannya</strong> (lihat Seksyen 6.9).</li>
          <li><strong>Terma ini mengehadkan tanggungjawab undang-undang kami terhadap anda dan termasuk indemniti yang memihak kepada kami</strong> (lihat Seksyen 15–17).</li>
        </ul>
      </div>

      <h2 id="s1">1. Tentang Service</h2>
      <p>1.1 Heqiyou ialah aplikasi temujanji dan sosial yang mengutamakan suara. Daripada meleret melalui foto, anda bertemu orang melalui panggilan suara yang pendek dan tanpa nama ("<strong>Mini-Date</strong>" (Temu Mini)). Nama dan foto kekal tersembunyi semasa panggilan. Hanya jika <strong>kedua-dua</strong> pihak memilih untuk meneruskan selepas itu, profil anda akan didedahkan antara satu sama lain dan sembang peribadi akan dibuka.</p>
      <p>1.2 Service mungkin merangkumi: pendaftaran melalui nombor telefon atau melalui pihak ketiga seperti Apple atau Google; panggilan suara tanpa nama; pemadanan berasaskan giliran; petunjuk keserasian; sembang selepas padanan; panggilan langsung (bukan tanpa nama) antara pengguna yang telah dipadankan; pembantu perancang temujanji AI (yang mungkin mencadangkan kawasan permulaan daripada lokasi peranti anda dan membenarkan anda membuka aplikasi seperti perkhidmatan tempahan kenderaan dengan destinasi telah diisi terlebih dahulu); rakan suara AI; video pendek dengan kapsyen pilihan dan eksport rumusan harian ("<strong>Glimpse</strong>"); hubungan rakan dan ciri komitmen eksklusif ("<strong>Pledge</strong>" (Ikrar)); "diari pasangan" tentang tempat yang dikongsi ("<strong>Places</strong>" (Tempat)); penciptaan profil dan foto; pembelian Credits; langganan <strong>Premium</strong>; dan iklan yang boleh anda tonton untuk mendapatkan ganjaran.</p>
      <p>1.3 Service hanya tersedia di rantau yang kami pilih ("<strong>Supported Regions</strong>" (Rantau Disokong)). Pemadanan dan penemuan Glimpse biasanya terhad kepada orang dalam Supported Region yang sama. Kami boleh menambah, mengeluarkan atau mengubah Supported Regions pada bila-bila masa, tanpa notis.</p>
      <p>1.4 Kami sentiasa menambah baik Service. Kami mungkin menambah, mengubah, menjeda atau mengeluarkan ciri (termasuk yang masih dalam pembangunan, seperti semakan identiti yang lebih kukuh atau pilihan pembayaran baharu), atau menetapkan had pada ciri, pada bila-bila masa dan mengikut budi bicara kami. Jika sesuatu perubahan menjejaskan ciri berbayar secara serius dan negatif, kami akan cuba memberi anda notis terlebih dahulu.</p>
      <p>1.5 <strong>Glimpse.</strong> Glimpse membolehkan anda merakam video pendek (beberapa saat) tentang diri anda, secara pilihan menambah kapsyen ringkas, dan menyiarkannya ke "tetingkap" masa berulang untuk khalayak yang anda pilih: <strong>Hopeful</strong> (penemuan tanpa nama), <strong>Matched</strong> (Dipadankan), <strong>Friends</strong> (Rakan), atau <strong>Pledged</strong> (Berikrar). Video dan kapsyen yang dihantar kepada khalayak Hopeful atau Matched disemak oleh penyederhanaan automatik sebelum ia muncul, dan ditunjukkan dengan glif abstrak dan skor keserasian — bukan nama atau profil anda (walaupun video memang menunjukkan penampilan anda). Video yang dihantar kepada Friends atau pasangan Pledged ditunjukkan dengan nama dan foto anda kepada orang tersebut. Glimpse juga boleh mencantumkan klip sehari (klip anda dan klip rakan/pasangan anda) menjadi video rumusan pendek yang boleh anda simpan atau kongsi. Penyiaran kepada Hopeful atau Matched, dan pengeksportan rumusan, mungkin memerlukan Credits atau disertakan dengan Premium; siaran Friends/Pledged adalah percuma (lihat Seksyen 6).</p>
      <p>1.6 <strong>Connections, Friends dan Pledge.</strong> Anda boleh membentuk hubungan berterusan dengan pengguna lain: <strong>Match</strong> (Padanan) (selepas Mini-Date bersama), <strong>Friend</strong> (Rakan) (ditambah dengan kod rakan peribadi), dan <strong>Pledge</strong> (komitmen eksklusif bersama antara pengguna yang dipadankan, dibentuk dengan kod padanan). Semasa anda berikrar, sesetengah ciri temujanji buta dan pemadanan dimatikan, dan sesetengah ciri hanya berfungsi dengan pasangan Pledged anda. Anda boleh menamatkan mana-mana Connection pada bila-bila masa.</p>
      <p>1.7 <strong>Places (diari pasangan).</strong> Pengguna yang berhubung (dipadankan atau berikrar) boleh menyimpan diari bersama tentang tempat yang pernah mereka kunjungi bersama — termasuk nama dan lokasi tempat, tarikh, foto, kapsyen dan nota yang ditambah oleh mana-mana pihak. Kedua-dua ahli Connection boleh melihat diari tersebut. Menyiarkan sesuatu tempat mungkin memerlukan Credits atau disertakan dengan Premium (lihat Seksyen 6).</p>
      <p>1.8 <strong>Rakan suara AI.</strong> Service mungkin membenarkan anda mengadakan sembang suara langsung dengan rakan AI automatik (bukan orang lain). Ia terhad masa dan mungkin memerlukan Credits.</p>
      <p>1.9 <strong>Mod Ambassador.</strong> Kami mungkin menjemput sesetengah pengguna ke mod "ambassador" pilihan yang membantu menyemai giliran pemadanan. Jika anda menghidupkannya, sesetengah panggilan anda mungkin ditandakan supaya ia dikecualikan daripada metrik tertentu, dan panggilan yang anda mulakan dalam mod ini mungkin tidak mengenakan Credits kepada anda. Kami boleh memberi, mengubah atau mengeluarkan kelayakan ambassador mengikut budi bicara kami.</p>

      <h2 id="s2">2. Definisi</h2>
      <p>Dalam Terma ini:</p>
      <ul>
        <li>"<strong>Account</strong>" (Akaun) bermaksud akaun yang anda daftarkan dengan Service.</li>
        <li>"<strong>Content</strong>" (Kandungan) bermaksud apa-apa data, teks, audio, suara, video, imej, foto, profil, mesej, transkrip, penilaian, laporan, entri tempat atau bahan lain dalam Service.</li>
        <li>"<strong>User Content</strong>" (Kandungan Pengguna) bermaksud Content yang anda berikan — profil anda, foto, <strong>video Glimpse</strong>, <strong>entri diari pasangan (tempat, foto, kapsyen dan nota)</strong>, suara anda semasa panggilan, dan mesej sembang.</li>
        <li>"<strong>Credits</strong>" (Kredit) bermaksud unit dalam aplikasi yang digunakan untuk membayar ciri tertentu (lihat Seksyen 6).</li>
        <li>"<strong>Premium</strong>" bermaksud langganan berbayar yang diperbaharui secara automatik yang membuka kunci ciri tertentu dan/atau menghapuskan caj Credit tertentu (lihat Seksyen 6.9).</li>
        <li>"<strong>Mini-Date</strong>" bermaksud panggilan suara tanpa nama dan terhad masa antara dua pengguna yang disediakan oleh sistem pemadanan kami.</li>
        <li>"<strong>Direct Call</strong>" (Panggilan Langsung) bermaksud panggilan suara bukan tanpa nama antara pengguna yang telah dipadankan.</li>
        <li>"<strong>Match</strong>" bermaksud keadaan apabila kedua-dua pengguna memilih untuk meneruskan selepas Mini-Date, supaya profil mereka didedahkan antara satu sama lain.</li>
        <li>"<strong>Glimpse</strong>" atau "<strong>Glimpse Clip</strong>" (Klip Glimpse) bermaksud video pendek tentang diri anda yang anda siarkan.</li>
        <li>"<strong>Connection</strong>" (Hubungan) bermaksud pautan berterusan antara dua pengguna — Match, Friend, atau Pledge.</li>
        <li>"<strong>Friend</strong>" bermaksud hubungan bukan romantik yang ditambah melalui kod rakan.</li>
        <li>"<strong>Pledge</strong>" bermaksud komitmen eksklusif bersama antara dua pengguna yang dipadankan.</li>
        <li>"<strong>Places</strong>" atau "<strong>Couple Diary</strong>" (Diari Pasangan) bermaksud diari bersama tempat sesuatu Connection merekodkan tempat, foto, kapsyen dan nota.</li>
        <li>"<strong>Marks</strong>" (Tanda) bermaksud nama "Heqiyou", logo, tanda perkataan, dan semua penjenamaan serta reka bentuk berkaitan.</li>
        <li>"<strong>Virtual Items</strong>" (Item Maya) bermaksud Credits, faedah Premium dan apa-apa barangan atau ciri maya lain dalam Service.</li>
      </ul>

      <h2 id="s3">3. Siapa Yang Boleh Menggunakan Service</h2>
      <p>3.1 <strong>Anda mestilah berumur 18+.</strong> Anda mestilah berumur sekurang-kurangnya 18 tahun untuk mencipta Account atau menggunakan Service, dan anda mengesahkan bahawa anda demikian. Kami boleh menutup mana-mana Account yang kami percaya secara munasabah dimiliki oleh seseorang yang berumur bawah 18 tahun, tanpa bayaran balik, dan kami boleh meminta bukti umur pada bila-bila masa.</p>
      <p>3.2 <strong>Anda dibenarkan untuk bersetuju, dan anda mempunyai rekod yang bersih.</strong> Anda mengesahkan bahawa: (a) anda boleh memeterai kontrak ini secara sah; (b) tiada apa-apa dalam undang-undang di tempat anda tinggal yang menghalang anda daripada menggunakan Service; (c) anda tidak pernah disabitkan dengan, dan tidak menghadapi pertuduhan bagi, jenayah serius, kesalahan seksual, atau apa-apa jenayah yang melibatkan keganasan atau ancaman keganasan; dan (d) anda tidak dikehendaki mendaftar sebagai pesalah seks di mana-mana.</p>
      <p>3.3 <strong>Di mana anda boleh menggunakannya.</strong> Service hanya untuk kegunaan di Supported Regions. Jangan gunakannya — atau cuba memintas had serantau (sebagai contoh dengan VPN, lokasi palsu, atau butiran pendaftaran palsu) — dari luar Supported Region.</p>
      <p>3.4 <strong>Satu akaun setiap orang.</strong> Anda hanya boleh mempunyai satu Account, untuk kegunaan peribadi dan bukan komersial anda sendiri. Jangan mencipta atau mengendalikan Account untuk orang lain, organisasi, atau bot.</p>
      <p>3.5 <strong>Tiada kembali selepas larangan.</strong> Jika kami pernah menggantung, melarang atau mengeluarkan anda sebelum ini, jangan mencipta Account baharu melainkan kami memberi anda kebenaran bertulis.</p>

      <h2 id="s4">4. Account Anda</h2>
      <p>4.1 <strong>Mendaftar.</strong> Untuk menggunakan Service, anda mendaftar dengan nombor mudah alih yang sah yang boleh menerima kod sekali guna, atau dengan log masuk menggunakan penyedia yang disokong seperti Apple atau Google. Nombor telefon yang disahkan kekal sebagai identiti utama anda bagi sesetengah ciri. Anda akan melalui proses pengenalan — memberikan nama atau nama paparan, tarikh lahir, jantina, bandar, dan beberapa keutamaan anda. Anda juga boleh menambah alamat e-mel dan foto profil.</p>
      <p>4.2 <strong>Pastikan ia tepat.</strong> Berikan kami maklumat yang benar, terkini dan lengkap, termasuk tarikh lahir sebenar anda, dan kemas kini ia. Berbohong tentang umur, identiti atau butiran pendaftaran lain anda merupakan pelanggaran serius terhadap Terma ini.</p>
      <p>4.3 <strong>Pastikan ia selamat.</strong> Anda bertanggungjawab atas segala-galanya yang berlaku pada Account anda dan untuk melindungi peranti serta nombor telefon anda. Beritahu kami segera di <strong><a href="mailto:admin@deployku.com">admin@deployku.com</a></strong> jika anda fikir seseorang telah mengakses Account anda tanpa kebenaran.</p>
      <p>4.4 <strong>Pengesahan.</strong> Kami mungkin meminta anda mengesahkan identiti, umur, telefon, foto atau "kehidupan" (liveness) anda (termasuk melalui penyedia pengesahan luar) sebelum atau semasa anda menggunakan Service, atau untuk membuka kunci ciri tertentu (seperti menerima panggilan). Jika anda tidak melengkapkan semakan yang diperlukan, akses anda mungkin dihadkan atau digantung.</p>
      <p>4.5 <strong>Semakan foto dan video.</strong> Foto dan video Glimpse yang anda muat naik mungkin disemak oleh sistem automatik dan/atau orang sebelum ia muncul. Kami boleh menolak, mengeluarkan atau enggan menunjukkan mana-mana foto atau video mengikut budi bicara kami — sebagai contoh jika ia menunjukkan kebogelan, senjata, dadah, atau bahan yang menyinggung, atau tidak menunjukkan diri anda.</p>
      <p>4.6 <strong>Kebenaran peranti.</strong> Sesetengah ciri memerlukan kebenaran peranti — sebagai contoh mikrofon (panggilan dan rakan AI), kamera (Glimpse dan foto), pustaka foto (muat naik), dan secara pilihan lokasi (untuk mencadangkan kawasan perancangan temujanji, membantu anda menandakan tempat berdekatan, atau menengahkan peta). Kami hanya membaca lokasi anda apabila anda menggunakan ciri sedemikian; kami tidak menjejakinya di latar belakang. Anda boleh menguruskan kebenaran dalam tetapan peranti anda; mematikan salah satunya mungkin melumpuhkan ciri pemadanan tersebut.</p>

      <h2 id="s5">5. Pemadanan, Kualiti dan Keadilan</h2>
      <p>5.1 <strong>Bagaimana pemadanan berfungsi.</strong> Sistem kami memadankan pengguna berdasarkan perkara yang mungkin termasuk keutamaan anda, sejauh mana lengkap profil anda, petunjuk keserasian daripada jawapan pengenalan anda, rantau anda, berapa lama anda telah menunggu, dan skor kualiti, reputasi serta keserasian dalaman. Pemadanan adalah berasaskan algoritma dan mengikut budi bicara kami, dan <strong>kami tidak menjamin sebarang padanan tertentu, bilangan padanan, kekerapan panggilan, atau hasil — sama ada romantik atau sebaliknya.</strong></p>
      <p>5.2 <strong>Skor dalaman.</strong> Untuk memastikan keadaan selamat dan seimbang, kami menyimpan metrik dalaman dan peribadi untuk Accounts — seperti skor reputasi (dipengaruhi oleh penilaian selepas panggilan dan laporan) dan skor kualiti padanan (dipengaruhi oleh hasil panggilan). Kami menggunakan ini untuk pemadanan, kelayakan, pengehadan kadar dan keselamatan. Ia bukan penilaian terhadap anda sebagai seorang individu, tidak ditunjukkan kepada pengguna lain, dan bukan janji daripada kami.</p>
      <p>5.3 <strong>Kelayakan dan had.</strong> Sesetengah ciri (seperti menyertai giliran menerima) mungkin memerlukan perkara seperti nombor telefon yang disahkan, profil yang lengkap, foto atau avatar sistem yang diluluskan, kedudukan yang baik, pengesahan yang selesai, dan kekal dalam had penggunaan (sebagai contoh had bulanan bagi panggilan yang diterima, atau had harian bagi tindakan tertentu). Kami boleh mengubah keperluan dan had ini pada bila-bila masa.</p>
      <p>5.4 <strong>Kekal tanpa nama sebelum pendedahan.</strong> Semasa Mini-Date, profil ditunjukkan sebagai avatar abstrak. Jangan cuba mengalahkan ketanpanamaan — sebagai contoh dengan memberikan atau meminta nama sebenar, foto, pemegangan media sosial, nombor telefon, atau butiran hubungan atau pengenalan lain semasa Mini-Date.</p>
      <p>5.5 <strong>Pendedahan bersama.</strong> Profil dan sembang hanya dibuka kunci jika kedua-dua orang memilih untuk meneruskan selepas Mini-Date. Keputusan untuk tidak meneruskan adalah muktamad bagi panggilan tersebut, dan kami tidak mendedahkannya dengan cara yang bertujuan memalukan sesiapa.</p>
      <p>5.6 <strong>Penemuan Glimpse.</strong> Apabila anda menyiarkan Glimpse, anda faham bahawa: (a) video dan kapsyen yang dihantar kepada <strong>Hopeful</strong> atau <strong>Matched</strong> disemak oleh penyederhanaan automatik terlebih dahulu dan mungkin ditolak; (b) dalam <strong>Hopeful</strong>, video anda ditunjukkan kepada kumpulan pengguna layak yang disusun mengikut keserasian dalam rantau anda bagi tetingkap tersebut — nama dan profil anda tersembunyi, tetapi <strong>video menunjukkan penampilan anda</strong>; (c) dalam <strong>Matched</strong>, <strong>Friends</strong> dan <strong>Pledged</strong>, video anda ditunjukkan dengan nama dan foto anda kepada orang yang telah anda hubungi; (d) rumusan harian yang anda cipta mungkin menggabungkan klip anda dengan klip yang dikongsi oleh rakan/pasangan anda; dan (e) anda tidak boleh menyiarkan Glimpse yang menunjukkan sesiapa selain diri anda tanpa persetujuan mereka, atau yang melanggar Seksyen 9.</p>

      <h2 id="s6">6. Credits, Pembelian, Langganan dan Pengebilan</h2>
      <p>6.1 <strong>Apakah itu Credits.</strong> Credits ialah lesen terhad, peribadi dan tidak boleh dipindah milik untuk menggunakan ciri tertentu — dan kami boleh membatalkannya. <strong>Credits bukan wang. Ia tiada nilai tunai, tidak memperoleh faedah, dan tidak boleh ditebus, ditukar atau ditunaikan untuk apa-apa yang bernilai di luar Service.</strong> Anda tidak boleh menjual, menukar, menghadiahkan, memindahkan atau menggabungkan Credits.</p>
      <p>6.2 <strong>Bagaimana anda memperoleh Credits.</strong> Anda boleh memperoleh Credits dengan: (a) membeli pakej Credit melalui pembelian dalam aplikasi pada harga yang ditunjukkan semasa anda membeli; (b) pemberian promosi atau percuma (seperti bonus pendaftaran), mengikut budi bicara kami; (c) menonton iklan berganjaran di mana ditawarkan, dalam had yang kami tetapkan; dan (d) apa-apa kaedah lain yang kami tambah. Kami boleh mengubah harga Credit, saiz pakej, peraturan perolehan, kos ciri dan had pada bila-bila masa; perubahan hanya terpakai pada masa hadapan dan tidak menjejaskan Credits yang sudah ada dalam baki anda.</p>
      <p>6.3 <strong>Bagaimana Credits dibelanjakan.</strong> Ciri yang menggunakan Credits — seperti memulakan Mini-Dates, memulakan Direct Calls, menjana pelan temujanji AI, menggunakan rakan suara AI, menyiarkan Glimpse kepada khalayak berbayar (Hopeful atau Matched), mengeksport rumusan Glimpse, dan menyiarkan tempat ke diari pasangan — mengenakan jumlah yang ditunjukkan dalam App semasa anda menggunakannya. Sesetengah daripadanya mungkin percuma dengan langganan Premium yang aktif, dan sesetengah khalayak Glimpse (Friends dan Pledged) sentiasa percuma. Bagi panggilan bermasa, Credits mungkin ditahan apabila panggilan bermula dan diselesaikan berdasarkan berapa lama anda sebenarnya disambungkan. Jika panggilan tamat lebih awal daripada yang ditempah, anda mungkin dikenakan caj secara berkadar, dan jika panggilan gagal disambungkan kerana kesilapan di pihak kami, kami secara amnya akan melepaskan atau mengembalikan Credits yang ditahan.</p>
      <p>6.4 <strong>Pembayaran dan peraturan gedung aplikasi.</strong> Pembelian dalam aplikasi dan langganan dikendalikan oleh gedung aplikasi tempat anda memuat turun dan/atau penyedia pembayaran kami, dan juga tertakluk kepada terma mereka. Kami tidak menyimpan butiran penuh kad anda. Kami mungkin menambah kaedah pembayaran lain kemudian, dengan terma tersendiri yang ditunjukkan semasa pembelian.</p>
      <p>6.5 <strong>Tiada bayaran balik.</strong> <strong>Kecuali di mana undang-undang atau peraturan gedung aplikasi sendiri mengkehendakinya, semua pembelian Credits dan langganan adalah muktamad dan tidak boleh dikembalikan</strong> — termasuk Credits yang tidak digunakan, bahagian langganan yang tidak digunakan, dan kes di mana akaun anda ditutup, digantung atau ditamatkan, atau Service dihentikan. Jika kami memilih untuk memberi anda bayaran balik atau kredit pada satu masa, itu tidak bermakna kami akan melakukannya lagi.</p>
      <p>6.6 <strong>Tamat tempoh.</strong> Credits pada masa ini tidak tamat tempoh, tetapi kami mungkin menambah peraturan tamat tempoh atau ketidakaktifan yang munasabah untuk Credits percuma/promosi, dan — dengan notis awal yang munasabah — untuk Credits yang dibeli, di mana undang-undang membenarkan.</p>
      <p>6.7 <strong>Jangan menipu sistem.</strong> Jangan: (a) memperoleh Credits, faedah Premium atau Virtual Items lain melalui penipuan, pepijat, bot, atau penyalahgunaan mekanik promo/iklan/rujukan; (b) memulakan tuntutan caj balik atau pembalikan pembayaran yang tidak jujur; atau (c) membeli atau menjual Credits, langganan atau Accounts di luar Service. Apa-apa yang diperoleh dengan melanggar peraturan ini adalah terbatal.</p>
      <p>6.8 <strong>Rekod kami.</strong> Rekod kami (termasuk lejar transaksi dan rekod kelayakan kami) adalah, melainkan terdapat kesilapan yang jelas, kata muktamad terhadap baki Credit, status langganan dan transaksi anda.</p>
      <p>6.9 <strong>Langganan Premium (diperbaharui secara automatik).</strong> Premium ialah langganan yang diperbaharui secara automatik yang dijual melalui gedung aplikasi.</p>
      <ul>
        <li><strong>Pembaharuan automatik.</strong> Anda dikenakan caj melalui akaun gedung aplikasi anda apabila anda membeli. <strong>Ia diperbaharui secara automatik bagi setiap tempoh baharu pada harga semasa melainkan anda membatalkannya sekurang-kurangnya 24 jam sebelum tempoh semasa tamat</strong> (atau sebagaimana yang dikehendaki oleh gedung aplikasi).</li>
        <li><strong>Menguruskan dan membatalkan.</strong> Anda boleh menguruskan atau membatalkan pada bila-bila masa dalam tetapan langganan gedung aplikasi anda. Memadam App <strong>tidak</strong> membatalkannya. Pembatalan berkuat kuasa pada akhir tempoh berbayar semasa, dan anda mengekalkan Premium sehingga ketika itu.</li>
        <li><strong>Perubahan harga.</strong> Kami mungkin mengubah harga; perubahan terpakai pada tempoh masa hadapan dan diberitahu mengikut peraturan gedung aplikasi, yang mungkin memerlukan persetujuan anda terlebih dahulu.</li>
        <li><strong>Percubaan percuma / promosi.</strong> Jika percubaan percuma atau promosi ditawarkan, ia secara automatik menjadi langganan berbayar melainkan anda membatalkannya sebelum ia tamat; apa-apa bahagian percubaan yang tidak digunakan akan dilucutkan apabila anda melanggan, di mana berkenaan.</li>
        <li><strong>Faedah.</strong> Faedah Premium (seperti menyiarkan Glimpse atau tempat tanpa caj Credit, lebih banyak sejarah, atau ciri lain) adalah sebahagian daripada lesen anda untuk menggunakan Service, bukan harta, mungkin berubah, dan tamat apabila langganan anda tamat atau dibatalkan.</li>
      </ul>
      <p>6.10 <strong>Terma Apple / Google.</strong> Di mana gedung aplikasi mengkehendakinya, lesen dan terma langganan standardnya juga terpakai, dan pengendali gedung aplikasi mungkin menjadi benefisiari pihak ketiga yang boleh menguatkuasakan Terma ini (lihat Seksyen 14.3).</p>

      <h2 id="s7">7. Kehilangan Credits; Penggantungan dan Penamatan oleh Kami</h2>
      <p>7.1 <strong>Anda boleh kehilangan Credits jika anda melanggar peraturan.</strong> <strong>Jika anda melanggar Terma ini — termasuk peraturan kelakuan dalam Seksyen 9, peraturan pengebilan dalam Seksyen 6.7, atau peraturan kelayakan dalam Seksyen 3 — kami boleh membatalkan dan melucutkan mana-mana atau semua Credits anda (yang dibeli, diperoleh atau percuma) dan membatalkan faedah Premium, tanpa bayaran balik atau pampasan, sebagai tambahan kepada apa-apa tindakan lain yang kami ambil.</strong> Kami boleh melakukan ini dengan atau tanpa amaran, tempoh sejuk, penggantungan atau larangan yang berasingan.</p>
      <p>7.2 <strong>Bila kami mungkin bertindak.</strong> Kami mungkin memberi amaran kepada anda, menyekat ciri, mengenakan tempoh sejuk, menggantung atau melarang Account anda secara kekal, dan/atau melucutkan Credits, jika kami percaya secara munasabah anda telah: (a) melanggar Terma ini atau apa-apa dasar yang dirujuk olehnya; (b) melakukan penipuan, penyalahgunaan pembayaran atau penyalahgunaan caj balik; (c) mengganggu, mengancam, mencederakan atau membahayakan mana-mana pengguna atau kakitangan kami; (d) berbohong tentang umur atau identiti anda; (e) menggunakan Service untuk pujukan komersial, promosi atau penipuan; (f) mencipta Accounts berbilang atau yang mengelak larangan; atau (g) sebaliknya bertindak dengan cara yang menimbulkan risiko atau kemungkinan pendedahan undang-undang kepada kami, pengguna lain, atau pihak ketiga.</p>
      <p>7.3 <strong>Apa yang berlaku jika kami menamatkan.</strong> Jika kami menggantung atau menamatkan Account anda: (a) hak anda untuk menggunakan Service tamat serta-merta (atau bagi tempoh penggantungan); (b) <strong>semua Credits dilucutkan tanpa bayaran balik</strong>, setakat yang dibenarkan undang-undang; (c) faedah Premium berhenti (apa-apa pembatalan atau bayaran balik langganan dikendalikan oleh gedung aplikasi di bawah peraturannya); dan (d) bahagian Terma ini yang sepatutnya terus terpakai (termasuk Seksyen 6.5, 7, 10, 11, 14–19) berterusan.</p>
      <p>7.4 <strong>Rayuan.</strong> Jika anda fikir kami melakukan tindakan penguatkuasaan secara silap, e-mel <strong><a href="mailto:admin@deployku.com">admin@deployku.com</a></strong>. Kami akan menyemak rayuan yang sahih tetapi tidak perlu memulihkan mana-mana Account, Credits atau faedah.</p>
      <p>7.5 <strong>Menutup akaun anda sendiri.</strong> Anda boleh berhenti menggunakan Service dan memadam Account anda pada bila-bila masa dalam tetapan App atau dengan menghantar e-mel ke <strong><a href="mailto:admin@deployku.com">admin@deployku.com</a></strong>. Memadam Account anda melucutkan apa-apa baki Credits tanpa bayaran balik (melainkan undang-undang menyatakan sebaliknya) dan <strong>tidak</strong> dengan sendirinya membatalkan langganan yang diperbaharui secara automatik — batalkan itu melalui gedung aplikasi anda. Cara kami mengendalikan data anda semasa pemadaman dinyatakan dalam <a href="privacy.html">Dasar Privasi</a>.</p>

      <h2 id="s8">8. Rakaman Panggilan, Video, Transkripsi dan Pemantauan</h2>
      <p>8.1 <strong>Anda bersetuju dengan rakaman.</strong> Untuk melindungi semua orang, <strong>panggilan suara dalam Service (Mini-Dates dan Direct Calls) dirakam dan ditranskripsikan secara automatik.</strong> App memberitahu anda tentang ini sebelum setiap panggilan. <strong>Dengan memulakan atau menyertai panggilan, anda bersetuju — dan mengesahkan bahawa anda mempunyai hak untuk bersetuju — terhadap panggilan tersebut dirakam, ditranskripsikan, dianalisis dan disemak untuk tujuan keselamatan.</strong> Jika anda tidak bersetuju, jangan gunakan ciri panggilan.</p>
      <p>8.2 <strong>Apa yang kami lakukan dengan rakaman.</strong> Seperti yang dijelaskan dalam <a href="privacy.html">Dasar Privasi</a>: audio mentah digunakan untuk membuat transkrip dan dipadam segera selepas itu; transkrip (dengan label penutur automatik dan rumusan) disimpan dan hanya tersedia kepada peserta panggilan dan kepada kakitangan yang diberi kuasa untuk tujuan keselamatan, penyederhanaan, pencegahan penipuan dan pematuhan undang-undang.</p>
      <p>8.3 <strong>Keselamatan dan pengalaman.</strong> Kami mungkin menyemak dan menggunakan rakaman, transkrip, mesej sembang, video Glimpse dan kandungan diari pasangan untuk menyiasat laporan, mengesan dan menghentikan penyalahgunaan, menguatkuasakan Terma ini, mematuhi undang-undang, melindungi pengguna, dan menambah baik pengalaman anda — semuanya selaras dengan Dasar Privasi.</p>
      <p>8.4 <strong>Kandungan Glimpse dan diari.</strong> Video Glimpse dan entri diari disaring dan/atau mungkin disemak untuk tujuan keselamatan. Video Glimpse disimpan dan dihantar melalui pautan yang selamat dan ditandatangani serta hanya ditunjukkan kepada khalayak yang diterangkan dalam Seksyen 1.5 dan 5.6. Anda bertanggungjawab atas apa yang anda rakam dan siarkan.</p>
      <p>8.5 <strong>Jangan merakam pengguna lain.</strong> Jangan merakam, menangkap, menangkap skrin, menyiarkan atau sebaliknya menyalin panggilan, suara, video Glimpse, sembang, entri diari atau profil pengguna lain — dengan apa-apa cara, termasuk peranti luar — tanpa persetujuan jelas pengguna tersebut dan kami. Berbuat demikian merupakan pelanggaran serius terhadap Terma ini.</p>

      <h2 id="s9">9. Peraturan Komuniti</h2>
      <p>9.1 Berkaitan dengan Service, anda bersetuju <strong>tidak</strong> akan:</p>
      <ul>
        <li>mengganggu, menyalahgunakan, mengintai, menggertak, mengancam, memfitnah atau mencederakan sesiapa, atau menggalakkan orang lain berbuat demikian;</li>
        <li>menggunakan ucapan kebencian, atau mendiskriminasi berdasarkan bangsa, etnik, kewarganegaraan, agama, jantina, identiti jantina, orientasi seksual, kecacatan, atau apa-apa ciri yang dilindungi lain;</li>
        <li>berkongsi kandungan — dalam panggilan, video Glimpse, foto, entri diari atau sembang — yang lucah secara seksual, keji, lucah, ganas atau sebaliknya tidak menyenangkan, atau mendedahkan sesiapa kepada kandungan sedemikian tanpa persetujuan;</li>
        <li>merakam atau menyiarkan Glimpse, foto atau entri diari yang menunjukkan sesiapa selain diri anda tanpa persetujuan mereka, atau yang sebenarnya bukan diri anda;</li>
        <li>berbohong tentang identiti, umur, foto, video atau gabungan anda, menyamar sebagai sesiapa, atau menjalankan profil palsu, pendua atau "catfishing";</li>
        <li>meminta mana-mana pengguna untuk wang, hadiah, derma, maklumat kewangan, kata laluan atau kod sekali guna, atau menjalankan apa-apa penipuan, penipuan percintaan, skim piramid atau pujukan komersial;</li>
        <li>mengiklankan, mempromosikan atau menjual apa-apa, atau menggunakan Service untuk apa-apa tujuan komersial, tanpa persetujuan bertulis kami;</li>
        <li>berkongsi atau meminta maklumat pengenalan atau hubungan semasa panggilan tanpa nama, atau sebaliknya memintas reka bentuk ketanpanamaan dan pendedahan;</li>
        <li>menyalahgunakan ciri Connection — sebagai contoh dengan berkongsi atau menuai kod rakan/padanan untuk spam, atau menyalahgunakan Pledge untuk mengganggu atau menipu;</li>
        <li>berkongsi maklumat peribadi seseorang tanpa persetujuan mereka ("doxxing"), termasuk lokasi dalam diari pasangan;</li>
        <li>menggunakan Service jika anda berumur bawah 18 tahun, atau berinteraksi dengannya bagi pihak sesiapa yang berumur bawah 18 tahun;</li>
        <li>menghantar virus, perisian hasad atau apa-apa kod yang berbahaya atau mengganggu;</li>
        <li>mengikis, merangkak, menuai atau mengumpul data tentang pengguna lain (termasuk video Glimpse atau profil), atau mengakses Service dengan cara automatik (bot, skrip, emulator) untuk apa-apa tujuan;</li>
        <li>menyiasat, mengimbas atau menguji keselamatan, atau merosakkan, memintas atau mengalahkan, apa-apa langkah keselamatan, pengehadan kadar, anti-penipuan, penyederhanaan atau log masuk;</li>
        <li>kejuruteraan balikan, menyahkompil, menyahhimpun, mengubah suai atau membuat kerja terbitan App atau Service, kecuali di mana undang-undang tidak membenarkan sekatan tersebut;</li>
        <li>menggunakan Service untuk membina produk yang bersaing, atau menyalin mana-mana ciri, fungsi, antara muka atau grafiknya;</li>
        <li>mengeksploitasi pepijat, memanipulasi pemadanan, penilaian, kedudukan atau sistem ganjaran, atau menyalahgunakan promosi; atau</li>
        <li>menggunakan Service dengan melanggar mana-mana undang-undang.</li>
      </ul>
      <p>9.2 <strong>Pelaporan.</strong> App membenarkan anda melaporkan dan menyekat pengguna lain sebelum, semasa dan selepas panggilan, dalam sembang, dan pada kandungan Glimpse. Sila laporkan apa-apa yang melanggar peraturan ini. Laporan melalui penyederhanaan kami, yang termasuk semakan manusia. Memfailkan laporan yang palsu atau berniat jahat dengan pengetahuan sendiri adalah pelanggaran Terma ini.</p>
      <p>9.3 <strong>Kami boleh bertindak, tetapi tidak perlu memantau segala-galanya.</strong> Kami tidak berjanji untuk memantau semua Content, tetapi kami mungkin (sepenuhnya mengikut budi bicara kami) menyemak, menyaring, menyederhana, mengeluarkan atau menolak apa-apa Content, dan mengambil tindakan di bawah Seksyen 7, pada bila-bila masa dan tanpa notis.</p>

      <h2 id="s10">10. Content Anda dan Lesen Yang Anda Berikan Kepada Kami</h2>
      <p>10.1 <strong>Anda memiliki Content anda.</strong> Anda mengekalkan apa-apa hak pemilikan yang anda miliki dalam User Content anda.</p>
      <p>10.2 <strong>Lesen yang anda berikan kepada kami.</strong> Dengan menyerahkan User Content (profil anda, foto, video Glimpse, entri diari, suara semasa panggilan, dan mesej sembang), anda memberikan Deployku lesen di seluruh dunia, tidak eksklusif, bebas royalti, boleh disublesenkan (kepada penyedia perkhidmatan kami) dan boleh dipindahkan untuk menghos, menyimpan, menyalin, memproses, menyesuaikan, menranskripsikan, menganalisis, memaparkan dan mengedarkannya — hanya untuk: (a) menjalankan, menyediakan, mengamankan dan menambah baik Service; (b) menunjukkan profil, video Glimpse, entri diari dan mesej anda kepada pengguna sebagaimana Service direka (sebagai contoh selepas pendedahan, kepada khalayak Glimpse anda, atau kepada pasangan yang berhubung); (c) mengendalikan penyederhanaan, keselamatan, pencegahan penipuan dan penguatkuasaan; dan (d) mematuhi undang-undang. Lesen ini berkekalan selagi kami menyimpan Content tersebut di bawah <a href="privacy.html">Dasar Privasi</a>, dan terus berkuat kuasa selepas penamatan setakat itu.</p>
      <p>10.3 <strong>Data tanpa nama dan teragregat.</strong> Kami mungkin mencipta dan menggunakan data tanpa nama, dinyahkenal atau teragregat daripada Content dan aktiviti anda — data yang tidak lagi boleh mengenal pasti anda secara munasabah — untuk apa-apa tujuan yang sah, termasuk menambah baik pemadanan, keselamatan, ciri dan pengalaman keseluruhan.</p>
      <p>10.4 <strong>Janji anda tentang Content anda.</strong> Anda mengesahkan bahawa: (a) anda mempunyai semua hak yang diperlukan untuk menyerahkan User Content anda dan memberikan lesen di atas; (b) User Content anda (termasuk foto, video Glimpse dan suara anda) menunjukkan dan adalah milik anda, dan tidak termasuk mana-mana orang lain yang boleh dikenal pasti tanpa persetujuan mereka; dan (c) ia tidak dan tidak akan melanggar atau mencabuli hak harta intelek, privasi, publisiti atau hak lain sesiapa, atau apa-apa undang-undang.</p>
      <p>10.5 <strong>Maklum balas.</strong> Jika anda menghantar kami cadangan atau idea tentang Service, kami boleh menggunakannya secara bebas, selama-lamanya, tanpa sekatan atau bayaran kepada anda.</p>

      <h2 id="s11">11. Harta Intelek dan Tanda Dagangan</h2>
      <p>11.1 <strong>Kami memiliki Service.</strong> Service — App, perisiannya, kod, seni bina, pangkalan data, algoritma, sistem pemadanan dan pemarkahan, avatar yang dijana dan reka bentuk glif, output AI yang disampaikan oleh Service, antara muka, reka bentuk, teks, grafik, audio dan segala-galanya yang lain (kecuali User Content) — adalah milik atau dilesenkan oleh Deployku, dan dilindungi oleh undang-undang hak cipta, tanda dagangan, rahsia dagangan dan undang-undang lain. Apa-apa hak yang tidak kami berikan secara nyata kepada anda adalah terpelihara.</p>
      <p>11.2 <strong>Lesen anda untuk menggunakannya.</strong> Tertakluk kepada Terma ini, kami memberikan anda lesen peribadi, terhad, tidak eksklusif, tidak boleh dipindah milik, tidak boleh disublesenkan dan boleh dibatalkan untuk memuat turun dan menggunakan App pada peranti yang anda miliki atau kawal, untuk kegunaan peribadi dan bukan komersial anda sendiri.</p>
      <p>11.3 <strong>Tanda dagangan, termasuk permohonan yang belum selesai.</strong> "Heqiyou", logo Heqiyou dan Marks kami yang lain adalah tanda dagangan Deployku Pte Ltd. <strong>Permohonan tanda dagangan untuk "Heqiyou" sedang diperiksa oleh Pejabat Harta Intelek Singapura (IPOS). Hakikat bahawa permohonan ini masih belum selesai tidak mengurangkan, mengetepikan atau menjejaskan mana-mana hak Deployku dalam Marks — termasuk hak tidak berdaftar dan hak common-law, hak dalam pelanggaran tort lulus, hak cipta dalam karya seni logo, dan hak yang berkuat kuasa apabila pendaftaran (yang, jika diberikan, terpakai dari tarikh pemfailan permohonan).</strong> Terma ini tidak memberi anda apa-apa hak dalam Marks. Jangan gunakan, daftarkan, atau cuba mendaftarkan mana-mana Marks kami, atau apa-apa nama, logo, domain, pemegangan media sosial atau pengecam aplikasi yang serupa secara mengelirukan, di mana-mana sahaja di dunia. Semua muhibah daripada apa-apa penggunaan Marks adalah milik Deployku.</p>
      <p>11.4 <strong>Tuntutan pelanggaran.</strong> Jika anda percaya Content pada Service melanggar hak cipta atau hak lain anda, beritahu kami di <strong><a href="mailto:admin@deployku.com">admin@deployku.com</a></strong> dengan butiran yang mencukupi (karya, bahan yang melanggar, butiran hubungan anda, dan pernyataan suci hati). Kami akan menyemak dan bertindak ke atas notis yang sah sebagaimana yang dikehendaki undang-undang.</p>

      <h2 id="s12">12. Ciri AI</h2>
      <p>12.1 <strong>Apa yang dikuasakan AI.</strong> Service termasuk ciri AI: transkripsi automatik dan rumusan panggilan, perancang temujanji AI yang mencadangkan itinerari daripada input yang anda dan padanan anda berikan, rakan suara AI yang boleh anda ajak berbual, dan penyederhanaan kandungan automatik. Pemprosesan AI mungkin dilakukan oleh penyedia AI pihak ketiga bagi pihak kami, seperti yang diterangkan dalam <a href="privacy.html">Dasar Privasi</a>.</p>
      <p>12.2 <strong>Jangan bergantung pada output AI.</strong> Output AI (pelan temujanji, cadangan tempat, transkrip, rumusan, balasan rakan, petunjuk keserasian) adalah <strong>cadangan automatik, disediakan "sebagaimana adanya" hanya untuk kemudahan</strong>. Ia mungkin salah, tidak lengkap atau lapuk. Kami tidak mengesahkan tempat, waktu operasi, harga, butiran pengangkutan dan seumpamanya. Terpulang kepada anda untuk menyemak output AI sebelum bergantung padanya, dan untuk menjaga keputusan dan keselamatan anda sendiri.</p>
      <p>12.3 <strong>Tempat pihak ketiga.</strong> Kami tidak berkaitan dengan, dan tidak bertanggungjawab atas, mana-mana tempat, perniagaan atau lokasi yang dicadangkan oleh ciri AI. Apa-apa yang berlaku antara anda dan tempat tersebut adalah semata-mata antara anda dan mereka.</p>
      <p>12.4 <strong>Rakan suara AI.</strong> Rakan suara AI ialah ejen automatik, bukan orang sebenar, dan penyedia AI memproses perbualan untuk menjana balasan. Jangan bergantung padanya untuk nasihat (perubatan, undang-undang, kewangan, kesihatan mental atau sebaliknya), dan jangan menganggapnya sebagai pengganti bantuan profesional atau hubungan manusia.</p>

      <h2 id="s13">13. Keselamatan dan Berurusan dengan Pengguna Lain</h2>
      <p>13.1 <strong>Anda bertanggungjawab atas interaksi anda.</strong> Service memperkenalkan orang antara satu sama lain. <strong>Kami tidak menjalankan semakan latar belakang jenayah atau semakan identiti penuh ke atas pengguna</strong>, dan apa-apa semakan yang kami lakukan (seperti telefon, foto atau kehidupan) adalah terhad dan mungkin tidak menangkap maklumat palsu. Kami tidak membuat apa-apa janji tentang identiti, kelakuan, niat, keserasian atau kejujuran mana-mana pengguna.</p>
      <p>13.2 <strong>Berhati-hati.</strong> Anda sahaja yang bertanggungjawab atas cara anda berurusan dengan pengguna lain, dalam talian dan terutamanya luar talian. Ambil langkah berjaga-jaga akal sehat: berjumpa di tempat awam, beritahu seseorang ke mana anda pergi, jangan kongsi maklumat kewangan atau menghantar wang, berhati-hati tentang berkongsi lokasi tepat (termasuk dalam diari pasangan), dan jangan bergantung hanya pada isyarat dalam aplikasi. Petua keselamatan dalam aplikasi adalah untuk kemudahan dan bukan jaminan keselamatan.</p>
      <p>13.3 <strong>Kami tidak bertanggungjawab atas pengguna lain.</strong> Setakat yang dibenarkan undang-undang, Deployku tidak bertanggungjawab atau berliabiliti atas kelakuan mana-mana pengguna, dalam talian atau luar talian, atau atas apa-apa kerugian, kecederaan atau kerosakan daripada interaksi antara pengguna — termasuk pertemuan yang diatur melalui Service atau perancang temujanji AI-nya.</p>
      <p>13.4 <strong>Kecemasan.</strong> Service bukan perkhidmatan kecemasan. Jika anda fikir anda dalam bahaya, hubungi polis tempatan atau perkhidmatan kecemasan dengan segera.</p>

      <h2 id="s14">14. Perkhidmatan Pihak Ketiga, Iklan dan Gedung Aplikasi</h2>
      <p>14.1 <strong>Penyedia perkhidmatan.</strong> Kami menjalankan Service menggunakan infrastruktur, komunikasi, storan, penyampaian kandungan, peta, pembayaran, pengiklanan, pengesahan, penyederhanaan dan perkhidmatan AI daripada pihak ketiga yang bertindak bagi pihak kami. Cara mereka mengendalikan data peribadi dinyatakan dalam <a href="privacy.html">Dasar Privasi</a>. Kami tidak bertanggungjawab atas gangguan, kesilapan atau tindakan penyedia ini di luar kawalan munasabah kami.</p>
      <p>14.2 <strong>Pengiklanan.</strong> Service mungkin menunjukkan iklan, termasuk iklan berganjaran pilihan. Iklan datang daripada rangkaian iklan pihak ketiga; kami tidak menyokong produk atau perkhidmatan yang diiklankan, dan apa-apa urusan dengan pengiklan adalah semata-mata antara anda dan mereka.</p>
      <p>14.3 <strong>Terma gedung aplikasi.</strong> Muat turun dan penggunaan anda terhadap App, dan apa-apa langganan, juga tertakluk kepada peraturan gedung aplikasi tempat anda memperolehnya. Terma ini adalah antara anda dan Deployku sahaja; pengendali gedung aplikasi bukan pihak kepadanya, tidak perlu menyediakan sokongan untuk App, dan tidak bertanggungjawab atas tuntutan mengenainya. Di mana peraturan gedung aplikasi mengkehendakinya, pengendali tersebut dan sekutunya adalah benefisiari pihak ketiga Terma ini dan boleh menguatkuasakannya terhadap anda.</p>
      <p>14.4 <strong>Pautan dan aplikasi lain.</strong> Service mungkin memaut ke laman atau sumber pihak ketiga (termasuk di dalam pelan temujanji AI dan peta) dan mungkin membenarkan anda membuka aplikasi lain — sebagai contoh aplikasi tempahan kenderaan yang telah diisi dengan destinasi yang dicadangkan, atau aplikasi pemesejan yang telah diisi dengan jemputan dan kod anda. Sebaik sahaja anda meninggalkan Service untuk aplikasi atau laman lain, terma dan dasar privasi pihak ketiga tersebut terpakai. Kami tidak bertanggungjawab atas kandungan, produk, perkhidmatan, harga atau ketersediaan mereka.</p>

      <h2 id="s15">15. Penafian Waranti</h2>
      <p>15.1 <strong>SERVICE DISEDIAKAN "SEBAGAIMANA ADANYA" DAN "SEBAGAIMANA TERSEDIA", DENGAN SEGALA KECACATAN DAN TANPA APA-APA WARANTI.</strong> Setakat yang dibenarkan undang-undang, Deployku menafikan semua waranti dan syarat, sama ada nyata, tersirat atau berkanun — termasuk apa-apa waranti tersirat kebolehdagangan, kualiti memuaskan, kesesuaian untuk tujuan tertentu, hak milik, penikmatan tenang, ketepatan dan tanpa pelanggaran, dan apa-apa waranti yang timbul daripada cara kami telah berurusan atau apa yang menjadi kebiasaan dalam perdagangan.</p>
      <p>15.2 Khususnya, kami tidak berjanji bahawa: (a) Service akan tidak terganggu, tepat masa, selamat, bebas ralat atau bebas daripada virus atau komponen berbahaya; (b) apa-apa padanan, panggilan, mesej, transkrip, output AI, video Glimpse atau Content lain akan tepat, boleh dipercayai, lengkap atau tersedia; (c) kecacatan akan dibaiki; atau (d) Service akan memenuhi jangkaan anda atau membawa kepada apa-apa hubungan, temujanji atau hasil lain.</p>
      <p>15.3 Sesetengah tempat tidak membenarkan waranti tertentu dikecualikan; di situ, perkara di atas terpakai setakat maksimum yang dibenarkan, dan tiada apa-apa dalam Terma ini yang mengecualikan hak yang tidak boleh dikecualikan secara sah.</p>

      <h2 id="s16">16. Had ke atas Liabiliti Kami</h2>
      <p>16.1 Setakat yang dibenarkan undang-undang, Deployku dan pengarah, pegawai, pekerja, ejen, pemberi lesen dan penyedia perkhidmatannya tidak akan bertanggungan atas: (a) apa-apa ganti rugi tidak langsung, sampingan, khas, berbangkit, teladan atau punitif; (b) keuntungan, hasil, muhibah, data, peluang atau penjimatan jangkaan yang hilang; (c) apa-apa kerosakan daripada penggunaan anda (atau ketidakupayaan untuk menggunakan) Service; (d) kelakuan atau Content mana-mana pengguna atau pihak ketiga, termasuk kelakuan yang berbahaya, menyinggung atau menyalahi undang-undang, dan termasuk pertemuan yang timbul daripada Service; atau (e) akses tanpa kebenaran kepada atau pengubahan data anda — sama ada tuntutan itu berdasarkan waranti, kontrak, tort (termasuk kecuaian), statut atau apa-apa yang lain, dan walaupun kami telah diberi amaran bahawa ganti rugi sedemikian mungkin berlaku.</p>
      <p>16.2 Setakat yang dibenarkan undang-undang, <strong>jumlah liabiliti kami bagi semua tuntutan berkaitan Service atau Terma ini tidak akan melebihi yang lebih besar antara (a) apa yang anda bayar kepada kami dalam 12 bulan sebelum peristiwa di sebalik tuntutan, dan (b) seratus dolar Singapura (SGD 100).</strong></p>
      <p>16.3 Tiada apa-apa dalam Terma ini yang mengecualikan atau mengehadkan liabiliti atas kematian atau kecederaan diri yang disebabkan oleh kecuaian, atas penipuan atau salah nyataan penipuan, atau atas apa-apa yang tidak boleh dikecualikan atau dihadkan di bawah undang-undang. Had dalam Seksyen ini terpakai hanya setakat yang dibenarkan undang-undang.</p>
      <p>16.4 Anda bersetuju bahawa Seksyen 15 dan 16 adalah cara yang adil untuk berkongsi risiko antara kita, dan bahagian asas perjanjian kami — dan bahawa kami tidak dapat menawarkan Service pada terma ini tanpanya.</p>

      <h2 id="s17">17. Indemniti</h2>
      <p>Setakat yang dibenarkan undang-undang, anda bersetuju untuk mempertahankan, menanggung rugi dan melindungi Deployku dan pengarah, pegawai, pekerja, ejen dan penyedia perkhidmatannya daripada apa-apa tuntutan, permintaan, tindakan, kerugian, liabiliti, ganti rugi, kos dan perbelanjaan (termasuk yuran guaman yang munasabah) yang timbul daripada: (a) User Content anda (termasuk video Glimpse dan entri diari); (b) penggunaan atau penyalahgunaan Service oleh anda; (c) pelanggaran anda terhadap Terma ini atau mana-mana undang-undang; (d) interaksi anda dengan pengguna lain, dalam talian atau luar talian; atau (e) pelanggaran anda terhadap hak sesiapa. Kami mungkin, atas perbelanjaan anda, mengambil alih pertahanan dan kawalan eksklusif terhadap apa-apa perkara yang anda akan tanggung rugi, dan anda bersetuju untuk bekerjasama.</p>

      <h2 id="s18">18. Undang-Undang Yang Mentadbir dan Pertikaian</h2>
      <p>18.1 <strong>Undang-undang yang mentadbir.</strong> Terma ini, dan apa-apa pertikaian berkaitannya atau Service (sama ada kontrak atau tidak), ditadbir oleh undang-undang Singapura, dengan mengabaikan peraturan percanggahan undang-undang.</p>
      <p>18.2 <strong>Bercakap dengan kami dahulu.</strong> Sebelum memulakan prosiding formal, e-mel <strong><a href="mailto:admin@deployku.com">admin@deployku.com</a></strong> yang menerangkan pertikaian dan cuba dengan suci hati menyelesaikannya dengan kami selama sekurang-kurangnya 30 hari.</p>
      <p>18.3 <strong>Mahkamah.</strong> Tertakluk kepada Seksyen 18.2, mahkamah Singapura mempunyai bidang kuasa eksklusif ke atas apa-apa pertikaian berkaitan Terma ini atau Service, dan setiap satu daripada kita tunduk kepada mahkamah tersebut. Tiada apa-apa di sini yang menghalang mana-mana satu daripada kita daripada mendapatkan relief injunksi segera di mana-mana mahkamah yang berwibawa, atau mengehadkan apa-apa hak pengguna mandatori yang anda miliki untuk membawa prosiding di tempat anda tinggal.</p>
      <p>18.4 <strong>Tiada tindakan kelas.</strong> Setakat yang dibenarkan undang-undang, anda mesti membawa pertikaian secara individu, bukan sebagai plaintif atau ahli kelas dalam apa-apa prosiding kelas, kolektif atau perwakilan.</p>
      <p>18.5 <strong>Had satu tahun.</strong> Setakat yang dibenarkan undang-undang, apa-apa tuntutan berkaitan Service mesti dimulakan dalam tempoh satu (1) tahun selepas ia timbul; selepas itu ia dihalang secara kekal.</p>

      <h2 id="s19">19. Am</h2>
      <p>19.1 <strong>Perubahan pada Terma ini.</strong> Kami mungkin mengemas kini Terma ini. Jika perubahan adalah material, kami akan memberitahu anda melalui App atau cara munasabah lain, dan Terma yang dikemas kini akan menunjukkan tarikh berkuat kuasa baharu. Menggunakan Service selepas tarikh tersebut bermakna anda menerima Terma baharu. Jika anda tidak bersetuju, berhenti menggunakan Service dan, jika anda mahu, padam Account anda.</p>
      <p>19.2 <strong>Keseluruhan perjanjian.</strong> Terma ini, dengan <a href="privacy.html">Dasar Privasi</a> dan apa-apa terma tambahan yang ditunjukkan untuk ciri atau pembelian tertentu, adalah keseluruhan perjanjian antara anda dan Deployku tentang Service, dan menggantikan apa-apa perjanjian terdahulu mengenai topik tersebut.</p>
      <p>19.3 <strong>Keterasingan.</strong> Jika mana-mana bahagian Terma ini didapati tidak sah atau tidak boleh dikuatkuasakan, bahagian tersebut diterapkan setakat mungkin dan selebihnya kekal berkuat kuasa.</p>
      <p>19.4 <strong>Tiada penepian.</strong> Jika kami tidak menguatkuasakan hak atau peraturan, itu bukan penepian terhadapnya. Apa-apa penepian mesti secara bertulis dan ditandatangani oleh kami.</p>
      <p>19.5 <strong>Penyerahan hak.</strong> Anda tidak boleh menyerahkan hak atau memindahkan Terma ini atau Account anda. Kami boleh menyerahkan hak atau memindahkannya (secara keseluruhan atau sebahagian) dengan bebas, termasuk dalam penggabungan, pengambilalihan, penyusunan semula atau penjualan aset.</p>
      <p>19.6 <strong>Peristiwa di luar kawalan kami.</strong> Kami tidak bertanggungan atas apa-apa kelewatan atau kegagalan yang disebabkan oleh perkara di luar kawalan munasabah kami, termasuk bencana alam, wabak, peperangan, keganasan, kekacauan awam, pertikaian buruh, tindakan kerajaan, kegagalan utiliti atau telekom, atau kegagalan penyedia pihak ketiga.</p>
      <p>19.7 <strong>Tiada perkongsian.</strong> Terma ini tidak mewujudkan apa-apa perkongsian, usaha sama, pekerjaan, fidusiari atau hubungan agensi antara anda dan Deployku.</p>
      <p>19.8 <strong>Pengekalan.</strong> Bahagian Terma ini yang menurut sifatnya sepatutnya berterusan selepas penamatan akan terus berkuat kuasa, termasuk Seksyen 6.5, 7, 10, 11, 14–19.</p>
      <p>19.9 <strong>Bahasa.</strong> Terma ini ditulis dalam bahasa Inggeris. Apa-apa terjemahan adalah untuk kemudahan sahaja; jika terdapat percanggahan, versi bahasa Inggeris yang diguna pakai, kecuali di mana undang-undang menyatakan sebaliknya.</p>
      <p>19.10 <strong>Komunikasi elektronik.</strong> Anda bersetuju untuk menerima komunikasi daripada kami secara elektronik (notis dalam aplikasi, pemberitahuan tolak, SMS ke nombor berdaftar anda, atau e-mel di mana disediakan), dan bahawa ini memenuhi apa-apa keperluan undang-undang untuk komunikasi bertulis.</p>

      <h2 id="s20">20. Hubungi</h2>
      <p><strong>Deployku Pte Ltd</strong><br />
      E-mel: <strong><a href="mailto:admin@deployku.com">admin@deployku.com</a></strong></p>
      <p>Untuk sokongan, rayuan, notis undang-undang dan tuntutan pelanggaran, gunakan e-mel di atas dan sertakan butiran yang mencukupi untuk kami mencari Account anda dan mengendalikan permintaan anda.</p>

      <p class="doc-note">Dengan menggunakan Heqiyou, anda mengesahkan bahawa anda telah membaca, memahami dan bersetuju dengan Terma dan Syarat ini serta <a href="privacy.html">Dasar Privasi</a> yang disertakan.</p>

    `
};
